
local goals = {}

local function AddPrefabToGoals(prefab,atlas,tex,name)
	local tab = {}
	tab.prefab = prefab
	tab.text = name or GLOBAL.STRINGS.NAMES[string.upper(prefab)] or "No Name"
	tab.tex = tex or prefab..".tex"
	tab.atlas = atlas or "images/victims_tropical_experience.xml"
	return tab
end

local prefabs = {
	"adult_flytrap",
	"ancient_herald",
	"ancient_hulk",
	{prefab = "antman",name = "Mant Worker"},
	"antman2",
	{prefab = "antman_warrior",name = "Mant Warrior"},
	"antman_warrior_egg",
	"antqueen",
	"ballphin",
	"ballphin2",
	"bear",
	"bill",
	"billsnow",
	"toucan_hamlet",
	"parrot_blue",
	"kingfisher",
	"bishopwater",
	"chicken",
	"clam",
	"commonfish",
	--"coralfish",
	"cormorant",
	"crab",
	"crocodog",
	"poisoncrocodog",
	"watercrocodog",
	"doydoybaby",
	"doydoy",
	"dragoon",
	"dungbeetle",
	"elephantcactus",
	--"firetwister_seal",
	"fish_coi",
	"fish2_alive",
	"fish3_alive",
	"fish4_alive",
	"fish5_alive",
	"fish6_alive",
	"fish7_alive",
	--"quagmire_salmom_alive",
	"mecfish_alive",
	"goldfish_alive",
	--"flame_elemental_tfc",
	"flup",
	"frog_poison",
	"frog_poison2",
	"giantgrub",
	"giantsnow",
	"glowfly",
	"glowfly_cocoon",
	"gnat",
	"goldbishop",
	"goldmonkey",
	"tikiman",
	"grabbing_vine",
	"hippopotamoose",
	"icebearger",
	"icedeerclops",
	"jellyfish_underwater",
	"jungletreeguard",
	"kelpy",
	"knightboat",
	"kraken",
	"krakenunderwater",
	"beetletaur",
	"bossboarte",
	"rhinodrill",
	"rhinodrill2",
	"lizardman_tfc",
	"lobsterunderwater",
	"mammoth",
	"mandrakeman",
	"maxwellboss",
	"mean_flytrap",
	--"mermfisherunderwater",
	"mermfisherguardunderwater",
	"merm1",
	"merm2",
	"mermfisher",
	"mermfisherpirate",
	"mermfisherguard",
	"octopus",
	"otter",
	"ox",
	"oxbaby",
	"packim",
	"panda",
	"pangolden",
	"parrot",
	"parrot_pirate",
	"peagawk",
	"peagawk_prism",
	"peekhen",
	"pigbandit",
	{prefab = "piggolem",name = "Pig Golem"},
	"pigman_beautician",
	"pigman_florist",
	{prefab = "pigman_erudite",name = "Pig Erudite"},
	{prefab = "pigman_hatmaker",name = "Pig Hatmaker"},
	"pigman_storeowner",
	"pigman_banker",
	"pigman_collector",
	{prefab = "pigman_hunter",name = "Pig Hunter"},
	"pigman_mayor",
	"pigman_mechanic",
	{prefab = "pigman_professor",name = "Pig Professor"},
	{prefab = "pigman_usher",name = "Pig Usher"},
	"pigman_royalguard",
	{prefab = "pigman_royalguard_2",name = "Royal Guard 2"},
	"pigman_farmer",
	"pigman_miner",
	{prefab = "pigman_queen",name = "Pig Queen"},
	"pig_eskimo",
	"pig_shopkeeper",
	"pig_royalguard_rich",
	"pig_royalguard_rich_2",
	"pigman_royalguard_3",
	"piko",
	"piko_orange",
	{prefab = "pinkman",name = "Pink Man"},
	"pirateghost",
	"pigghost",
	"pog",
	"primeape",
	"pugalisk",
	"quagmire_pigeon",
	"rabid_beetle",
	"rainbowjellyfish",
	"reef_jellyfish",
	"ro_bin",
	--"roe",
	"rookwater",
	"scorpion",
	"sea_eel",
	"seagull",
	"seaquaketentacle",
	"seatentacle",
	"sharkitten",
	"sharx",
	"sharxunderwater",
	"shrimp",
	"slip",
	"slipstor",
	"snake",
	"snake_poison",
	"snake_amphibious",
	"snapdragon",
	"snowbeetle",
	"snowgoat",
	--"snowperd",
	"spider_snow",
	"spider_snow2",
	--"snowwarg",
	"solofish",
	"spider_ape",
	"spider_monkey",
	"spiky_monkey_tfc",
	"spiky_turtle_tfc",
	"squidunderwater",
	"squidunderwater2",
	"strange_scorpion_tfc",
	"stungray",
	"stungrayunderwater",
	"summerwalrus",
	"swordfish",
	"swordfishunderwater",
	--"tentacleunderwater",
	"thunderbird",
	"tigershark",
	"toucan",
	"trapslug",
	"treeguard",
	"twister",
	"twister_seal",
	"vampirebat",
	--"circlingbat",
	"weevole",
	"whale_blue",
	"whale_white",
	--"whale_bluefinal",
	"wildbeaver",
	"wildbeaverguard",
	"wildbore",
	"wildboreguard",
	--"yeti",
	"zeb",
}



AddSimPostInit(function()
	for _,v in ipairs(prefabs) do
		if type(v) == "table" then
			local goal = AddPrefabToGoals(v.prefab,v.atlas,v.tex,v.name)
			table.insert(goals,goal)
		else
			local goal = AddPrefabToGoals(v)
			table.insert(goals,goal)
		end
	end
	GLOBAL.AddCustomGoals(goals,"TropicalExperience")
end)