return {
	NAMES = {
		QUESTBOARD = "Tableau de quête",
		REQUEST_QUEST = "Requête",
		REQUEST_QUEST_VERY_EASY = "Requête très facile",
		REQUEST_QUEST_EASY = "Requête facile",
		REQUEST_QUEST_NORMAL = "Requête normale",
		REQUEST_QUEST_DIFFICULT = "Requête difficile",
		REQUEST_QUEST_VERY_DIFFICULT = "Requête très difficile",
		REQUEST_QUEST_SPECIFIC = "Requête",
		GLOMMERFUELMACHINE = "Machine de glommerfuel sombre",
		GLOMMER_LIGHTFLOWER = "La fleur de lumière de Glommer",
		CHESTER_BOSS = "Chester le cauchemar",
		NIGHTMARECHESTER = "Chester le cauchemar",
		NIGHTMARECHESTER_EYEBONE = "Os de l'œil de Nightmare Chester",
		GLOMMER_SMALL = "Tempête de glace Glommer",
		GLOMMER_BOSS = "Blizzard Glommer",
		BLACKGLOMMERFUEL = "Sombre Glommerfuel",
		["ADDITIONAL QUEST SLOTS"] = "Créneau de quêtes supplémentaires",
		SHADOW_CREST = "Crête de l'ombre",
		SHADOW_MITRE = "Mitre de l'ombre",
		SHADOW_LANCE = "Lance de l'ombre",
		FROGKING = "Roi des Grenouilles",
		FROGKING_P_CROWN = "Couronne de grenouille",
		FROGKING_SCEPTER = "Sceptre de la grenouille",
		FROGKING_BEYBLADE = "Toupie diamantée",
	},
	DESCRIBE = {
		QUESTBOARD = "Je pense en connaitre certain...",
		REQUEST_QUEST = "On dirait que quelqu'un aurait perdu une requête quelque part. Autant meilleur pour moi!",
		REQUEST_QUEST_VERY_EASY = "On dirait que quelqu'un aurait perdu une requête quelque part. Autant meilleur pour moi!",
		REQUEST_QUEST_EASY = "On dirait que quelqu'un aurait perdu une requête quelque part. Autant meilleur pour moi!",
		REQUEST_QUEST_NORMAL = "On dirait que quelqu'un aurait perdu une requête quelque part. Autant meilleur pour moi!",
		REQUEST_QUEST_DIFFICULT = "On dirait que quelqu'un aurait perdu une requête quelque part. Autant meilleur pour moi!",
		REQUEST_QUEST_VERY_DIFFICULT = "On dirait que quelqu'un aurait perdu une requête quelque part. Autant meilleur pour moi!",
		REQUEST_QUEST_SPECIFIC = "On dirait que quelqu'un aurait perdu une requête quelque part. Autant meilleur pour moi!",
		GLOMMERFUELMACHINE = "Un dieu a apporté sa bénédiction à cette machine !",
		GLOMMER_LIGHTFLOWER = "Un cadeau d'un dieu !",
		CHESTER_BOSS = "Je n'aurais pas dû faire ça ! Je n'aurais PAS dû faire ça !",
		NIGHTMARECHESTER = "Il a l'air un peu énervé mais je ne pense pas qu'il l'est.",
		NIGHTMARECHESTER_EYEBONE = "Même l'ocelle a l'air ennuyé !",
		GLOMMER_SMALL = "Oh il est si gentil et si petit... Oh mon dieu pourquoi m'attaque-t-il?!",
		GLOMMER_BOSS = "Il s'est réveillé et il est là pour nous tuer!",
		BLACKGLOMMERFUEL = "Une substance sombre et visqueuse, peut être utilisée pour piéger d'autres monstres!",
		SHADOW_CREST = "Un peu macabre d'avoir son ennemi sur sa tête mais c'est trop bien !",
		SHADOW_MITRE = "On dirait qu'il y a encore un peu de l'évêque de l'ombre dedans...",
		SHADOW_LANCE = "Une arme assoiffée de sang on dirait, surtout contre les ennemis lunaires !",
		FROGKING = "Celui-là a l'air effrayant!",
		FROGKING_P_CROWN = "Une couronne qui fera que toutes les grenouilles vous verront comme leur roi !",
		FROGKING_SCEPTER = "Un sceptre qui dirige ses sujets d'une main de fer",
		FROGKING_BEYBLADE = "Mieux vaut ne pas être touché par celle-là !",
	},
	RECIPE_DESC = {
		QUESTBOARD = "Commencer à quêter!",
		REQUEST_QUEST = "Pour une requête aléatoire!",
		REQUEST_QUEST_VERY_EASY = "Requête très facile aléatoire",
		REQUEST_QUEST_EASY = "Requête facile aléatoire",
		REQUEST_QUEST_NORMAL = "Requête normale aléatoire",
		REQUEST_QUEST_DIFFICULT = "Requête difficile aléatoire",
		REQUEST_QUEST_VERY_DIFFICULT = "Requête très difficile aléatoire",
		REQUEST_QUEST_SPECIFIC = "Requête",
		GLOMMERFUELMACHINE = "Vous ne pouvez pas fabriquer des choses pieuses!",
		GLOMMER_LIGHTFLOWER = "Vous ne pouvez pas fabriquer de choses pieuses!",
	},
	ATTACKWAVES = {
		MISSION_FAILED = "Mission échouée...",
		MISSION_SUCCESS = "Mission accomplie!",
		MISSION_OBJECTIVE = "Je dois protéger %s!",
		TIME_LEFT = "Temps restant jusqu'à l'arrivée de %s: %i",
		ENEMIES_LEFT = "Cette vague contient %s ennemis que vous devez vaincre",
		WAVE = "Vague %s\n%s/%s ennemis",
	},
	ACTIONS = {
		FIGHT_GLOMMER = "Être un ami?!",
		SHADOW_ROOK_ATTACK = "Attaque de la tour de l'ombre",
	},
	REQUEST_QUEST = {
		FULL_LOG = "J'ai déjà und tableau de quête plein!",
		QUEST_ADDED = "Quête ajoutée!",
	},
	TALKING = {
		REWARDS = "J'ai obtenu les récompenses de ma bataille!",
	},
	REWARDS = {
		health = "Bonus Santé pour x min",
		sanity = "Bonus Santé mentale pour x min",
		hunger = "Bonus faim pour x min",
		sanityaura = "Bonus Sanityaura pour x min",
		hungerrate = "Taux de faim pour x min",
		healthrate = "Santé toutes les 10 secondes pendant x min",
		damage = "Bonus de dommages pour x min",
		damagereduction = "Bonus de réduction des dommages pour x min",
		range = "Bonus de gamme pour x min",
		winterinsulation = "Bonus isolation hivernale pour x min",
		summerinsulation = "Bonus d'isolation d'été pour x min",
		worker = "Bonus de travail pour x min",
		sleeping = "Bonus de sommeil pour x min",
		nightvision = "Vue de nuit pour x min",
		speed = "Bonus de vitesse pour x min",
		escapedeath = "fois échapper la mort pour x min",
		planardamage = "Bonus de dégâts planaires pendant x min",
		planardefense = "Bonus de défense planaire pendant x min",
		dodge = "temps de recharge bonus d'esquive pendant x min",
		crit = "Chance critique de faire 1,5x les dégâts pendant x min",
		waterproofness = "Bonus d'imperméabilité pour x min",
	},
	QUEST_BOARD = {
		QUEST_BOARD = "Tableau de quête",
		LOOK_FOR_QUESTS = "Chercher une nouvelle quête",
		LOOK_FOR_QUESTS_ACCEPTED = "Déjà accepté une nouvelle quête!",
		LOOK_FOR_QUESTS_MAX = "J'ai la quantité max de quête!",
		OBTAIN_LEVEL_REWARDS = "Recevoir récompenses niveau",
		CREATE_NEW_QUESTS = "Créer nouvelles quêtes",
		IN_CAVES = "Pas possible dans les grottes!",
		CLOSE = "Fermer",
		NO_NAME = "Aucun Nom",
		REWARDS = "Récompenses",
		ACCEPT_QUEST = "Accepter quête",
		ALREADY_ACCEPT_QUEST = "Déjà accepté une quête!",
		REWARD_LEVEL = "Récompense niveau",
		ACCEPTED_REWARDS = "Récompense accepté pour niveau",
		LEVEL = "Niveau",
		REWARD1 = "Récompense 1",
		REWARD2 = "Récompense 2",
		REWARD3 = "Récompense 3",
		DIFFICULTY = "Difficulté",
		VICTIM = "Victime",
		AMOUNT = "Quantité",
		AMOUNT_OF_KILLS = "Quantité of victime",
		POINTS = "Points",
		TITLE = "Titre",
		WRITE_DESCRIPTION = "Écrire Description",
		ADD_QUEST = "Ajouter quête aux sources de quêtes",
		SAVE_DESCRIPTION = "Sauvegarder Description",
		YES = "Oui",
		NO = "Non",
		ASK_ADD_QUEST = "Est-ce que tu es sûr que tu veux ajouter cette quêtes aux sources de quêtes?",
		QUEST = "Quête",
		ADDED_SUCCESFULLY = "Ajouté avec succès",
		QUEST_EXISTS = "La quête avec ce nom existe déjà. Veuillez en choisir un autre.",
		NUMBERS = "Nombres",
		FOODS = "Repas",
		ITEMS = "Articles",
		REMOVE_QUEST = "Retirer la quête des sources de quête",
		ASK_REMOVE_QUEST = "Supprimer la quête \"%s\"?",
		MANAGE_QUESTS = "Gérer les quêtes personnalisées",
		REQUIREMENTS = "Prérequis",
		EDIT_QUEST = "Modifier la quête",
		ASK_OVERWRITE_QUEST = "Voulez-vous échanger la quête %s pour cette version ? La quête sera supprimée du journal des quêtes de tous les joueurs !",
	},
	QUEST_LOG = {
		EMPTY_SLOT = "Créneau\nde quête\nvide",
		BUTTON = "Ouvrir le journal des quêtes",
		NO_NAME = "Aucun Nom",
		DESCRIPTION = "Description",
		REWARDS = "Récompenses",
		NOT_DEFINED = "Pas defini",
		GET_REWARDS = "Recevoir Récompenses!",
		RECEIVE_REWARDS = "Recu les récompenses pour la quête",
		FORFEIT_QUEST = "Abandonner quête",
		QUEST_LOG = "Journal de quêtes",
		CLOSE = "Fermer",
		PAGE_1 = "Première page de quêtes",
		PAGE_2 = "Deuxième page de quêtes",
		PAGE_3 = "Troisième page de quêtes",
		PAGE_4 = "Quatrième page de quêtes",
		PAGE_5 = "Cinquième page de quêtes",
		PAGE_6 = "Sixième page de quêtes",
		SCOREBOARD = "Tableau",
		CURRENT_LEVEL = "Niveau présent",
		POINTS = "Points",
		LEVEL = "Niveau",
		YES = "Oui",
		NO = "Non",
		BOSSFIGHT = "Boss de fin lutte!",
		COMPLETED_QUESTS = "Quêtes complétés",
		TOTAL_POINTS = "Points total",
		ASK_FORFEIT = "Est-ce que tu es sûr que tu veux abandonner cette quête?",
		SUCCESS = "Complété avec succès!",
		HEALTHBONUS = "Augmentation de la santé:",
		SANITYBONUS = "Augmentation de la raison:",
		HUNGERBONUS = "Augmentation de la faim:",
		SPEEDBONUS = "Augmentation de la vitesse:",
		WINTERINSULATIONBONUS = "Augmentation de l'isolation à froid:",
		SUMMERINSULATIONBONUS = "Augmentation de l'isolation thermique:",
		WORKMULTIPLIERBONUS = "Multiplicateur de travail:",
		KILL = "Tuer",
		PROGRESS = "Progrès",
		SHOW_BONUS = "Afficher le bonus",
		CURR_RANK = "Rang actuel\n\nPoints jusqu'au prochain rang: ",
		QUEST_LINE = "Cette quête fait partie d'une ligne de quêtes!",
		SCALING = "Quête évolutive (peut devenir plus difficile si vous la terminez)",
	},
	TEMP_BONI = {
		HEALTH = " Santé",
		SANITY = " Santé mentale",
		HUNGER = " Faim",
		SANITYAURA = "/min Aura de santé mentale",
		HUNGERRATE = "% Taux de faim",
		HEALTHRATE = " Santé toutes les 10 secondes",
		DAMAGE = " Dommages",
		DAMAGEREDUCTION = "% Réduction des dommages",
		RANGE = " Gamme",
		WINTERINSULATION = " Isolation hivernale",
		SUMMERINSULATION = " Isolation d'été",
		WORKER = "% Efficacité du travail",
		SLEEPING = " Santé/Sanité par seconde de dormir",
		NIGHTVISION = "Vision nocturne",
		SPEED = " % de Vitesse",
		ESCAPEDEATH = " fois échapper à la mort",
		PLANARDAMAGE = " Dommages planaires",
		PLANARDEFENSE = " Défense planaire",
		DODGE = "Esquive tous les %s secondes",
		CRIT = "% de chances critiques d'infliger 1,5 fois les dégâts",
		TIME_LEFT = "Temps restant :",
		WATERPROOFNESS = "% d'imperméabilité",
	},
	LOADING_TIPS = {
		request = "Les requêtes peuvent tomber des créatures tuées. Vous pouvez également activer leur fabrication dans les options de configuration !",
		questboard = "Construisez un tableau de quêtes pour avoir accès à une nouvelle quête chaque jour et, si vous l'activez, la possibilité de créer vos propres quêtes !",
		attackwaves = "Les quêtes où vous devez protéger une créature commenceront après un laps de temps aléatoire après avoir accepté la quête",
		bossfight = "Les combats de boss peuvent être lancés depuis le journal des quêtes. Chaque fois que vous montez de niveau, vous avez une chance de pouvoir commencer un combat de boss ! Vous ne perdrez pas vos objets si vous mourez, mais si vous gagnez, il y aura une récompense pour vous !",
		temporarybonus = "Certaines quêtes te donneront un bonus temporaire comme récompense. Tu verras celles qui sont actives en haut de ton écran. Le nombre maximum de bonus est de 5, si vous en obtenez plus, les plus anciens seront supprimés.",
		quest_line = "Certaines quêtes font partie d'une ligne de quête. Les quêtes qui suivent la quête de départ seront ajoutées automatiquement et ne peuvent être obtenues autrement. Ces quêtes auront une ampoule.",
		levelupcomponent = "Si vous avez activé le système de niveau, vous deviendrez plus fort à chaque niveau gagné. Vous gagnez des points en accomplissant des quêtes et en battant des créatures. Le bonus peut être vu sur la page de gauche dans le journal des quêtes.",
	},
	QUESTS = {
		["The Wicked Mist Fury"] = {
			NAME = "La méchante fureur des brumes",
			DESCRIPTION = "Ces embêtants marcheurs des mers ruinent le lieu de retraite qu'est le Biome gorgé d'eau.\nS'il vous plaît, aidez-nous à nous en débarrasser, afin que nous puissions reposer en paix dans ce bel endroit !",
		},
		["The Powerful Shadow from Below"] = {
			NAME = "L'ombre puissante d'en dessous",
			DESCRIPTION = "Ces ombres terrifiantes nous attaquent dès que nous mettons les voiles!\nNous ne savons pas comment leur échapper, encore moins comment les vaincre.\nSi seulement un aventurier courageux pouvait nous aider!",
		},
		["The Reckoning of the Gestalt"] = {
			NAME = "Le jugement de la Gestalt",
			DESCRIPTION = "Les Gestalts ont faim de votre illumination!\nRestez %s secondes d'affilée à plus de 85%% d'illumination sur l'île lunaire pour rassembler leur offrande.",
			COUNTER = "Secondes",
			HOVER = "Restez à plus de 85%% de Lunacy pendant %s secondes d'un coup !",
		},
		["The Corrupt Prophecy Revenge"] = {
			NAME = "La vengeance de la prophétie corrompue",
			DESCRIPTION = "Une prophétie autrefois prédite mentionnait que l'adoration d'un monstre insectoïde apporterait paix et richesse à cette terre désolée.\nMais regardez où cela nous a mené ! Seuls les monstres autour de nous, pas assez à manger et la nuit est la partie la plus effrayante de tout ça !\nPour nous venger de cette prophétie, nous voulons que vous éliminiez ce monstre insectoïde nommé Glommer !\nSigné, le roi des cochons.",
		},
		["The Monstrous Delicacy"] = {
			NAME = "La Délicatesse Monstrueuse",
			DESCRIPTION = "On m'a offert une lasagne monstre apparemment délicieuse d'un cuisinier connu mais je veux être sûr que ça ne me tuera pas si j'essaye de la manger !\nSi quelqu'un pouvait en manger cinq pour me montrer que mes doutes étaient infondés, je le ferais récompensez-les en conséquence !",
			COUNTER = "Monsterlasagna",
			HOVER = "Mangez %s Monsterlasagna",
		},
		["The Explorers End"] = {
			NAME = "La fin des explorateurs",
			DESCRIPTION = "Un scientifique nous a parlé d'une créature extrêmement dangereuse qui apparaît après avoir assemblé le siphonateur lunaire.\nIl s'appelle Champion céleste.\nJe crains pour ma vie !\nVeuillez détruire ce monstre et ramener la paix dans le monde !\nEn récompense, je le ferai dupliquez chaque objet qui se trouve dans votre inventaire lorsque vous acceptez la récompense !\n(Cela exclut les objets de votre sac à dos !)",
		},
		["Within the Labyrinth"] = {
			NAME = "Dans le labyrinthe",
			DESCRIPTION = "Le Minotaure, la créature mythique de nombreux contes, est apparu dans ce monde !\nComme il a été prédit, il se tient dans le Labyrinthe.\nVeuillez le vaincre pour que mes enfants puissent y jouer à nouveau, ils ne m'énervent vraiment que être à la maison !",
		},
		["The Stone from Below"] = {
			NAME = "La pierre d'en bas",
			DESCRIPTION = "Je voudrais analyser quelques fossiles que l'on peut trouver dans ce monde.\nMalheureusement, je ne peux pas creuser pour eux dans les grottes car je ne suis pas assez fort pour y survivre.\nSi quelqu'un pouvait m'aider, je serais très reconnaissant!",
			COUNTER = "Fossiles",
			HOVER = "Trouver %s fossiles",
		},
		["Beyond the Charming Hamlet"] = {
			NAME = "Au-delà du charmant hameau",
			DESCRIPTION = "Ces hommes-cochons envahissent ce monde !\nIls se reproduisent à un rythme alarmant et laissent des excréments partout.\nVeuillez contrôler la population.",
		},
		["Corpses of the Swampy Badlands"] = {
			NAME = "Cadavres des Badlands marécageux",
			DESCRIPTION = "Beaucoup d'aventuriers sont morts en essayant de terminer cette mission, j'espère que vous ne serez pas l'un d'entre eux !\n Nous avons besoin des tentacules sortis du marais pour pouvoir voyager en paix.",
		},
		["The Bane of Lake Nen"] = {
			NAME = "Le fléau du lac Nen",
			DESCRIPTION = "Notre lac Nen n'est pas très loin de votre monde et parfois, nous recevons la visite du terrible Malbatross.\nIl vole tous nos poissons dont nous avons besoin pour survivre !\nS'il vous plaît, je vous en prie, battez ce monstre ainsi que nous n'avons pas à mourir de faim !",
		},
		["The Scorched Nightmare Amulet"] = {
			NAME = "L'amulette du cauchemar brûlé",
			DESCRIPTION = "Je veux voir à quel point vous pouvez survivre!\nÉquipez-vous d'une amulette de cauchemar et surchauffez en même temps pendant %s secondes d'un coup.\nMais n'osez pas ne pas faire l'une de ces choses même une seconde, car j'ai gagné ne l'accepte pas!\nVoyons si vous pouvez le faire!",
			COUNTER = "Secondes brûlantes",
			HOVER = "Rester fou et surchauffé pendant %s secondes à la fois",
		},
		["The Fearful Trial"] = {
			NAME = "Le procès effrayant",
			DESCRIPTION = "Je veux que vous vous débarrassiez de tous les grands patrons saisonniers en un an.\nCe qui signifie : \nAutumn = Bearger\nWinter = Deerclops\nSpring = Moose/Goose\nSummer = Antlion\n\nSi vous parvenez à tous les vaincre en un an , vous serez généreusement récompensé !",
			COUNTER = "Bosses",
			HOVER = "Tuer les 4 boss saisonniers en un an",
		},
		["Across the Desert"] = {
			NAME = "À travers le désert",
			DESCRIPTION = "J'ai entendu parler d'une étrange créature vivant dans le désert.\nApparemment, elle se met en colère très vite et seules les offrandes peuvent aider à l'apaiser.\nMalheureusement, nous n'avons presque plus de telles offrandes !\nSi quelqu'un pouvait la vaincre, nous serions pour toujours reconnaissant!",
		},
		["The Corrupt Darkness"] = {
			NAME = "Les ténèbres corrompues",
			DESCRIPTION = "Je fais actuellement des tests pour analyser la force de Charlie.\nJ'aurai besoin d'un volontaire pour absorber quelques coups d'elle.\nSi vous avez un trait masochiste, veuillez accepter!",
			COUNTER = "Coups",
			HOVER = "Prendre %s coups de Charlie",
		},
		["The Legend of the Trade Road"] = {
			NAME = "La légende de la route commerciale",
			DESCRIPTION = "Nous aimerions renforcer nos relations commerciales avec les hommes cochons.\nPour ce faire, nous avons besoin que vous effectuiez quelques échanges avec le Roi cochon en notre nom.\nVous serez rémunéré en conséquence!",
			COUNTER = "marché",
			HOVER = "Faire %s transactions avec le Roi des Cochons",
		},
		["The Vampire Dungeon"] = {
			NAME = "Le donjon des vampires",
			DESCRIPTION = "Nous essayons d'explorer le sous-sol, mais malheureusement nous avons atteint un point où nous sommes coincés !\nCes chauves-souris vampires nous aspirent !\nVeuillez les vaincre pour que nous puissions avancer !",
		},
		["Within the Stream"] = {
			NAME = "Dans le flux",
			DESCRIPTION = "J'ai besoin d'échantillons des différents poissons qui vivent dans les océans de ce monde.\nAttrapez %s poissons et rapportez les résultats!",
			COUNTER = "Poissons pêchés",
			HOVER = "Attraper %s poissons",
		},
		["Mage of the Manor Baldur"] = {
			NAME = "Mage du Manoir Baldur",
			DESCRIPTION = "Moi, le Grand Mage du Manoir Baldur, je vous invite à passer un examen!\nVous devrez téléporter un Deerclops loin!\nIndice: vous pouvez utiliser un bâton de télélocalisation.\nVoyons si vous avez le pouvoir magique en vous pour accomplir cette!",
			HOVER = "Téléportation de Deerclops au loin",
			COUNTER = "Cerf-volant",
		},
		["The Rage of Ioun"] = {
			NAME = "La rage de Ioun",
			DESCRIPTION = "Je suis Ioun. Mon père n'a pas été revu depuis qu'il est entré dans les bois pour ramasser de la soie.\nJe suis sûr que les araignées sont à blâmer !\nLa rage commence à me consumer, mais je ne suis pas assez fort pour maintenir ce désir de vengeance ! \nS'il vous plaît, aidez-moi !",
		},
		["The Sack For the Unlucky"] = {
			NAME = "Le sac pour les malchanceux",
			DESCRIPTION = "J'ai entendu dire que vous aimiez le Krampussack.\nMais j'ai aussi entendu dire que vous n'avez pas de chance, mes condoléances.\nEn tant qu'offre que vous ne pouvez pas refuser, je vous donnerai un Krampussack si vous en battez suffisamment !",
		},
		["Below the Abandoned Land"] = {
			NAME = "Sous les terres abandonnées",
			DESCRIPTION = "J'ai entendu dire qu'il y a des trésors inestimables à trouver dans les terres souterraines. \nFaisons un échange, je te donne l'emplacement et tu vas le chercher. \nEnsuite, nous pourrons partager le butin ! \nLes trésors peuvent être trouvés dans les stalagmites qui poussent sous terre.",
			COUNTER = "Stalagmites",
			HOVER = "Trouvez un trésor dans les stalagmites des grottes",
		},
		["A Cute Companion"] = {
			NAME = "Un compagnon mignon",
			DESCRIPTION = "J'aime Chester, je l'aime vraiment, vraiment, vraiment ! \nJe veux qu'il ait un ami avec qui jouer. \nJ'ai entendu dire qu'il y avait une créature semblable à lui dans le sous-sol. \nS'il vous plaît, allez le chercher pour Chester et moi !",
			HOVER = "Tenir le bocal à poissons de Hutch",
		},
		["The Allies Within the Land"] = {
			NAME = "Les alliés au sein du pays",
			DESCRIPTION = "Tout le monde a besoin d'amis ! \nC'est pourquoi je veux aider les gens à en trouver. \nEt quelle meilleure motivation qu'une récompense... \nSi tu trouves 10 amis qui te suivent, qu'il s'agisse de cochons, d'araignées ou de n'importe quoi d'autre, je m'en fiche, je te récompenserai !",
			COUNTER = "Suiveurs",
			HOVER = "Avoir %s suiveurs en même temps",
		},
		["Orcus's Living Dead"] = {
			NAME = "Les morts-vivants d'Orcus",
			DESCRIPTION = "Ces chiens qui sont apparus sur l'île lunaire ne sont pas normaux, ils irradient la mort ! \nJe veux qu'ils soient éradiqués avant que des choses pires n'arrivent !",
		},
		["The Damned Legacy"] = {
			NAME = "L'héritage des damnés",
			DESCRIPTION = "Bonjour, je m'appelle Wilba, tu me connais peut-être d'un autre continent. \nComme je devais perpétuer l'héritage de mon père, je me transforme en Werepig à chaque pleine lune. \nMais je ne veux plus ! \nJ'ai entendu dire que la malédiction peut être brisée si tu défends la base de pierre de lune %s fois contre les porcs-garous et les chiens !",
			COUNTER = "Temps défendu",
			HOVER = "Défendre la base lunaire %s fois",
		},
		["The Abandoned Chester"] = {
			NAME = "Le Chester abandonné",
			DESCRIPTION = "Mon maître, l'Ancien Tisseur de combustible, m'a complètement oublié et m'a laissé me débrouiller tout seul dans ce monde cruel ! \nJe sens déjà que je vais bientôt être attaqué, aidez-moi à me défendre !",
			COUNTER = "Vagues d'attaque",
			HOVER = "Protégez le Chester!",
		},
		["The Sharks Demise"] = {
			NAME = "Le déclin des requins",
			DESCRIPTION = "Pardonne-moi, aventurier. Votre aide est requise. \nLa nature est troublée et pour de bonnes raisons. \nUne sorte de force démoniaque s'est insinuée dans ces terres, petite au début, mais elle devient plus forte chaque jour. \nCe n'est qu'une question de temps avant que nous ne puissions plus les arrêter. \nS'il te plaît, héros, cherche leur source, détruis-la et débarrasse-toi de ces misérables Rockjaws. \nHéros, agissez rapidement lorsque vous traitez avec les Rockjaws. \nTu peux en éliminer autant que tu veux, moins il y a de ces voyous dans ce monde, mieux c'est.",
		},
		["The Houndstooth Curse"] = {
			NAME = "La malédiction des dents de chiens",
			DESCRIPTION = "J'ai besoin de ton aide, aventurier!\nLes méchants Wargs ont ravagé notre petit village de cochons!\nVeuillez les vaincre pour que nous puissions vivre à nouveau en paix !",
		},
		["The Possessed Crows"] = {
			NAME = "Les corbeaux possédés",
			DESCRIPTION = "Nos champs sont ravagés par les corbeaux. \nIls semblent être possédés par des forces obscures. \nMalheureusement, je ne pense pas qu'il y ait d'espoir pour eux. \nS'il vous plaît, débarrassez-vous d'eux, sinon ma famille va mourir de faim !",
		},
		["Colors of the Rainbow"] = {
			NAME = "Les couleurs de l'arc-en-ciel",
			DESCRIPTION = "Les créatures de l'ombre du monde souterrain ont volé les couleurs éblouissantes du gardien de la lumière. \nVoyagez dans le monde souterrain, collectez une gemme de chaque couleur de l'arc-en-ciel. \nQuand les six gemmes différentes seront dans vos poches, je les prendrai et je considérerai que la quête est terminée. \nAide-moi à réunir toutes les couleurs de l'arc-en-ciel.",
			COUNTER = "Différentes pierres précieuses trouvées",
			HOVER = "Tenir une gemme rouge, bleue, violette, verte, jaune et orange",
		},
		["Bright Worshipnight"] = {
			NAME = "Culte lumineux",
			DESCRIPTION = "La nuit sacrée du culte de Glommer approche et ne peut avoir lieu sans les accessoires associés. \nLutte contre les cochons, récupère la fleur de Glommer et 10 lucioles et trouve la boîte en bois sacrée que je te fournirai près de la statue de Glommer la nuit de la pleine lune.",
			COUNTER = "Fois vénéré Glommer",
			HOVER = "Prêcher à Glommer",
		},
		["Mirror of Merms"] = {
			NAME = "Miroir de Merms",
			DESCRIPTION = "La vie dans le marais est sens dessus dessous ! \nLes hommes du marais ont commencé à émettre des gaz lorsqu'ils sont attaqués. \nSi ceux-ci sont inhalés, le monde commence à tourner. \nTuez %s hommes des marais pour empêcher la transmission de cette mutation.",
		},
		["Giving back to Nature"] = {
			NAME = "Redonner à la nature",
			DESCRIPTION = "La nuit noire semble menaçante, notamment à cause de Charlie. \nPour une vie plus insouciante, je demande aux lucioles d'éclairer mon chemin.",
			COUNTER = "Les lucioles libérées",
			HOVER = "Déposer %s lucioles sur le sol",
		},
		["A Crappy Day"] = {
			NAME = "Une journée de merde",
			DESCRIPTION = "J'ai eu une journée de merde aujourd'hui, je veux que quelqu'un se sente aussi mal ! \nS'il vous plaît, aidez-moi à finir cette merde !",
			COUNTER = "Fois se faire chier",
			HOVER = "Se faire toucher %s fois par une crotte lancée",
		},
		["Revenge of the crapped victim"] = {
			NAME = "La vengeance de la victime chiée",
			DESCRIPTION = "Après avoir été incapable d'enlever la merde de mes vêtements après ma dernière visite aux ruines, je veux prendre ma revanche sur ces créatures ! \nQu'elles volent le flegme d'un Ewecus pour leur montrer ce que signifie le vrai dégoût !",
			COUNTER = "Flegme volé",
			HOVER = "Laisser les singes voler 1 flegme",
		},
		["Luminous globules"] = {
			NAME = "Globules lumineux",
			DESCRIPTION = "Je suis un défenseur de la médecine naturelle depuis longtemps. D'après mes recherches, les ampoules électriques sont très prometteuses en termes de guérison. \Faites l'expérience des effets curatifs par vous-même et faites un rapport sur les résultats.",
			COUNTER = "Guérison par ampoules",
			HOVER = "Guérir %s points de vie en mangeant des ampoules",
		},
		["Beary Hunger"] = {
			NAME = "Faim d'ours",
			DESCRIPTION = "Aidez-moi s'il vous plaît, je suis au bord de la famine car les dindons mangent toutes mes baies. \nTuez deux de ces bêtes et je partagerai mes baies avec vous.",
		},
		Wetlands = {
			NAME = "Zones humides",
			DESCRIPTION = "C'est si agréable d'être mouillé, ne voulez-vous pas être mouillé comme ça ? \nPouvez-vous réussir à être plus mouillé que 50%% pendant un total de %s minutes ?",
			COUNTER = "Secondes humides",
			HOVER = "Rester au minimum à 50%% d'humidité pendant %s minutes",
		},
		["Off to sea"] = {
			NAME = "En mer",
			DESCRIPTION = "Ohé, les terriens ! \nSi tu veux naviguer avec nous, tu dois d'abord avoir tous les matériaux pour un bateau dans ton inventaire !",
			COUNTER = "Matériaux",
			HOVER = "Tenir un kit de bateau, une rame, un mât, un volant et une ancre dans votre inventaire",
		},
		["Hidden Treasures"] = {
			NAME = "Trésors cachés",
			DESCRIPTION = "Au fond de la mer, il y aurait des trésors que personne n'a encore vus. \nSi vous repêchez %s de ces trésors, vous serez récompensé !",
			COUNTER = "Trésors",
			HOVER = "Utilisez le treuil à pinces pour soulever %s objets récupérables sous l'eau",
		},
		["Off to donate blood"] = {
			NAME = "En route pour donner du sang",
			DESCRIPTION = "Les réserves de sang sont rares ! Nous, les cochons, irions même chercher du sang humain pour reconstituer nos réserves. \nN'hésitez pas à postuler à tout moment !",
			COUNTER = "Dons de sang",
			HOVER = "Se faire attaquer %s fois par des moustiques",
		},
		["The Lonely Woven Shadow"] = {
			NAME = "L'ombre solitaire tissée",
			DESCRIPTION = "L'Ancien Tisseur de combustible a laissé cette pauvre Ombre tissée se débrouiller toute seule ! \nCertains monstres veulent se venger de l'Ancien Tisseur de combustible et ont décidé de l'attaquer, défendez-le !",
			COUNTER = "Vagues d'attaque",
			HOVER = "Protégez l'Ombre tissée !",
		},
		["The Eye of Cthulhu"] = {
			NAME = "L'œil de Cthulhu",
			DESCRIPTION = "Mon œil m'a quitté une fois de plus ! \nIl refuse de revenir à moi ! \nComme je suis actuellement très occupé, j'aimerais engager un aventurier pour le vaincre afin que mon œil me revienne.",
		},
		["The Biggest Veggy"] = {
			NAME = "La plus grosse %s",
			DESCRIPTION = "Qui a la plus grosse aubergine ? \nJe veux organiser un concours. \nSi vous arrivez à faire pousser une %s dont le poids est supérieur à %s, le record actuel, vous gagnerez un prix spécial !",
			COUNTER = "%s",
			HOVER = "Récolter une %s dont le poids dépasse %s !",
		},
		["A Sailor's Life"] = {
			NAME = "La vie d'un marin",
			DESCRIPTION = "Si tu es un vrai marin, tu restes sur le bateau aussi longtemps que tu peux!\nSi tu nous montres que tu es l'un des nôtres, nous t'accueillerons avec un petit cadeau !",
			COUNTER = "Secondes sur le bateau",
			HOVER = "Restez %s secondes à la fois sur un bateau sans le quitter !",
		},
		["Survival: Famine"] = {
			NAME = "Survivre : la famine %s",
			DESCRIPTION = "Étudiez le chapitre 1, \"Famine\", du manuel officiel \"Techniques de survie\" de notre collection de livres. Affamez-vous jusqu'à la limite de la douleur et vérifiez l'efficacité de ce livre de référence sur votre propre corps ! Ne vous inquiétez pas, une réparation appropriée vous sera fournie par la suite ...\n\n~ L'agence de quête ~.",
			COUNTER = "Dommages causés par la famine",
			HOVER = "Recevoir %s dommages en mourant de faim",
		},
		["Survival: Heart attack"] = {
			NAME = "Survivre : Crise cardiaque %s",
			DESCRIPTION = "Étudiez le chapitre 2 \"Crise cardiaque\" du manuel officiel \"Techniques de survie\" de notre collection de livres. Conduisez-vous jusqu'au bord de la folie et consultez les précieux conseils de notre guide pas à pas ! En guise de récompense, vous recevrez également de la glace aux noix pour compenser !\n\n~ L'agence de quête ~",
			COUNTER = "Dommages reçus",
			HOVER = "Recevoir %s dommages par un terrorbeak",
		},
		["Survival: Frost Shock"] = {
			NAME = "Survivre : Chocs de gel %s",
			DESCRIPTION = "Étudiez le chapitre 3 \"Le choc du gel\" du manuel officiel \"Techniques de survie\" de notre collection de livres. Endurez les vents glacés et les membres frissonnants et vérifiez si vous pouvez rester au chaud dans une rangée avec l'aide du livre ! Si vous réussissez cette tâche, vous recevrez également quelque chose de chaud à manger en guise de remerciement ! \n\n~ L'agence de quête ~",
			COUNTER = "Dégâts causés par le gel",
			HOVER = "Recevoir %s dommages en gelant",
		},
		["Survival: Heat exhaustion"] = {
			NAME = "Survivre : Épuisement par la chaleur %s",
			DESCRIPTION = "Étudiez le chapitre 4, \"Coup de chaleur\", du manuel officiel \"Techniques de survie\" de notre collection de livres. Tenez bon dans la chaleur accablante et la transpiration et vérifiez l'efficacité des mesures de réduction de la transpiration trouvées entre les pages de ce chapitre ! Nous vous assurons également un repas frais par la suite pour vous rafraîchir ! \n\n~ L'agence de quête ~.",
			COUNTER = "Dommages dus à la surchauffe",
			HOVER = "Recevoir %s dommages par surchauffe",
		},
		["Survival: Life-threatening"] = {
			NAME = "Survie : danger de mort %s",
			DESCRIPTION = "Étudiez le chapitre 5 \"Danger de mort\" du manuel officiel \"Techniques de survie\" de notre collection de livres. Essayez de vous rapprocher le plus possible de la mort en saignant pour la bonne cause et voyez si vous pouvez utiliser les astuces proposées dans le livre pour vous sortir de cette situation de danger de mort ! Pour vous remettre sur les rails, le maître boulanger local vous réserve également une surprise en guise de récompense !\n\n ~ L'agence de quête ~",
			COUNTER = "Expérience de mort imminente",
			HOVER = "Avoir moins de %s point de santé",
		},
		["The True Enemy"] = {
			NAME = "Le véritable ennemi",
			DESCRIPTION = "Une terreur sinistre glisse sur ses ailes à travers le pays et son nom est Glommer... Beaucoup ne sont pas conscients du danger que ce compagnon maléfique apporte avec lui et ignorent donc le danger imminent. Cette menace ne peut être arrêtée que si nous prenons des mesures préventives contre vous avec toute la force nécessaire. Sauvez le monde de cette engeance meurtrière et détruisez le véritable ennemi de nous tous !\n\n~ L'agence de quête ~",
		},
		["Treebeard's end"] = {
			NAME = "La fin de Treebeard",
			DESCRIPTION = "Les arbres errent dans les bois et ne causent que des problèmes dans nos efforts d'acquisition de bois de chauffage. Ils gênent nos opérations d'albolz et font fuir tous ceux qui s'approchent de la forêt. Donnez l'exemple en abattant à la hache l'un de ces arbres à barbe. \n\n~ L'agence de quête ~",
			COUNTER = "Garde forestière",
			HOVER = "Tuer 1 Garde forestière avec une hache",
		},
		["Feeding Time"] = {
			NAME = "Heure de l'alimentation",
			DESCRIPTION = "Gardez vos coéquipiers en vie à tout prix ! Sauvez un de vos collègues en lui enfonçant de la nourriture dans la bouche dans la plus grande faim. Cela favorise la camaraderie et envoie un signal fort sur leur esprit d'équipe !\n\n~ L'agence de quête ~",
			COUNTER = "Joueur nourri",
			HOVER = "Nourrir 1 joueur lorsqu'il perd de la santé à cause de la faim",
		},
		["Catch the stick"] = {
			NAME = "Attrape le bâton",
			DESCRIPTION = "Nos spécialistes du comportement ont émis l'hypothèse que les chiens locaux réagissent également au \"lancer de bâton\" comme des chiens ordinaires. Testez cette thèse passionnante en essayant de stimuler un des chiens de ce monde avec un bâton ! \n\n~ L'agence de quête ~",
			COUNTER = "Bâtons lancés",
			HOVER = "Lancer un boomerang %s fois sur un chien",
		},
		["Front Pigs"] = {
			NAME = "Cochons du front",
			DESCRIPTION = "La guerre est dans l'air. Nous avons besoin de porcs de première ligne capables de se défendre pour repousser les agresseurs de toutes sortes et protéger nos intérêts. Mais malheureusement, nos offres d'emploi ne semblent atteindre aucun des combattants de la liberté locaux. Contactez-les personnellement et convainquez la population locale de les suivre au combat ! Nous vous promouvrons au poste de général des cochons peu de temps après !\n\n~ L'agence de quête ~",
			COUNTER = "Suiveurs de cochons",
			HOVER = "Recrutez %s cochons pour qu'ils combattent à vos côtés.",
		},
		["Detective Work"] = {
			NAME = "Travail de détective",
			DESCRIPTION = "Je cherche quelqu'un qui a de l'expérience dans la lecture de traces. \nIl y a des créatures qui errent dans le coin, mais je n'arrive jamais à les trouver. \nSi vous êtes capable de retrouver 3 d'entre elles, je vous récompenserai !",
			COUNTER = "Piles à terre suivies ",
			HOVER = "Pistez 3 tas de terre jusqu'à ce que vous trouviez la créature à laquelle ils appartiennent.",
		},
		["Twins Of Destruction"] = {
			NAME = "Jumeaux de la destruction",
			DESCRIPTION = "Il semble qu'une fissure dimensionnelle ait amené dans ce monde des créatures qui ne devraient pas y être!\nVeuillez les vaincre car elles bouleversent tout l'écosystème !",
			COUNTER = "Les jumeaux de la terreur",
			HOVER = "Vaincre les deux jumeaux de la terreur",
		},
		["The Biggest Frog"] = {
			NAME = "La plus grosse grenouille",
			DESCRIPTION = "J'ai entendu dire qu'il y a une grenouille dans les grottes qui est si grosse qu'elle pourrait avaler une personne en entier ! \nJ'ai une phobie assez forte des grenouilles malheureusement. \nC'est pour ça que ça me rend un peu nerveux d'explorer les grottes, s'il vous plaît trouvez-la et tuez-la.",
		},
		["Ho Ho Ho"] = {
			NAME = "Ho Ho Ho",
			DESCRIPTION = "Il semble qu'il y ait un imposteur parmi nous, les Pères Noël... \nDans ce monde, le Père Noël ne distribue pas les cadeaux qu'il reçoit de l'Association des Pères Noël et les amasse pour lui. \nS'il vous plaît, vainquez-le pour que ce monde puisse aussi connaître les joies de Noël !",
		},
		["The Impregnable Fortress"] = {
			NAME = "La forteresse imprenable",
			DESCRIPTION = "Il y a une forteresse dans la mer qui semble imprenable. \nElle est gardée (ou est-ce la forteresse elle-même ?) par un monstre si grand que vous ne le croiriez pas ! \nDes rumeurs disent que de nombreux trésors y sont cachés. \nSi tu vaincs ce monstre, nous te récompenserons en conséquence !",
		},
		["The Master Chef"] = {
			NAME = "Le maître cuisinier",
			DESCRIPTION = "J'aimerais vraiment essayer un dîner de homard, mais les ingrédients sont si difficiles à trouver que je ne peux pas le faire ! \nSi tu pouvais cuisiner ce plat et me le donner, je te récompenserais !",
			COUNTER = "Dîners de homard cuisinés",
			HOVER = "Cuisiner %s dîner de homard",
		},
		["Destroyer of Ancient Works"] = {
			NAME = "Destructeur d'œuvres anciennes",
			DESCRIPTION = "La suite de Glommer ne veut plus aucune mention des anciennes civilisations dans ce monde, cela rend plus difficile le recrutement d'adeptes. \nDétruisez les vestiges des anciennes civilisations avec un marteau et ne laissez aucune trace !",
			COUNTER = "Stations anciennes détruites",
			HOVER = "Détruire %s stations de pseudo-science anciennes pleines ou brisées avec un marteau.",
		},
		["The Goodest Boy"] = {
			NAME = "Le meilleur des garçons",
			DESCRIPTION = "Qui est le plus gentil des garçons ? C'est toi, Houndius Shootius ! \nTu t'occupes toujours des méchants chiens qui m'attaquent ! \nMais malheureusement, Houndius Shootius se sent seul car il n'a pas d'amis. \nS'il te plaît, construis-en %s de plus pour qu'il ait des amis avec qui jouer !",
			COUNTER = "Houndius Shootius construit",
			HOVER = "Déployer %s Houndius Shootius",
		},
		["The RPG Expert"] = {
			NAME = "L'expert en RPG",
			DESCRIPTION = "J'ai besoin de l'aide d'un joueur de RPG professionnel ! \nJe n'arrive pas à monter de niveau rapidement et efficacement. \nSi vous pouvez me montrer que vous savez ce que vous faites et comment vous le faites, je vous récompenserai ! \nVous devez juste gagner %s niveaux dans le journal des quêtes.",
			COUNTER = "Niveaux gagnés",
			HOVER = "Gagner %s niveaux dans le journal des quêtes",
		},
		["The Questing Adventurer"] = {
			NAME = "L'aventurier en quête",
			DESCRIPTION = "Les quêtes sont de plus en plus nombreuses et il n'y a pas assez de monde pour les faire !\nC'est pourquoi nous proposons maintenant une incitation à terminer les quêtes.\nSeules les quêtes qui ont été terminées lorsque cette quête était active seront prises en compte !\nRéussissez %s quêtes et vous obtiendrez une récompense spéciale !",
			COUNTER = "Quêtes achevées",
			HOVER = "Terminer %s quêtes",
		},
		["Night Angler"] = {
			NAME = "Pêcheur de nuit",
			DESCRIPTION = "Nous soupçonnons que les bancs de poissons locaux ont changé de comportement ces derniers temps. Vérifiez si les poissons dans ces eaux mordent toujours la nuit ! \n\n ~ L'agence de quête ~",
			COUNTER = "Poissons capturés",
			HOVER = "Attraper %s poissons en une nuit",
		},
		["Comrade Pig"] = {
			NAME = "Camarade Cochon",
			DESCRIPTION = "Jusqu'à présent, on ne sait pas grand-chose sur la réaction des porcs à la surconsommation de viande de monstre. Par conséquent, donnez une énorme quantité de viande de monstre à 3 spécimens différents et documentez leur réaction. Nous attendons vos résultats avant demain matin !\n\n ~ L'agence de quête ~",
			COUNTER = "Des porcs transformés",
			HOVER = "Transformez 3 cochons en un Werepig",
		},
		Kingfisher = {
			NAME = "Martin-pêcheur",
			DESCRIPTION = "La plupart des oiseaux que nous connaissons migrent vers le sud à l'entrée de l'hiver et ne reviennent qu'au printemps, lorsque le temps se réchauffe. Une exception : les grands oiseaux, qui doivent défier en permanence les conditions climatiques hivernales. Pour vérifier ce fait, nous vous demandons de congeler et de décongeler %s grands oiseaux différents. Indiquez comment les oiseaux supportent le froid !\n\n ~ L'agence de quête ~",
			COUNTER = "Tallbirds gelés",
			HOVER = "Congeler %s Tallbirds",
		},
		["The Mad Hatter"] = {
			NAME = "Le Chapelier fou",
			DESCRIPTION = "Malheureusement, notre meilleur chapelier a disparu sans laisser de trace. Cependant, nous avons un besoin urgent de nouveaux chapeaux en ce moment. C'est pourquoi nous vous demandons de concevoir une nouvelle collection de chapeaux et de nous les envoyer. Nous vous enverrons une liste des chapeaux dont nous avons besoin. En guise de compensation, vous recevrez le vieux chapeau de pluie du chapelier.\n\n ~ L'agence de quête ~",
			COUNTER = "Chapeaux fabriqués",
			HOVER = "Fabriquez les chapeaux suivants : Chapeau de bœuf, chapeau en plumes, \nchapeau de pluie et bonnet de chat",
			MISSING = "Manquant :",
		},
		["Wrong Offering"] = {
			NAME = "Offre erronée",
			DESCRIPTION = "Il est parfois juste de sacrifier pour une bonne cause. Testez leur volonté de se sacrifier avec une offrande douloureuse. Faites en sorte que votre fidèle compagnon Chester connaisse une fin peu glorieuse. Nous vous attribuerons un meilleur Chester par la suite.\n\n ~ L'agence de quête ~",
		},
		["Shadow World Manipulation"] = {
			NAME = "Manipulation du monde de l'ombre",
			DESCRIPTION = "Élargissez votre base et aidez-nous à réaliser les dernières découvertes en matière de recherche sur les ombres. Construisez plus de manipulateurs d'ombres pour explorer le monde des ombres et mener des tests de terrain révolutionnaires ! Nous comptons sur vous !\n\n ~ L'agenze de quête ~",
			COUNTER = "Manipulateurs d'ombres construits",
			HOVER = "Construire 3 Manipulateurs d'Ombrage",
		},
		["Friends in the Shadow Realm"] = {
			NAME = "Friends in the Shadow Realm",
			DESCRIPTION = "Vouz vous efforcez d'aller plus loin que jamais. Vous redoublez vos efforts dans la recherche des ombres. Vouz n'avez pas encore compris ce que cela signifie de ne faire qu'un avec les ombrez ! Faites en zorte que tous les joueurs de votre environnement participent aussi à la recherche des ombres ! Ouvrez voz yeux tous en même tempz pour jeter un coup d'oeil dans les profonds abyzzes ! Nous n'attendons rien de moins que votre meilleur !\n\n ~ L'agenze de quête ~",
			COUNTER = "Secondez",
			HOVER = "Tous les joueurs doivent avoir une valeur de zanté mentale inférieure à 10 pendant 66 secondes.",
			HOVER1 = "Rester à une valeur de zanté mentale de moins de 10 pendant 366 zecondes.",
		},
		["Your True Friends"] = {
			NAME = "Vos vrais amis",
			DESCRIPTION = "Vous avez fait votre travail trèz bien, trèz bien... Nouz vouz paieronz trèz bien. Oui, nouz le feronz. Pendant que vouz faiziez de si bonnez recherchez pour nouz dans l'ombre, nouz avonz pu retrouver un vieil ami à vouz pour une réunion. Il a hâte de vouz revoir dèz que possible... Il meurt d'envie... Vous feriez mieux d'amener tout votre groupe avec vous... Nouz vouz récompenzerons touz pour lez fruitz de votre travail...\n\n ~ L'agenzZze de quête ~",
			COUNTER = "Amiz",
			HOVER = "Allez à la ztatue de Glommer pour rencontrer voz amiz....",
		},
		Spiderman = {
			NAME = "Spiderman",
			DESCRIPTION = "J'ai besoin de quelqu'un pour décimer la population de porcs, mais sans qu'ils sachent que c'est moi. \nSi vous savez comment persuader des araignées de tuer les cochons pour moi, vous êtes la personne idéale pour cette mission ! \nVotre dévouement ne sera pas oublié !",
			COUNTER = "Cochons",
			HOVER = "Tuez %s cochons avec des araignées qui vous suivent.",
		},
		["A Bunnys Job"] = {
			NAME = "Le travail d'un lapin",
			DESCRIPTION = "Les Bunnymans tuent les chauves-souris, c'est ainsi que le monde a toujours été. \nC'est leur seul but... \nMais récemment, les Bunnymans ne savent souvent pas qu'ils doivent les tuer. \nC'est pourquoi j'ai besoin de quelqu'un qui puisse leur montrer comment tuer les chauves-souris !",
			COUNTER = "Chauves-souris",
			HOVER = "Tuez %s chauves-souris avec des Bunnymans qui vous suivent",
		},
		["Your Own Fault"] = {
			NAME = "Votre propre faute",
			DESCRIPTION = "Je suis vraiment désolé MacTusks, mais c'est de votre faute... \nVous nous avez donné vos sarbacanes chaque fois que nous vous tuons et maintenant je veux qu'ils ressentent la douleur que nous ressentons quand nous sommes touchés par ces sarbacanes. \nTuez %s d'entre eux avec la sarbacane de votre choix !",
			COUNTER = "MacTusk",
			HOVER = "Tuez %s MacTusks avec une fléchette de votre choix",
		},
		["Death By Self"] = {
			NAME = "La mort par soi-même",
			DESCRIPTION = "Les cochons semblent être des créatures stupides mais j'aimerais étudier la question : Peuvent-ils comprendre des situations complexes ? \nPour cela, je voudrais que vous tuiez %s cochons avec un Ham Bat. \nS'ils comprennent pourquoi c'est une mauvaise chose à faire, mon expérience sera un succès !",
			COUNTER = "Cochons",
			HOVER = "Tuer %s porcs avec un Ham Bat",
		},
		["The Inner Monster"] = {
			NAME = "Le monstre intérieur",
			DESCRIPTION = "Dans chaque cochon il y a un monstre intérieur qui fait rage... \nJe veux que tu le libères, car les cochons ne devraient pas avoir à vivre dans la peur pour laisser sortir leurs démons intérieurs. \nLibère %s cochons de ces normes sociales en les transformant en cochons-garous !",
			COUNTER = "Cochons à Werepig",
			HOVER = "Transformez %s cochons en Werepigs en leur donnant quelque chose à manger.",
		},
		["The Boxer"] = {
			NAME = "Le Boxeur",
			DESCRIPTION = "Si tu veux être le meilleur, tu dois apprendre du meilleur !\n Et je suis le meilleur ! \nJe vous offre une séance d'entraînement personnelle avec moi, le champion de boxe invaincu et constant ! \nNous allons commencer par les bases, infliger %s points de dégâts avec seulement vos poings !",
			COUNTER = "Dégâts",
			HOVER = "Infligez %s points de dégâts avec vos poings",
		},
		["The Dish for the Pig"] = {
			NAME = "Le plat pour le cochon",
			DESCRIPTION = "Même les cochons comme moi ressentent le besoin de se faire plaisir. \nC'est pourquoi je récompenserai la personne qui nourrira un autre cochon avec un dîner Wobster. \nDe cette façon, ils entreront également en contact avec le monde culinaire.",
			COUNTER = "Dîner de Wobster",
			HOVER = "Donner un dîner de Wobster à un cochon",
		},
		["A Useful Companion"] = {
			NAME = "Un compagnon utile",
			DESCRIPTION = "Les bœufs peuvent sembler être des créatures qui ne s'intéressent qu'à leurs congénères, mais je peux vous assurer que ce n'est pas le cas ! \nJe veux montrer au monde que ce sont des compagnons adorables qui rendent plus qu'ils ne prennent. \nMontez-en un pendant %s secondes pour voir ce que je veux dire",
			COUNTER = "Secondes montées",
			HOVER = "Chevaucher un bœuf pendant %s secondes",
		},
		["Marble Trees?!"] = {
			NAME = "Arbre de Marbre?!",
			DESCRIPTION = "Apparemment, il est possible de planter des haricots de marbre pour faire pousser du marbre. \nC'est juste quelque chose qui n'a pas beaucoup de sens pour moi... Si c'est vrai, il doit y avoir quelque chose qui m'échappe... Comment obtiennent-ils l'énergie pour grandir ? \nS'il vous plaît, plantez %s haricots de marbre, je veux les voir pousser pour faire avancer mes recherches !",
			COUNTER = "Arbre de Marbre planté",
			HOVER = "Planter %s arbres de Marbre",
		},
		["The Stonemason"] = {
			NAME = "Le tailleur de pierre",
			DESCRIPTION = "Le marbre est un matériau utile, même si l'on dit qu'il a des liens avec les ombres de ce monde. \nC'est pourquoi j'ai besoin de quelqu'un qui sache fabriquer des équipements en marbre pour m'apprendre à le faire ! \nMontre-moi les ficelles du métier en fabriquant %s Armures de Marbre",
			COUNTER = "Armures de Marbre",
			HOVER = "Fabriquer %s armures de marbre",
		},
		["The Shadow Plague"] = {
			NAME = "La peste des ombres",
			DESCRIPTION = "Ces derniers temps, les créatures de l'ombre sont une véritable menace pour notre population. Nous avons besoin d'aide pour contrôler leur nombre. \nTout le monde est le bienvenu pour aider à tuer autant de créatures de l'ombre qu'il le souhaite, une récompense sera donnée pour les %s premières !",
			COMPTEUR = "Créatures de l'ombre",
			HOVER = "Vaincre %s créatures de l'ombre",
			COUNTER = "Créatures de l'ombre",
		},
		["The Pieces of Downfall"] = {
			NAME = "Les morceaux de la chute",
			DESCRIPTION = "Il semble que notre récente purge ait réveillé des forces qui auraient mieux fait de rester endormies... \nLes pièces de l'ombre sont presque réveillées ! S'ils atteignent ce stade, le monde sera condamné ! \nSi vous pouvez les vaincre avant qu'ils ne se réveillent complètement, vous pourrez tous nous sauver ! \nPour cela, tu dois construire les statues de marbre correspondantes et les détruire lors d'une pleine lune.",
			COUNTER = "Pièces de l'ombre",
			HOVER = "Construisez une tour, un chevalier et un évêque en marbre, \ndétruisez-les à la pleine lune et tuez les pièces de l'ombre",
		},
		["The Ancient Craft"] = {
			NAME = "L'artisanat ancien",
			DESCRIPTION = "J'ai vraiment de la thulecite mais je ne suis pas assez fort pour survivre dans les ruines... \nS'il vous plaît, si quelqu'un connaît encore l'ancienne méthode pour fabriquer de la thulecite à partir de fragments de thulecite, faîte-le !",
			COUNTER = "Fabrication de thulecite",
			HOVER = "Fabrication de %s thulecite",
		},
		["The Shadow Slayer"] = {
			NAME = "Le tueur d'ombres",
			DESCRIPTION = "Ces ombres de cauchemar ont pris le contrôle des ruines ! Il y en a tellement pendant le cycle des cauchemars. \nJ'ai besoin de quelqu'un pour en tuer pour que je puisse voyager en toute sécurité en bas !",
			COUNTER = "Ombres tuées",
			HOVER = "Tuez %s créatures de l'ombre pendant le cycle du cauchemar dans les ruines",
		},
		["Suicidal Thoughts"] = {
			NAME = "Pensées suicidaires",
			DESCRIPTION = "J'ai eu une fois un ami qui m'a dit qu'il avait pu survivre à l'explosion d'une pile de 25 poudres à canon ! \nAucune idée de comment il a fait et il est mort depuis par une autre explosion malheureuse... \nSi vous êtes capable de survivre à une telle explosion, montrez-moi comment vous avez fait !",
			COUNTER = "Survivre à l'explosion",
			HOVER = "Survivre à l'explosion d'une pile d'au moins 25 poudres à canon",
		},
		["The Untalented Chef"] = {
			NAME = "Le chef sans talent",
			DESCRIPTION = "Ma vie est finie ! J'ai été viré de l'école culinaire ! \nC'était mon plus grand rêve ! Juste parce que je n'étais capable que de cuisiner de la Matière grasse... \nJ'ai besoin de quelque chose pour me remonter le moral, pour me montrer que je ne suis pas le seul à cuisiner de la Matière grasse !",
			COUNTER = "Matière grasse cuites",
			HOVER = "Cuire %s Wet Goop",
		},
		["The Flower Lover"] = {
			NAME = "L'amoureux des fleurs",
			DESCRIPTION = "J'aime les fleurs... C'est probablement pour cela que l'on m'appelle l'Amoureux des Fleurs ! \nJe souhaite remplir ce monde de fleurs ! \nAide-moi à réaliser mon rêve en plantant %s fleurs !",
			COUNTER = "Fleurs plantées",
			HOVER = "Planter %s fleurs",
		},
		["The Fish Fisher"] = {
			NAME = "The %s Fisher",
			DESCRIPTION = "J'ai vraiment besoin d'un %s pour un de mes projets spéciaux ! \nMais je n'arrive pas à les attraper ! \nSi quelqu'un pouvait m'en apporter 5, je lui en serais très reconnaissant !",
			COUNTER = "%s pêché",
			HOVER = "Pêche 2 %s",
		},
		["The Tormented Dust Moth"] = {
			NAME = "Le papillon de poussière tourmenté",
			DESCRIPTION = "Une teigne que je connais personnellement est harcelée depuis un certain temps par de fortes créatures ! \nElles veulent lui voler la thulecite qu'il s'efforce de faire pousser depuis longtemps. \nSi tu les aides à les défendre, ils te récompenseront en te donnant un morceau de cette thulecite et en te jetant un sort de protection !",
			COUNTER = "Protection de la Teigne des Poussières",
			HOVER = "Protégez la Teigne de la Poussière des créatures qui frayent pendant 5 vagues",
		},
		["The Sleeping Beauty"] = {
			NAME = "La Belle au Bois Dormant",
			DESCRIPTION = "L'heure du sommeil de la beauté ! Avec tout le travail à accomplir, il est facile de se surmener. Prenez soin de vous et donnez à votre corps et à vous-même une pause !",
			COUNTER = "Dormir pendant des secondes.",
			HOVER = "Dormir %s secondes dans une tente ou similaire.",
		},
		["The Ocean Chose Me!"] = {
			NAME = "L'océan m'a choisi !",
			DESCRIPTION = "Là où l'océan se perd flotte un son, il m'appelle ! Est-il donc loin ? Suis-je prêt ? L'océan t'a choisi pour récolter %s d'algues. Alors rejoignez-le et dites : J'aimerais bien !",
			COMPTEUR = "Récolte des algues marines",
			HOVER = "Récoltez les anatifes de %s algues à mains nues !",
			COUNTER = "Herbes marines récoltées",
		},
		["The Seven Dwarfs"] = {
			NAME = "Les sept nains",
			DESCRIPTION = "Blanche-Neige a besoin de ton aide ! Tes amis nains ont creusé trop profondément dans leur travail à la mine et sont tombés dans la constante ! Ce faisant, ils se sont transformés en figures rigides. Aide-la à les retrouver et à les livrer au roi des cochons pour les renvoyer dans leur monde !",
			COMPTEUR = "Nains",
			HOVER = "Livrez les sept nains au Roi des cochons!",
			COUNTER = "Nains",
		},
		["The Cold Never Bothered Me Anyway!"] = {
			NAME = "Le froid fait maintenant partie de moi!",
			DESCRIPTION = "Je me laisse aller ! Je me laisse aller maintenant ! Plus de faim pour me tourmenter, plus de créatures pour me rendre fou, et le froid fait maintenant partie de moi aussi ! Prouve que, comme Elsa, tu es prête pour la liberté et que le froid, la faim et la folie ne te dérangent pas !",
			COMPTEUR = "Secondes insouciantes",
			HOVER = "Reste affamé, froid et à moins de 10 Sanity pendant %s secondes",
			COUNTER = "Quelques secondes d'insouciance",
		},
		["Kiss The Frog!"] = {
			NAME = "Embrassez la grenouille !",
			DESCRIPTION = "Parfois, tu dois embrasser beaucoup de grenouilles avant de trouver ton prince. Affronte suffisamment d'entre elles et tu deviendras un vrai prince grenouille ! Mais attention : une grenouille vient rarement seule !",
			COUNTER = "Grenouilles",
			HOVER = "Tue %s grenouilles pour trouver ton prince !",
		},
		["The Dangerous Widow"] = {
			NAME = "La veuve dangereuse",
			DESCRIPTION = "L'une des forêts de ce pays est sous le contrôle d'une araignée géante depuis longtemps. \nNous voulons cultiver cette terre et pour cela, nous avons besoin que cette araignée disparaisse ! \nTuez-la et nous vous récompenserons !",
		},
		["The Mad Adventurer"] = {
			NAME = "L'aventurier fou",
			DESCRIPTION = "J'ai entendu dire qu'il existe une créature de l'ombre si effrayante et monstrueuse que personne n'a jamais survécu à sa rencontre pour en parler. \nSi tu es capable d'en vaincre une, je te récompenserai !",
		},
		["The Scientist"] = {
			NAME = "Le scientifique",
			DESCRIPTION = "J'ai besoin de quelqu'un qui aime la science autant que moi ! \Construis 3 moteurs d'alchimie pour montrer au monde à quel point la science peut être géniale !",
			COUNTER = "Moteurs Alchimiques construits",
			HOVER = "Construire 3 moteurs d'alchimie",
		},
		["The Arsonist"] = {
			NAME = "L'incendiaire",
			DESCRIPTION = "La plupart de mes amis ne veulent rien avoir à faire avec moi, juste parce que parfois je veux mettre le feu à certaines choses. \Ils ne comprennent pas à quel point un feu est beau... \NMontre-moi que nous pouvons être amis en mettant le feu à 10 choses !",
			COUNTER = "Feux allumés",
			HOVER = "Mettre le feu à 10 objets avec un briquet",
		},
		["The Gravedigger"] = {
			NAME = "Le fossoyeur",
			DESCRIPTION = "Dans le silence sinistre du cimetière, vous plongerez dans l'inconnu en creusant %s tombes. Au fur et à mesure que la terre cède à votre pelle, vous découvrirez peut-être des reliques oubliées, des souvenirs perdus ou peut-être même d'anciennes malédictions. Chaque tombe a sa propre histoire, et votre curiosité vous guidera pour élucider leur passé énigmatique.",
			COUNTER = "Graves",
			HOVER = "Déterrer %s tombes",
		},
		["I've got 99 problems but starving ain't one!"] = {
			NAME = "J'ai 99 problèmes, mais mourir de faim n'en fait pas partie !",
			DESCRIPTION = "Bien que la probabilité de mourir de faim dans ce monde soit assez élevée, j'ai entendu dire que certains de ses habitants sont très riches en ce qui concerne la nourriture. Montrez-moi qu'il existe de telles personnes en mangeant des %s de calories sans mourir de faim une seule fois !",
			COUNTER = "Calories",
			HOVER = "Manger %s calories de nourriture",
			FORFEIT = "J'ai 99 problèmes, mais mourir de faim en est un ! Je n'ai pas pu terminer la quête !",
		},
		["The Untouchable"] = {
			NAME = "L'intouchable",
			DESCRIPTION = "Pouvez-vous être l'Intouchable ? L'intouchable est une entité si forte qu'elle ne peut être touchée par quoi que ce soit ! Montre-moi si tu es digne de ce titre en ne subissant aucun dégât pendant %s secondes !",
			COUNTER = "Secondes",
			HOVER = "Ne subit aucun dommage pendant %s secondes",
		},
		["The Hunted Glommer"] = {
			NAME = "Le Glommer traqué",
			DESCRIPTION = "Un pauvre Glommer est chassé par des prédateurs impitoyables ! Aidez-le à s'échapper, au moins pour cette fois !",
			COUNTER = "Vagues d'attaque",
			HOVER = "Protégez le Glommer ! Le Glommer apparaît au bout de 2 à 3 minutes !",
		},
		["The Stray Hutch"] = {
			NAME = "La huche vagabonde",
			DESCRIPTION = "Mon clapier s'est enfui ! Si vous le retrouvez, merci de le mettre en garde contre les dangers qu'il encourt. Beaucoup de créatures semblent vouloir lui faire du mal dès qu'elles le voient !",
			COUNTER = "Vagues d'attaque",
			HOVER = "Protégez la huche ! La huche apparaît au bout de 2 à 3 minutes !",
		},
		["The Healer"] = {
			NAME = "Le guérisseur",
			DESCRIPTION = "Le membre le plus important d'un groupe est le soigneur. Montrez-moi que vous êtes capable de prodiguer les soins nécessaires pour que cela vaille la peine d'être protégé en soignant les %s de santé !",
			COUNTER = "Santé guérie",
			HOVER = "Soigne %s de votre santé",
		},
		["The Attacker"] = {
			NAME = "L'attaquant",
			COUNTER = "Dommages infligés",
			HOVER = "Inflige %s de dégâts dans un délai de 30 secondes",
			DESCRIPTION = "Le membre le plus important d'un groupe est l'attaquant. Montrez-moi que vous êtes capable de fournir la puissance d'attaque nécessaire pour valoir la peine d'être défendu en infligeant des %s en 30 secondes !",
		},
		["The Defender"] = {
			NAME = "Le défenseur",
			DESCRIPTION = "Le membre le plus important d'un groupe est le défenseur. Montrez-moi que vous êtes capable de fournir la puissance défensive nécessaire pour que cela vaille la peine d'être soigné !",
			COUNTER = "Arrêt des dégâts",
			HOVER = "Empêche %s des dégâts de vous atteindre avec l'armure",
		},
		["Axe-swinging Competition"] = {
			NAME = "Compétition de la hache d'armes",
			DESCRIPTION = "Nous organisons un concours de maniement de la hache. Si vous pensez en être capable, acceptez cette quête ! Vous devrez abattre %s arbres en 3 minutes ! La compétition commence dès que vous avez abattu le premier arbre !",
			COUNTER = "Arbres coupés",
			HOVER = "Couper %s arbres en 3 minutes",
		},
		["Pickaxe-swinging Competition"] = {
			NAME = "Concours de pioche",
			DESCRIPTION = "Nous organisons un concours de maniement de la pioche. Si vous pensez en être capable, acceptez cette quête ! Vous devrez extraire %s roches en 3 minutes ! La compétition commence dès que vous avez extrait le premier rocher !",
			COUNTER = "Roches extraites",
			HOVER = "Mine %s rocks in 3 minutes",
		},
		["Shovel-digging Competition"] = {
			NAME = "Concours de creusage à la pelle",
			DESCRIPTION = "Nous organisons un concours de pelletage. Si vous pensez en être capable, acceptez cette mission ! Vous devrez déterrer %s choses dans un délai de 3 minutes ! La compétition commence dès que vous avez déterré la première chose !",
			COUNTER = "Choses déterrées",
			HOVER = "Déterrer %s choses en 3 minutes",
		},
		["The Fatal Rose"] = {
			NAME = "La rose fatale",
			DESCRIPTION = "Quand j'étais jeune, j'ai touché une rose et j'ai failli en mourir ! Mais personne n'a jamais cru que les roses étaient des créatures maléfiques qui pouvaient même vous tuer ! Aide-moi à leur montrer que les roses peuvent te tuer, si elles le souhaitent...",
			COUNTER = "La mort",
			HOVER = "Mourir d'une rose",
		},
		["The Bird Predator"] = {
			NAME = "Le prédateur d'oiseaux",
			DESCRIPTION = "Les oiseaux ne sont que des drones que Charlie a envoyés pour nous observer ! Je veux qu'ils disparaissent et pour cela, j'ai besoin d'un prédateur d'oiseaux ! Montre-moi ce que tu vaux en tuant %s d'oiseaux rouges dans les 8 prochaines minutes !",
			COUNTER = "Redbirds",
			HOVER = "Tuer %s redbirds dans les 8 prochaines minutes",
		},
		["A Werepigs Worst Nightmare"] = {
			NAME = "Le pire cauchemar de Werepigs",
			DESCRIPTION = "Il semble qu'il y ait un cochon-garou dans les grottes, si gros que personne n'ose l'approcher. Mais nous ne devrions pas avoir peur de simples cochons-garous ! C'est pourquoi je veux que quelqu'un montre à ce soi-disant \"cochon-garou du cauchemar\" que les humains sont leur pire cauchemar !",
		},
		["The Nightmare Trio"] = {
			NAME = "Le trio des cauchemars",
			DESCRIPTION = "Nous voulons extraire de la dreadstone dans les grottes, mais malheureusement, les Ink Blights n'ont pas l'air d'apprécier ! Aidez-nous à les vaincre !",
			COUNTER = "Les lumières de l'encre",
			HOVER = "Tuer les 3 Ink Blights",
		},
		["The Acid Bath"] = {
			NAME = "Le bain acide",
			DESCRIPTION = "Je souhaite étudier la quantité d'acide qu'une personne peut supporter. Je cherche donc des volontaires pour cette recherche. Nous commencerons par %s secondes dans la pluie acide dans les grottes, mais sans protection, sinon la recherche sera faussée !",
			COUNTER = "Secondes",
			HOVER = "Tenir %s secondes dans la pluie acide sans protection",
		},
		["A Great Ryft"] = {
			NAME = "Un grand Ryft",
			DESCRIPTION = "Les ryftals nouvellement apparus semblent assez intéressants, je veux savoir quel genre de butin ils donnent ! J'ai besoin que quelqu'un en mine %s pour que je puisse voir leur contenu.",
			COUNTER = "Ryftals exploités",
			HOVER = "Mine %s ryftals",
		},
		["A Grazers Nightmare"] = {
			NAME = "Le cauchemar des brouteurs",
			DESCRIPTION = "Les brouteurs semblent protéger les ryftals, mais j'ai vraiment besoin de les étudier sans qu'ils me dérangent ! Que quelqu'un m'aide en leur infligeant %s de dégâts !",
			COUNTER = "Dommages infligés",
			HOVER = "Inflige %s de dégâts aux brouteurs",
		},
		["Closest To Oneself"] = {
			NAME = "Au plus près de soi",
			DESCRIPTION = "Tout le monde a des talents particuliers ! Je veux que tu les cultives ! Fabrique %s d'objets que tu es le seul à pouvoir fabriquer et je te donnerai une petite récompense !",
			COUNTER = "Artisanat spécifique à un personnage",
			HOVER = "Fabriquer %s objets spécifiques au personnage",
		},
		["Kill The Lord"] = {
			NAME = "Tuer le Seigneur",
			DESCRIPTION = "Bien que Lord Fruitfly veille sur notre village depuis un certain temps, il a commencé à attaquer nos fermiers et notre bétail récemment. Nous n'avons donc qu'une seule option, la mort au Seigneur ! Malheureusement, nous ne sommes pas assez forts, aidez-nous !",
		},
		["Kill The Innocent"] = {
			NAME = "Tuer les innocents",
			DESCRIPTION = "Les mousses sont si innocents lorsque leur mère est avec eux, mais ils deviennent des monstres une fois qu'elle est partie. Malheureusement, leur viande n'a plus le même goût lorsqu'ils se mettent en colère... J'ai besoin de quelqu'un pour tuer %s d'innocents mosslings afin de profiter du plaisir d'une viande délicieuse !",
			COUNTER = "Mousses innocentes",
			HOVER = "Tuer %s mosslings qui ne sont pas enragés",
		},
		["Defeating Rocky"] = {
			NAME = "Vaincre Rocky",
			DESCRIPTION = "Mon ancien meilleur ami Rocky, une langouste, m'a terriblement trahi. Je veux me venger en tuant l'un de ses frères. Ainsi, il pourra peut-être ressentir un peu de la douleur qu'il m'a causée.",
		},
		["I'm The Pirate Now!"] = {
			NAME = "C'est moi le pirate maintenant !",
			DESCRIPTION = "Yahaha ! Les pirates se promènent de plus en plus souvent sur les mers ces derniers temps. Montrons-leur que les rôles peuvent rapidement changer en notre faveur !",
		},
		["Cannon Fodder"] = {
			NAME = "La chair à canon",
			DESCRIPTION = "Es-tu de la chair à canon ou veux-tu prendre les choses en main ? Montrez-moi que vous n'êtes pas de la chair à canon en déployant %s canons !",
			COUNTER = "Canons déployés",
			HOVER = "Déployer %s canons",
		},
		["Let's Get The Party Started!"] = {
			NAME = "Que la fête commence !",
			DESCRIPTION = "Cela fait un certain temps que je n'ai pas organisé de véritable fête, en fait depuis que je suis arrivée à Constant. Mais ça change maintenant ! J'ai besoin de gens qui veulent faire la fête avec moi, mais vous devez apporter vos propres boissons, au moins %s. Il peut s'agir d'un jus de banane, d'un Vegetable Stinger ou d'un Daiquiri à la banane congelé.",
			COUNTER = "Cocktails consommés",
			HOVER = "Mangez %s de jus de banane, de Vegetable Stinger ou de Daiquiri à la banane congelé.",
		},
		["Return To Monke"] = {
			NAME = "Retour à Monke",
			DESCRIPTION = "Le monde moderne n'a plus de place pour nous, les humains. C'est pourquoi je propose que nous rejetions l'humanité et que nous retournions à l'état de singe ! Vous voulez vous joindre à nous ?",
			COUNTER = "Retourné à Monke",
			HOVER = "Transformez-vous en Wonkey, revenez à monke !",
		},
		["The Punching Bag"] = {
			NAME = "Le sac de frappe",
			DESCRIPTION = "Je me considère comme le plus fort de ce monde. Je suis tellement fort que j'ai pu atteindre une valeur de %s en utilisant les sacs de frappe ! Je vous mets au défi de me montrer une valeur plus élevée !",
			COUNTER = "Dommages maximaux au sac de frappe",
			HOVER = "Faire plus de %s de dégâts à un sac de frappe en un seul coup",
		},
		["The Shadowcrafter"] = {
			NAME = "L'artisan de l'ombre",
			DESCRIPTION = "Les métiers de l'ombre sont difficiles à apprendre et encore plus difficiles à maîtriser... \nSi vous êtes en mesure de me prouver que vous avez fabriqué %s objets de l'ombre, je vous récompenserai en vous offrant des pouvoirs obscurs !",
			COUNTER = "Objets de Shadowcraft fabriqués",
			HOVER = "Fabriquer %s objets d'ombrage avec le socle d'ombrage",
		},
		["Strong Stomach"] = {
			NAME = "Un estomac solide",
			DESCRIPTION = "Avez-vous ce qu'il faut pour survivre dans la nature ? Il est nécessaire d'avoir un estomac solide, car beaucoup de nourriture commence à pourrir lorsque vous vous en occupez. Voyez cela comme un entraînement pour votre estomac à manger des %s pourris.",
			COUNTER = "Pourriture mangée",
			HOVER = "Mangez %s Rot. N'y pensez pas, mangez-la...",
		},
		["Dreadful Constructor"] = {
			NAME = "Constructeur redoutable",
			DESCRIPTION = "Les grottes semblent un peu instables ces derniers temps, car de nombreux tremblements de terre se sont produits. Nos piliers de soutien en pierre ne sont pas capables d'absorber ces chocs, c'est pourquoi j'ai besoin d'un matériau plus solide, comme la dreadstone. Aidez-nous en construisant %s piliers en dreadstone pour que notre base dans les grottes soit en sécurité !",
			COUNTER = "Construction de piliers de pierre redoutable",
			HOVER = "Construire %s full dreadstone pillars",
		},
		["Poor Doggies"] = {
			NAME = "Pauvres chiens",
			DESCRIPTION = "Pauvres chiens, a dit ma mère. Je dis simplement qu'ils l'ont bien cherché ! Ces chiens cherchent des humains et les attaquent, on peut les appeler des pauvres ! Si tu vaincs %s d'entre eux, je te donnerai un vrai bon toutou !",
			COUNTER = "Chiens courants tués",
			HOVER = "Tuer %s des chiens de chasse, des chiens de feu ou des chiens de glace",
		},
		["The Queen Slayer"] = {
			NAME = "La reine tueuse",
			DESCRIPTION = "Les Reines des araignées sont devenues trop puissantes ! J'ai besoin de quelqu'un d'assez fort pour tuer %s d'entre elles, afin que notre village de cochons puisse continuer à vivre en paix !",
		},
		["Whac-A-Mole"] = {
			NAME = "Whac-A-Mole",
			DESCRIPTION = "J'ai entendu parler de ce jeu appelé Whac-A-Mole en dehors de Constant. J'ai essayé d'y jouer mais cela semble impossible, je n'arrive jamais à toucher une taupe. Montrez-moi que c'est possible en tuant %s taupes !",
		},
		["Running Like Clockwork"] = {
			NAME = "Courir comme une horloge",
			DESCRIPTION = "Je me demande comment ces horloges peuvent encore fonctionner sans problème alors qu'il n'y a personne pour les entretenir ! J'ai besoin que vous en détruisiez %s pour que je puisse mieux comprendre leur fonctionnement.",
			COUNTER = "Horlogerie détruite",
			HOVER = "Détruire %s clockworks",
		},
		["A Friend of Bunnymans"] = {
			NAME = "Un ami des Bunnymans",
			DESCRIPTION = "Les Bunnymans sont des créatures très douces qui peuvent sembler un peu grossières au premier abord, mais qui ont un cœur d'or. Essayez-le en donnant %s carottes à Bunnymans.",
			COUNTER = "Carottes nourries",
			HOVER = "Donner %s carottes à Bunnymans",
		},
		Firestarter = {
			NAME = "Déclencheur d'incendie",
			DESCRIPTION = "J'ai créé un prototype de coffre d'un nouveau genre, capable de résister aux incendies les plus violents. Mais je n'ai pas encore eu le temps de le tester, c'est pourquoi j'ai besoin de quelqu'un pour enflammer %s choses avec une torche.",
			COUNTER = "Les choses allumées",
			HOVER = "Mettre le feu à %s choses avec une torche",
		},
		["Squid Game"] = {
			NAME = "Jeu du calmar",
			DESCRIPTION = "Je veux jouer à un jeu avec toi ! Tue %s de calamars et je te donnerai quelque chose qui t'aidera à les garder frais !",
		},
		["It's Wednesday my Dudes!"] = {
			NAME = "C'est mercredi, mes amis !",
			DESCRIPTION = "Dois-je en dire plus ? Célébrez-la en libérant %s grenouilles de la constante !",
		},
		["The Archive Guardian"] = {
			NAME = "The Archive Guardian",
			DESCRIPTION = "Les Archives anciennes sont pleines de Sentinelles anciennes et elles ne veulent vraiment pas me laisser faire mes recherches en paix ! Aide-moi à les tenir à distance avec tes attaques en leur infligeant %s de dégâts !",
			COUNTER = "Dommages",
			HOVER = "Inflige %s de dégâts aux Sentinelles anciennes",
		},
		["Helmet Compulsory"] = {
			NAME = "Casque obligatoire",
			DESCRIPTION = "Nous voulons instiller une nouvelle ligne de conduite : Portez toujours votre casque lorsque vous êtes sous terre ! Mais la plupart des gens ne nous croient pas, c'est pourquoi nous devons leur montrer les résultats de l'absence de casque. Pour ce faire, il suffit de se faire frapper %s fois par des débris provenant d'un tremblement de terre.",
			COUNTER = "Heurtés par des débris",
			HOVER = "Être touché %s fois par des débris provenant d'un tremblement de terre",
		},
		["Good For Your Nerves"] = {
			NAME = "Bon pour les nerfs",
			DESCRIPTION = "De nos jours, la plupart des gens sont très stressés ! Prenez le temps de vous détendre en buvant %s thés apaisants et vous verrez à quel point cela vous aidera...",
			COUNTER = "Thés apaisantes ivres",
			HOVER = "Boire %s thés apaisants",
		},
		Nitroglycerin = {
			NAME = "Nitroglycérine",
			DESCRIPTION = "J'ai entendu dire qu'il existe un minéral aussi instable et explosif que la nitroglycérine dans le Constant. Cela a un rapport avec le Moon Glas, mais il m'en faut beaucoup pour pouvoir analyser correctement la structure et reproduire la version instable. Aidez-moi à trouver %s Moon Glas !",
			COUNTER = "Glas lunaire",
			HOVER = "Trouver %s Moon Glas en minant des roches ou similaires",
		},
		["It's A Trap!"] = {
			NAME = "C'est un piège !",
			DESCRIPTION = "Je veux étudier les guerriers araignées pour savoir comment ils sont tellement plus forts et intelligents que leurs frères et sœurs. J'ai besoin que tu en attrapes plusieurs !",
			COUNTER = "Les Spider Warriors capturés",
			HOVER = "Attraper %s guerriers araignées avec un piège",
		},
		["The Monster Breeder"] = {
			NAME = "L'éleveur de monstres",
			DESCRIPTION = "Certaines personnes que je connais m'ont dit que les oiseaux pondent maintenant des œufs monstrueux s'ils sont nourris avec de la viande monstrueuse. J'ai vraiment envie de voir quel genre de créature va éclore à partir de ces œufs, j'ai besoin que vous en créiez %s !",
			COUNTER = "Œufs de monstres",
			HOVER = "Produire %s d'œufs de monstres avec des oiseaux en cage",
		},
		["The Ancient Curse"] = {
			NAME = "L'ancienne malédiction",
			DESCRIPTION = "Selon une légende, au plus profond des ruines de l'ancienne civilisation, vit l'un des êtres de l'ombre les plus puissants ! J'ai besoin que vous le trouviez et que vous le tuiez, pour me montrer que ce n'est pas qu'une légende !",
		},
		["Oh Sweet Summer Child"] = {
			NAME = "Oh Sweet Summer Child",
			DESCRIPTION = "Êtes-vous encore coincé avec votre cataplasme au miel ? Ou êtes-vous déjà dans la bande des cool avec votre Sweetflower Wrap ? Allez, faites partie des enfants cool et fabriquez %s Sweetflower Wrap !",
			COUNTER = "Enveloppe Sweetflower cravatée",
			HOVER = "Artisanat %s Sweetflower Wrap",
		},
		["It's Raining!"] = {
			NAME = "Il pleut !",
			DESCRIPTION = "Il pleut ! C'est du moins ce que j'aurais voulu vous dire, mais malheureusement, la dernière pluie est tombée il y a longtemps. J'ai besoin que quelqu'un invoque la pluie pour nous, car c'est la seule possibilité qu'il nous reste pour que nos récoltes ne se flétrissent pas... J'ai besoin que vous l'invoquiez au moins %s fois !",
			COUNTER = "Pluie invoquée",
			HOVER = "Invoquer la pluie avec une Conque noyée %s fois",
		},
		["The Uncompromising Experience"] = {
			NAME = "L'expérience sans compromis",
			DESCRIPTION = "Êtes-vous aussi résistant que vous le pensez ? Montrez-moi votre valeur en survivant à %s jours d'affilée dans le Constant sans mourir !",
			COUNTER = "Jours de survie",
			HOVER = "Survivre à %s jours en une seule fois",
		},
		["Watch This!"] = {
			NAME = "Regardez ça !",
			DESCRIPTION = "J'ai peut-être volé des pierres précieuses dans la Forêt des cerises et voilà que les Veilleurs m'attaquent à vue ! Mais j'ai vraiment envie de me promener, alors s'il vous plaît, tuez l'un d'entre eux !",
		},
		["Mutated Queen"] = {
			NAME = "Reine mutante",
			DESCRIPTION = "La reine des abeilles a perdu la tête ! On dirait que la Forêt des cerises a provoqué une mutation qui l'a rendue vénéneuse et mortelle ! J'ai besoin de quelqu'un pour m'aider à me débarrasser d'elle !",
		},
		["A Reputable Person"] = {
			NAME = "Une personne de bonne réputation",
			DESCRIPTION = "La Forêt des Cerisiers et ses habitants vous observent en permanence... Faites un faux pas et votre réputation diminuera ! Montrez-moi que vous pouvez augmenter votre réputation jusqu'au nombre nécessaire !",
			COUNTER = "Réputation",
			HOVER = "Reach %s Réputation de la forêt",
		},
		["It's Bugging Me!"] = {
			NAME = "Ça m'énerve !",
			DESCRIPTION = "Cela m'énerve de ne pouvoir attraper aucun insecte dans la Forêt des cerises ! Chaque fois que je pense en avoir attrapé un, il s'enfuit ou s'envole... Si vous pouviez m'aider à attraper quelques insectes, je vous en serais très reconnaissant !",
			COUNTER = "Insectes capturés",
			HOVER = "Attraper %s insectes avec un filet",
		},
		["The Pacifier"] = {
			NAME = "Le Pacifier",
			DESCRIPTION = "Le monde tel que nous le connaissons est toujours en guerre. Je n'en peux plus ! J'ai entendu dire que l'on pouvait fabriquer un appareil qui apaise les créatures. C'est peut-être un moyen de ramener la paix dans ce monde !",
			COUNTER = "Pacifier construites",
			HOVER = "Construire %s Pacifier",
		},
		["Mischievous Thief"] = {
			NAME = "Voleur espiègle",
			DESCRIPTION = "J'ai entendu parler d'un voleur qui s'en prend aux Tallbirds. Je veux rencontrer cette personne, mais je dois m'assurer qu'elle est digne de confiance. Montre-moi que tu l'es en volant %s œufs d'oiseaux-talons !",
			COUNTER = "Vol d'œufs de merle de roche",
			HOVER = "Voler %s d'œufs d'oiseaux-taureaux",
		},
		["People Pleaser"] = {
			NAME = "Plaisir des gens",
			DESCRIPTION = "Je veux rendre les gens heureux ! Mais pour y parvenir, j'ai besoin que davantage de personnes aient des pensées positives ! Sois l'une de ces personnes et montre-moi à quel point tu es heureux !",
			COUNTER = "Aura de santé",
			HOVER = "Avoir une Aura de Sanité de %s/min",
		},
		["The Hunt For Mutants"] = {
			NAME = "La chasse aux mutants",
			DESCRIPTION = "J'ai entendu parler de mutants géants qui terrorisent les cochons autour des failles lunaires. Je veux les traquer, mais je ne suis pas assez fort. Aide-moi en tuant % d'entre eux !",
			COUNTER = "Les géants mutants tués",
			HOVER = "Tuer %s Géants mutants (soit Deerclops de cristal, Bearger blindé ou Varg possédé)",
		},
		["Praise The Pigking"] = {
			NAME = "Éloge du cochon d'Inde",
			DESCRIPTION = "Le roi des cochons est la personne la plus généreuse de Constant ! Il nous donne beaucoup d'or, mais nous devons le féliciter pour cela ! Montre-moi que tu es digne de son or en lui donnant tant d'objets qu'il te donnera % d'or !",
			COUNTER = "L'or",
			HOVER = "Recevoir %s d'or du Pigking",
		},
		["Training Makes Perfect"] = {
			NAME = "L'entraînement rend parfait",
			DESCRIPTION = "Je vieillis et je n'ai plus besoin de mon Howlitzer. Je veux le donner à quelqu'un qui en est digne. Montrez-moi vos talents de combattant à distance en infligeant %s de dégâts avec des fléchettes !",
			COUNTER = "Dommages",
			HOVER = "inflige %s de dégâts avec des fléchettes",
		},
		["What Is Hunger?"] = {
			NAME = "Qu'est-ce que la faim ?",
			DESCRIPTION = "La constante est un endroit difficile, mais j'ai entendu parler de personnes qui ne savent même pas ce qu'est la faim ! Montre-moi que tu es l'un d'entre eux en restant au-dessus de 80%% de faim pendant %s secondes !",
			COUNTER = "Secondes au-dessus de 80 % de la faim",
			HOVER = "Reste %s secondes au-dessus de 80%% de faim en une seule fois",
		},
		["Repairing The Past"] = {
			NAME = "Réparer le passé",
			DESCRIPTION = "Le passé est quelque chose que nous ne pouvons pas changer, mais nous pouvons le réparer ! J'ai besoin de quelqu'un pour réparer %s objets avec %s !",
			COUNTER = "Articles réparés",
			HOVER = "Réparer %s éléments avec %s",
		},
		["A Soul For A Soul"] = {
			NAME = "Une âme pour une âme",
			DESCRIPTION = "On dit que l'âme d'une personne persiste à travers les changements physiques. Je veux tester cette théorie ! Montre-moi que tu en es digne en te transformant en un autre personnage !",
			COUNTER = "Transformations",
			HOVER = "Passer à un autre personnage avec un idole de roche lunaire",
		},
		["Dancing With The Devil"] = {
			NAME = "Danse avec le diable",
			DESCRIPTION = "Le Diable, alias l'Ancien Fuelweaver, est une créature très forte qui terrorise les ruines depuis longtemps. Tout le monde vit dans la crainte de cette créature, mais il ne faut pas avoir peur ! J'ai besoin de quelqu'un pour leur montrer que le Diable n'est pas aussi terrifiant qu'ils le pensent en dansant %s fois près de lui !",
			COUNTER = "Danses",
			HOVER = "Danse %s fois près de l'ancien Fuelweaver",
		},
		["Hell's Guardian"] = {
			NAME = "Gardien de l'enfer",
			DESCRIPTION = "La libellule garde l'entrée de l'enfer, mais je veux y entrer ! J'ai besoin de quelqu'un pour la vaincre afin de pouvoir entrer dans la piscine de magma !",
		},
	},
	QUEST_FUNCTIONS = {
		SANITY_90 = "Rester à plus de 90 % de santé mentale pendant x secondes en une seule fois !",
		SANITY_10 = "Restez à moins de 10 % de santé mentale pendant x secondes en une seule fois !",
		LUNACY_10 = "Restez à moins de 10 % d'aliénation pendant x secondes en une seule fois !",
		LUNACY_90 = "Rester à plus de 90 % de folie pendant x secondes en une seule fois !",
		MONSTERLASAGNA = "Manger x Monterlasagna",
		SURFNTURF = "Manger x Surf'n'Turf",
		LOBSTERDINNER = "Dîner Eat x Wobster",
		LEAFLOAF = "Manger x Pain de viande à base de feuilles",
		JELLYBEAN = "Manger x Jellybeans",
		KOALEFIG_TRUNK = "Mangez x Malle farcie de figues",
		BARNACLESUSHI = "Manger x Nigiri aux balanes",
		FOSSILS = "Trouver x fossiles par l'exploitation minière",
		GOLDNUGGETS = "Trouver x pépites d'or en minant",
		REDGEM = "Trouver x gemmes rouges en minant",
		BLUEGEM = "Trouver x gemmes bleues en minant",
		PURPLEGEM = "Trouver x gemmes violettes en minant",
		GREENGEM = "Trouver x pierres précieuses vertes en minant",
		YELLOWGEM = "Trouver x gemmes jaunes en minant",
		ORANGEGEM = "Trouver x gemmes orange en minant",
		LIVINGLOG = "Trouver x bûches vivantes en les coupant",
		LIFEAMULET = "Trouver x Amulettes de vie en creusant",
		GEARS = "Trouver x engrenages en creusant",
		CHARLIE = "Se faire frapper x fois par Charlie",
		TRADES = "Échanger x fois avec le roi des cochons",
		TRINKET_12 = "Échanger x fois un Tentacule Desséché avec le Roi Cochon",
		TRINKET_8 = "Échangez x fois une bonde en caoutchouc durci avec le roi des porcs",
		TRINKET_24 = "Échangez x fois une jarre Lucky Cat avec le roi des cochons",
		TRINKET_26 = "Échanger x fois une coupe de pommes de terre avec le roi des cochons",
		FISHING = "Catch x Fishes",
		ICEBREAM = "Catch x Ice Bream",
		DEEPBASS = "Catch x Deep Bass",
		SPITTLEFISH = "Catch x Spittlefish",
		SUNFISH = "Attraper x Poisson-lune brûlant",
		TUNA = "Capture x Thon à nageoires cendrées",
		FALLOUNDER = "Capture x flétan noir",
		CORNCOD = "Catch x Corn Cod",
		TELEPORT = "Téléporter x fois quelque chose au loin",
		T_BEEFALO = "Téléporter x Beefalo au loin",
		T_DEERCLOPS = "Téléporter x cerfs-volants au loin",
		T_BEARGER = "Téléporter x Bearger au loin",
		T_DRAGONFLY = "Téléportation de x libellules",
		T_MOOSE = "Téléportation de x Moose/Goose",
		MOONBASE = "Défendre x fois la base lunaire",
		BUILD_BUFFER = "Recevoir %s comme construction en mémoire",
		KRAMPUS_SACK = "%s%% Chance de sac Krampus",
	},
	SCRAPBOOK = {
		NIGHTMARE_EYEBONE = "Invoque Nightmare Chester lorsqu'il est ramassé. Le Cauchemar de Chester suivra le porteur. Tant que Nightmare Chester est en vie, l'œil est ouvert.",
		FROGKING_P_CROWN = "Peut être ravitaillé en grenouilles. Lorsqu'elles sont portées, les sirènes et les grenouilles sont vos amies. Les grenouilles vous aideront si vous êtes attaqué.",
		FROGKING_SCEPTER = "Peut être ravitaillé en grenouilles. Peut lancer un sort qui fait apparaître une grenouille uniquement autour du lanceur de sort pendant 60 secondes.",
		GLOMMERFUELMACHINE_ITEM = "Peut être ravitaillé en carburant de cauchemar. Lorsqu'il est placé, il génère du Dark Glommerfuel.",
		GLOMMERFUELMACHINE = "Peut être ravitaillé en carburant de cauchemar. Lorsqu'il est placé, il génère du Dark Glommerfuel.",
		BLACKGLOMMERFUEL = "Peut être placé comme piège pour les ennemis. Si rien ne passe au travers, il se dissout au bout de 15 secondes. L'ennemi subit 40 % de dégâts en moins, reçoit 20 % de dégâts en plus et est 40 % plus lent pendant 10 secondes.",
		GLOMMER_LIGHTFLOWER = "Génère au total 20 Glommer Fuel au fil du temps.",
		QUESTBOARD = "Peut être utilisé pour obtenir une nouvelle quête chaque jour. Si cette option est activée, vous pouvez également créer vos propres quêtes ici.",
		REQUEST_QUEST = "Une fois lue, une nouvelle quête sera ajoutée à votre journal des quêtes. Elles peuvent également apparaître dans des difficultés différentes.",
		SHADOW_CREST = "Peut être ravitaillé avec du carburant de cauchemar. Les entités de l'ombre vous infligent 33% de dégâts en moins. Lorsque vous le portez, vous pouvez utiliser une attaque spéciale sur les ennemis.",
		SHADOW_MITRE = "Peut être ravitaillé avec du carburant de cauchemar. Vous recevrez 33% de dégâts en moins de la part des entités de l'ombre. Lorsque vous le portez, vous laissez des chauves-souris d'ombre derrière vous lorsque vous êtes touché.",
		SHADOW_LANCE = "Peut être ravitaillé en carburant de cauchemar. Augmente de 50 % les dégâts infligés aux entités lunaires et utilise moins d'énergie contre les entités lunaires.",
	},
}