return {
	NAMES = {
		QUESTBOARD = "Tablero de misión",
		REQUEST_QUEST = "Solicitud",
		REQUEST_QUEST_VERY_EASY = "Solicitud muy fácil",
		REQUEST_QUEST_EASY = "Solicitud fácil",
		REQUEST_QUEST_NORMAL = "Solicitud normal",
		REQUEST_QUEST_DIFFICULT = "Solicitud dura",
		REQUEST_QUEST_VERY_DIFFICULT = "Solicitud muy difícil",
		REQUEST_QUEST_SPECIFIC = "Solicitud",
		GLOMMERFUELMACHINE = "Máquina de combustible oscura de Glommer",
		GLOMMER_LIGHTFLOWER = "Flor de luz de Glommer",
		CHESTER_BOSS = "Pesadilla Chester",
		NIGHTMARECHESTER = "Pesadilla Chester",
		NIGHTMARECHESTER_EYEBONE = "Nightmare Chester Eyebone",
		GLOMMER_SMALL = "Icestorm Glommer",
		GLOMMER_BOSS = "Glommer Ventisca",
		BLACKGLOMMERFUEL = "Glommerfuel oscuro",
		["ADDITIONAL QUEST SLOTS"] = "Ranuras de búsqueda adicionales",
		SHADOW_CREST = "Cresta de la Sombra",
		SHADOW_MITRE = "Mitra de la Sombra",
		SHADOW_LANCE = "Lanza de la Sombra",
		FROGKING = "Rey rana",
		FROGKING_P_CROWN = "Corona de la rana",
		FROGKING_SCEPTER = "Cetro de las ranas",
		FROGKING_BEYBLADE = "Peonza de diamantes",
	},
	DESCRIBE = {
		QUESTBOARD = "Creo que conozco algunos de estos...",
		REQUEST_QUEST = "Parece que alguien perdió una solicitud en alguna parte. ¡Bueno para mí!",
		REQUEST_QUEST_VERY_EASY = "Parece que alguien perdió una solicitud en alguna parte. ¡Bueno para mí!",
		REQUEST_QUEST_EASY = "Parece que alguien perdió una solicitud en alguna parte. ¡Bueno para mí!",
		REQUEST_QUEST_NORMAL = "Parece que alguien perdió una solicitud en alguna parte. ¡Bueno para mí!",
		REQUEST_QUEST_DIFFICULT = "Parece que alguien perdió una solicitud en alguna parte. ¡Bueno para mí!",
		REQUEST_QUEST_VERY_DIFFICULT = "Parece que alguien perdió una solicitud en alguna parte. ¡Bueno para mí!",
		REQUEST_QUEST_SPECIFIC = "Parece que alguien perdió una solicitud en alguna parte. ¡Bueno para mí!",
		GLOMMERFUELMACHINE = "¡Un dios ha traído su bendición a esta máquina!",
		GLOMMER_LIGHTFLOWER = "¡Un regalo de un dios!",
		CHESTER_BOSS = "¡No debería haber hecho eso! NO debería haber hecho eso!",
		NIGHTMARECHESTER = "Parece un poco molesto pero no creo que lo diga en serio",
		NIGHTMARECHESTER_EYEBONE = "¡Hasta el ojete parece molesto!",
		GLOMMER_SMALL = "Oh, es tan dulce y pequeño... Oh dios ¿por qué me ataca?!",
		GLOMMER_BOSS = "¡Ha despertado y está aquí para matarnos!",
		BLACKGLOMMERFUEL = "Una sustancia oscura y viscosa, ¡puede usarse para atrapar a otros monstruos!",
		SHADOW_CREST = "¡Un poco macabro tener a tu enemigo en la cabeza pero esto es demasiado bueno!",
		SHADOW_MITRE = "Parece que todavía tiene algo del Obispo de las Sombras...",
		SHADOW_LANCE = "¡Un arma sedienta de sangre parece, especialmente contra enemigos lunares!",
		FROGKING = "¡Este da miedo!",
		FROGKING_P_CROWN = "¡Una corona que hará que todas las ranas te vean como su rey!",
		FROGKING_SCEPTER = "Un cetro que gobierna a sus súbditos con puños de hierro",
		FROGKING_BEYBLADE = "¡Mejor que no te golpee este!",
	},
	RECIPE_DESC = {
		QUESTBOARD = "¡Empezar a realizar misiones!",
		REQUEST_QUEST = "¡No creo que pueda crear esto!",
		REQUEST_QUEST_VERY_EASY = "Solicitud muy fácil",
		REQUEST_QUEST_EASY = "Solicitud fácil",
		REQUEST_QUEST_NORMAL = "Solicitud normal",
		REQUEST_QUEST_DIFFICULT = "Solicitud dura",
		REQUEST_QUEST_VERY_DIFFICULT = "Solicitud muy difícil",
		REQUEST_QUEST_SPECIFIC = "Solicitud",
		GLOMMERFUELMACHINE = "¡No puedes hacer cosas divinas!",
		GLOMMER_LIGHTFLOWER = "¡No puedes hacer cosas divinas!",
	},
	ATTACKWAVES = {
		MISSION_FAILED = "Misión fallida...",
		MISSION_SUCCESS = "¡Misión cumplida!",
		MISSION_OBJECTIVE = "¡Necesito proteger a %s!",
		TIME_LEFT = "Tiempo hasta la llegada de %s: %i",
		ENEMIES_LEFT = "Esta ola contiene %s enemigos que debes derrotar",
		WAVE = "Oleada %s\n%s/%s enemigos",
	},
	ACTIONS = {
		FIGHT_GLOMMER = "¿Ser un amigo?",
		SHADOW_ROOK_ATTACK = "Ataque de la torre de la sombra",
	},
	REQUEST_QUEST = {
		FULL_LOG = "¡Ya tengo un registro de misiones completo!",
		QUEST_ADDED = "¡Misión agregada!",
	},
	TALKING = {
		REWARDS = "¡Obtuve las recompensas por mi batalla!",
	},
	REWARDS = {
		health = "Bono de salud para x min",
		sanity = "Bono de cordura para x min",
		hunger = "Bono por hambre para x min",
		sanityaura = "Bono de Sanityaura para x min",
		hungerrate = "Tasa de hambre para x min",
		healthrate = "Salud cada 10 segundos durante x min",
		damage = "Bono por daños para x min",
		damagereduction = "Bono por reducción de daños para x min",
		range = "Bono por alcance para x min",
		winterinsulation = "Bono por aislamiento invernal para x min",
		summerinsulation = "Bono por aislamiento de verano para x min",
		worker = "Bono de trabajo para x min",
		sleeping = "Bono para dormir para x min",
		nightvision = "Vista nocturna para x min",
		speed = "Bono de velocidad para x min",
		escapedeath = "veces escapando de la Muerte durante x min",
		planardamage = "Bonificación de daño planar durante x min",
		planardefense = "Bonificación de defensa planar durante x min",
		dodge = "Enfriamiento de la bonificación de esquiva durante x min",
		crit = "Probabilidad crítica de hacer 1,5x de daño durante x min.",
		waterproofness = "Bonificación de estanqueidad durante x min",
	},
	QUEST_BOARD = {
		QUEST_BOARD = "Tablero de misión",
		LOOK_FOR_QUESTS = "Busque nuevas misiones",
		LOOK_FOR_QUESTS_ACCEPTED = "¡Ya has aceptado una misión!",
		LOOK_FOR_QUESTS_MAX = "¡Tengo la máxima cantidad de misiones!",
		OBTAIN_LEVEL_REWARDS = "Obtén recompensas de nivel",
		CREATE_NEW_QUESTS = "Crea nuevas misiones",
		IN_CAVES = "¡No es posible en las cuevas!",
		CLOSE = "Cerrar",
		NO_NAME = "Sin nombre",
		REWARDS = "Recompensas",
		ACCEPT_QUEST = "Aceptar Quest",
		ALREADY_ACCEPT_QUEST = "¡Ya has aceptado una nueva misión!",
		REWARD_LEVEL = "Nivel de recompensa",
		ACCEPTED_REWARDS = "Recompensas aceptadas por nivel",
		LEVEL = "Nivel",
		REWARD1 = "Recompensa 1",
		REWARD2 = "Recompensa 2",
		REWARD3 = "Recompensa 3",
		DIFFICULTY = "Dificultad",
		VICTIM = "Víctima",
		AMOUNT = "Monto",
		AMOUNT_OF_KILLS = "Monto de muertes",
		POINTS = "Puntos",
		TITLE = "Título",
		WRITE_DESCRIPTION = "Escribir descripción",
		ADD_QUEST = "Agregar misión al grupo de misiones",
		SAVE_DESCRIPTION = "Guardar descripción",
		YES = "Sí",
		NO = "No",
		ASK_ADD_QUEST = "¿Estás seguro de que deseas agregar esta misión al grupo de misiones?",
		QUEST = "Misión",
		ADDED_SUCCESFULLY = "Añadido exitosamente",
		QUEST_EXISTS = "La misión con este nombre ya existe. Por favor elije otro.",
		NUMBERS = "Números",
		FOODS = "Alimentos",
		ITEMS = "Elementos",
		REMOVE_QUEST = "Eliminar la búsqueda del grupo de búsqueda",
		ASK_REMOVE_QUEST = "¿Eliminar la búsqueda \"%s\"?",
		MANAGE_QUESTS = "Gestionar las misiones personalizadas",
		REQUIREMENTS = "Prerrequisitos",
		EDIT_QUEST = "Editar búsqueda",
		ASK_OVERWRITE_QUEST = "¿Quieres cambiar la búsqueda %s a esta versión? La quest será eliminada del registro de quest de todos los jugadores!",
	},
	QUEST_LOG = {
		EMPTY_SLOT = "Ranura\nde misión\nvacía",
		BUTTON = "Abrir registro de misiones",
		NO_NAME = "Sin nombre",
		DESCRIPTION = "Descripción",
		REWARDS = "Recompensas",
		NOT_DEFINED = "No definido",
		GET_REWARDS = "¡Obtener recompensas!",
		RECEIVE_REWARDS = "Recompensas recibidas por la misión",
		FORFEIT_QUEST = "Perder Quest",
		QUEST_LOG = "Registro de misiones",
		CLOSE = "Cerrar",
		PAGE_1 = "Primera página de misiones",
		PAGE_2 = "Segunda página de misiones",
		PAGE_3 = "Tercera página de misiones",
		PAGE_4 = "Cuarta página de misiones",
		PAGE_5 = "Quinta página de misiones",
		PAGE_6 = "Sexta página de misiones",
		SCOREBOARD = "Marcador",
		CURRENT_LEVEL = "Nivel actual",
		POINTS = "Puntos",
		LEVEL = "Nivel",
		YES = "Sí",
		NO = "No",
		BOSSFIGHT = "¡Lucha del jefe!",
		COMPLETED_QUESTS = "Misiones completadas",
		TOTAL_POINTS = "Puntos totales",
		ASK_FORFEIT = "¿Estás seguro de que quieres renunciar a esta misión?",
		SUCCESS = "¡Completado con éxito!",
		HEALTHBONUS = "Aumento de salud:",
		SANITYBONUS = "Aumento de la cordura:",
		HUNGERBONUS = "Aumento del hambre:",
		SPEEDBONUS = "Aumento de velocidad:",
		WINTERINSULATIONBONUS = "Aumento del aislamiento en frío:",
		SUMMERINSULATIONBONUS = "Aumento del aislamiento térmico:",
		WORKMULTIPLIERBONUS = "Multiplicador de trabajo:",
		KILL = "Matar",
		PROGRESS = "Progreso",
		SHOW_BONUS = "Mostrar bonificación",
		CURR_RANK = "Rango actual\n\nPuntos hasta el siguiente rango: ",
		QUEST_LINE = "¡Esta búsqueda es parte de una línea de búsqueda!",
		SCALING = "Búsqueda escalable (puede volverse más difícil si la completas)",
		GO_BACK = "Volver atrás",
		SHOW_STATS = "Mostrar estadísticas",
		SHOW_QUESTS = "Mostrar misiones",
		TURN_LEFT = "Pasar página a la izquierda",
		TURN_RIGHT = "Pasar página a la derecha",
	},
	TEMP_BONI = {
		HEALTH = " Salud",
		SANITY = " Cordura",
		HUNGER = " Hambre",
		SANITYAURA = "/min Aura de cordura",
		HUNGERRATE = "% Tasa de hambre",
		HEALTHRATE = " Salud cada 10 segundos",
		DAMAGE = " Daño",
		DAMAGEREDUCTION = "% Reducción de daños",
		RANGE = " Gama",
		WINTERINSULATION = " Aislamiento invernal",
		SUMMERINSULATION = " Aislamiento de verano",
		WORKER = "% Eficacia del trabajo",
		SLEEPING = " Salud/Sanidad por segundo Dormir",
		NIGHTVISION = "Visión nocturna",
		SPEED = " % Velocidad",
		ESCAPEDEATH = " Tiempos de escapar de la muerte",
		PLANARDAMAGE = " Daños planares",
		PLANARDEFENSE = " Defensa planar",
		DODGE = " Cada %s segundos esquiva",
		CRIT = "% Probabilidad crítica de hacer 1.5x de daño",
		TIME_LEFT = "Tiempo restante:",
		WATERPROOFNESS = "% Impermeabilidad",
	},
	LOADING_TIPS = {
		request = "Las peticiones pueden caer de criaturas muertas. También puedes habilitar su elaboración en las opciones de configuración!",
		questboard = "¡Construye un tablero de quest para tener acceso a una nueva quest cada día y, si está activado, la posibilidad de crear tus propias quest!",
		attackwaves = "Las misiones en las que necesites proteger a una criatura comenzarán después de una cantidad de tiempo aleatoria tras aceptar la misión",
		bossfight = "Las peleas de jefes se pueden iniciar desde el registro de misiones. Cada vez que subas de nivel, tendrás una oportunidad de poder iniciar una pelea de jefes. No perderás tus objetos si mueres, pero si ganas, ¡habrá una recompensa para ti!",
		temporarybonus = "Algunas misiones te darán un bonus temporal como recompensa. Verás cuáles están activas en la parte superior de tu pantalla. La cantidad máxima de boni es de 5, si obtienes más, los más antiguos serán eliminados",
		quest_line = "Hay algunas misiones que forman parte de una línea de misiones. Las búsquedas que siguen a la búsqueda inicial se añadirán automáticamente y no se podrán conseguir de otra manera. Estas misiones tendrán una bombilla.",
		levelupcomponent = "Si has activado el sistema de niveles, te harás más fuerte con cada nivel que ganes. Ganas puntos completando misiones y derrotando criaturas. La bonificación se puede ver en la página de la izquierda en el registro de misiones",
	},
	QUESTS = {
		["The Wicked Mist Fury"] = {
			NAME = "La furia de la niebla malvada",
			DESCRIPTION = "Esos molestos zancudos marinos están arruinando el lugar de retiro que es el bioma anegado.\n¡Por favor, ayúdanos a deshacernos de ellos para que podamos descansar en paz en este hermoso lugar!",
		},
		["The Powerful Shadow from Below"] = {
			NAME = "La poderosa sombra de abajo",
			DESCRIPTION = "¡Estas aterradoras sombras nos están atacando tan pronto como zarpamos!\nNo sabemos cómo escapar de ellas, y mucho menos cómo derrotarlas.\n¡Si tan solo un valiente aventurero pudiera ayudar!",
		},
		["The Reckoning of the Gestalt"] = {
			NAME = "El ajuste de cuentas de la Gestalt",
			DESCRIPTION = "¡Las Gestalt están hambrientas de tu iluminación! \nQuédate %s segundos seguidos a más del 85%% de iluminación en la isla lunar para recoger su ofrenda.",
			COUNTER = "Segundos",
			HOVER = "¡Permanece a más del 85%% de locura durante %s segundos a la vez!",
		},
		["The Corrupt Prophecy Revenge"] = {
			NAME = "La venganza de la profecía corrupta",
			DESCRIPTION = "Una profecía una vez predicha mencionó que la adoración de un monstruo insectoide traerá paz y riqueza a esta tierra desolada. \n¡Pero mira a dónde nos llevó! ¡Solo los monstruos que nos rodean, no hay suficiente para comer y la noche es la parte más aterradora de todo! \nComo venganza por esta profecía, ¡queremos que elimines a este monstruo insectoide llamado Glommer! \nFirmado, el Rey Cerdo.",
		},
		["The Monstrous Delicacy"] = {
			NAME = "La monstruosa delicadeza",
			DESCRIPTION = "Me ofrecieron una lasaña monstruosa aparentemente deliciosa de un cocinero conocido, ¡pero quiero estar seguro de que no me matará si trato de comerla! \nSi alguien pudiera comer cinco de ellas para demostrarme que mis dudas eran infundadas, yo los recompensará en consecuencia!",
			COUNTER = "Monsterlasagna",
			HOVER = "Coma %s Monsterlasagna",
		},
		["The Explorers End"] = {
			NAME = "El fin de los exploradores",
			DESCRIPTION = "Cierto científico nos habló de una criatura extremadamente peligrosa que aparece después de montar el Sifonador Lunar. \nSe llama Campeón Celestial. \n¡Temo por mi vida! \n¡Destruye este monstruo y trae la paz mundial! \nComo recompensa, lo haré ¡Duplica cada artículo de tu inventario al aceptar la recompensa! \n (¡Esto excluye los artículos de tu mochila!)",
		},
		["Within the Labyrinth"] = {
			NAME = "Dentro del Laberinto",
			DESCRIPTION = "¡El Minotauro, la criatura mítica de muchos cuentos, ha aparecido en este mundo! \nComo se predijo, se mantiene en el Laberinto. \nPor favor, derrótalo para que mis hijos puedan volver a jugar allí, solo me están poniendo de los nervios ¡estando en casa!",
		},
		["The Stone from Below"] = {
			NAME = "La piedra de abajo",
			DESCRIPTION = "Me gustaría analizar algunos fósiles que se pueden encontrar en este mundo. \nDesafortunadamente, no puedo cavar en las cuevas porque no soy lo suficientemente fuerte para sobrevivir allí. \nSi alguien pudiera ayudarme, estaría muy ¡agradecido!",
			COUNTER = "Fósiles",
			HOVER = "Encontrar %s fósiles",
		},
		["Beyond the Charming Hamlet"] = {
			NAME = "Más allá de la encantadora aldea",
			DESCRIPTION = "¡Estos Hombres Cerdos se están apoderando de este mundo! \nSe reproducen a un ritmo alarmante y dejan heces por todas partes. \nPor favor, controle la población.",
		},
		["Corpses of the Swampy Badlands"] = {
			NAME = "Cadáveres de las tierras baldías pantanosas",
			DESCRIPTION = "Muchos aventureros han muerto tratando de completar esta misión, ¡espero que no seas uno de ellos! \nNecesitamos que los tentáculos desaparezcan del pantano para que podamos viajar en paz.",
		},
		["The Bane of Lake Nen"] = {
			NAME = "La perdición del lago Nen",
			DESCRIPTION = "Nuestro lago Nen no está muy lejos de tu mundo y, a veces, recibimos la visita del terrible Malbatros. \n¡Roba todos nuestros peces que son necesarios para que sobrevivamos! \nPor favor, te lo ruego, derrota a este monstruo. que no tenemos que morirnos de hambre!",
		},
		["The Scorched Nightmare Amulet"] = {
			NAME = "El amuleto de la pesadilla quemada",
			DESCRIPTION = "¡Quiero ver qué tan bien puedes sobrevivir! \nEquipa un amuleto de pesadilla y recalienta al mismo tiempo durante %s segundos de una vez. \nPero no te atrevas a no hacer una de estas cosas ni por un segundo, ya que gané ¡No lo aceptes! \n¡Veamos si puedes hacer esto!",
			COUNTER = "Segundos ardientes",
			HOVER = "Permanece loco y sobrecalentado durante %s segundos a la vez",
		},
		["The Fearful Trial"] = {
			NAME = "El terrible juicio",
			DESCRIPTION = "Quiero que te deshagas de todos los grandes jefes de temporada en un año. \nLo que significa son: \nOtoño = Oso \nInvierno = Ciervo \nPrimavera = Alce / Ganso \nVerano = Antlion \n \nSi logras derrotarlos a todos en un año , ¡serás recompensado generosamente!",
			COUNTER = "Jefes",
			HOVER = "Mata a los 4 jefes de temporada en un año",
		},
		["Across the Desert"] = {
			NAME = "A través del desierto",
			DESCRIPTION = "He oído hablar de una extraña criatura que vive en el desierto. \nAparentemente, se enoja muy rápido y solo las ofrendas pueden ayudar a apaciguarlo. \nDesgraciadamente, ¡casi no nos quedan esas ofrendas! \nSi alguien pudiera derrotarlo, estaríamos para siempre ¡agradecido!",
		},
		["The Corrupt Darkness"] = {
			NAME = "La oscuridad corrupta",
			DESCRIPTION = "Actualmente estoy haciendo algunas pruebas para analizar la fuerza de Charlie. \nNecesitaré un voluntario para absorber algunos de sus golpes. \nSi tienes un rasgo masoquista, ¡acepta!",
			COUNTER = "Golpes",
			HOVER = "Recibe %s golpes de Charlie",
		},
		["The Legend of the Trade Road"] = {
			NAME = "La leyenda de la ruta comercial",
			DESCRIPTION = "Nos gustaría fortalecer nuestras relaciones comerciales con los cerdos. \nPara hacer esto, necesitamos que realices algunos intercambios con el Rey Cerdo en nuestro nombre. \n¡Serás recompensado en consecuencia!",
			COUNTER = "Vientos alisios",
			HOVER = "Haz %s intercambios con el Rey Cerdo",
		},
		["The Vampire Dungeon"] = {
			NAME = "La mazmorra de vampiros",
			DESCRIPTION = "¡Estamos tratando de explorar el subsuelo, pero desafortunadamente llegamos a un punto en el que estamos atascados! \n¡Estos murciélagos vampiros nos están dejando secos! \n¡Por favor, derrótalos para que podamos avanzar!",
		},
		["Within the Stream"] = {
			NAME = "Dentro de la corriente",
			DESCRIPTION = "Necesito muestras de los diferentes peces que viven en los océanos de este mundo. \n¡Captura %s peces e informa con los resultados!",
			COUNTER = "Peces capturados",
			HOVER = "Atrapa %s peces",
		},
		["Mage of the Manor Baldur"] = {
			NAME = "Mago de la mansión Baldur",
			DESCRIPTION = "¡Yo, el Gran Mago de la Mansión Baldur, te invito a que te sometas a un examen! \n¡Tendrás que teletransportar a un Deerclops! \nSugerencia: puedes usar un bastón de telelocalizador. \nVeamos si tienes el poder mágico en ti para cumplir ¡esta!",
			HOVER = "Teletransportar a Deerclops",
			COUNTER = "Deerclops",
		},
		["The Rage of Ioun"] = {
			NAME = "La ira de Ioun",
			DESCRIPTION = "Soy Ioun. No se ha visto a mi padre desde que entró en el bosque para recoger seda. \n¡Estoy seguro de que las arañas tienen la culpa! \n¡La rabia está empezando a consumirme, pero no soy lo suficientemente fuerte para calmar este deseo de venganza! \n¡Por favor ayúdame!",
		},
		["The Sack For the Unlucky"] = {
			NAME = "El saco de los desafortunados",
			DESCRIPTION = "Escuché que te gusta el Krampussack. \nPero también escuché que eres un tipo desafortunado, mi más sentido pésame. \nComo una oferta que no puedes rechazar, ¡te daré un Krampussack si derrotas a suficientes de ellos!",
		},
		["Below the Abandoned Land"] = {
			NAME = "Below the Abandoned Land",
			DESCRIPTION = "I heard that there are imeasurable treasures to be found in the land underground.\nLet's make a trade, I will give you the location and you will go and get it.\nThen we can share the loot!\nThe treasures can be found in the stalagmites that grow underground.",
			COUNTER = "Stalagmites",
			HOVER = "Encuentra un tesoro en las estalagmitas de las cuevas",
		},
		["A Cute Companion"] = {
			NAME = "Una linda compañera",
			DESCRIPTION = "¡Quiero a Chester, de verdad, de verdad que lo quiero! \nQuiero que tenga un amigo con el que jugar. \nHe oído que en el subsuelo hay una criatura parecida a él.",
			HOVER = "Mantener la pecera de Hutch",
		},
		["The Allies Within the Land"] = {
			NAME = "Los aliados dentro de la tierra",
			DESCRIPTION = "¡Todo el mundo necesita amigos! \nPor eso quiero ayudar a la gente a encontrar amigos.\nY qué mejor motivación que una recompensa...\nSi consigues 10 amigos que te sigan, ya sean cerdos, arañas o lo que sea, me da igual, ¡te recompensaré!",
			COUNTER = "Seguidor",
			HOVER = "Tener %s seguidores a la vez",
		},
		["Orcus's Living Dead"] = {
			NAME = "Los muertos vivientes de Orcus",
			DESCRIPTION = "Estos sabuesos que aparecieron en la Isla Lunar no son normales, ¡irradian muerte! \n¡Quiero erradicarlos antes de que ocurran cosas peores!",
		},
		["The Damned Legacy"] = {
			NAME = "El legado maldito",
			DESCRIPTION = "Hola mi nombre es Wilba, tal vez me conozcas de otro continente.\nComo tenía que seguir el legado de mi padre, me transformo en un Werepig cada luna llena.\n¡Pero ya no quiero hacerlo! \n¡He oído que la maldición se puede romper si defiendes la base de piedra lunar %s veces de los Werepigs y los sabuesos! \n¡Por favor ayúdame!",
			COUNTER = "Tiempos defendidos",
			HOVER = "Defiende la base lunar %s veces",
		},
		["The Abandoned Chester"] = {
			NAME = "El Chester abandonado",
			DESCRIPTION = "¡Mi maestro, el Antiguo Tejedor de Combustible, se olvidó completamente de mí y me dejó a mi suerte en este mundo cruel!",
			COUNTER = "Ondas de ataque",
			HOVER = "¡Protege el Chester!",
		},
		["The Sharks Demise"] = {
			NAME = "La desaparición de los tiburones",
			DESCRIPTION = "Perdóname, aventurero. Se requiere tu ayuda.\nLa naturaleza está intranquila y por una buena razón también. Algún tipo de fuerza demoníaca se ha colado en estas tierras, pequeña al principio, pero se hace más fuerte cada día. \nEs sólo cuestión de tiempo antes de que no podamos detenerlas. \nPor favor, héroe, busca su origen, destrúyelo y deshazte de esos miserables Rockjaws.\nHéroe, actúa con rapidez cuando te enfrentes a los Rockjaws. \nPuedes acabar con todos los que quieras, cuantos menos de esos infelices haya en este mundo, mejor.",
		},
		["The Houndstooth Curse"] = {
			NAME = "La maldición de la pata de gallo",
			DESCRIPTION = "¡Busco tu ayuda, aventurero! \n¡Los miserables Wargs han asolado nuestra pequeña aldea de cerdos! \n¡Por favor, derrótalos para que podamos volver a vivir en paz!",
		},
		["The Possessed Crows"] = {
			NAME = "Los cuervos poseídos",
			DESCRIPTION = "Nuestros campos están siendo devastados por los cuervos. \nParece que están poseídos por fuerzas oscuras. \nDesgraciadamente, no creo que haya esperanza para ellos. \nPor favor, deshágase de ellos, de lo contrario mi familia morirá de hambre.",
		},
		["Colors of the Rainbow"] = {
			NAME = "Los colores del arco iris",
			DESCRIPTION = "Las criaturas de la sombra del inframundo han robado los deslumbrantes colores del Guardián de la Luz.\nViaja al inframundo, recoge una gema de cada color del arco iris. \nCuando las seis gemas diferentes estén en tus bolsillos, me las llevaré y consideraré la búsqueda completada. \nAyúdame a unir todos los colores del arco iris.",
			COUNTER = "Diferentes gemas encontradas",
			HOVER = "Sostener una gema roja, azul, púrpura, verde, amarilla y naranja",
		},
		["Bright Worshipnight"] = {
			NAME = "Noche de adoración brillante",
			DESCRIPTION = "La noche sagrada de la adoración de Glommer se acerca y no puede tener lugar sin los accesorios asociados. \nLucha contra los cerdos, consigue la flor de Glommer y 10 luciérnagas y encuentra la caja de madera sagrada que te proporcionaré cerca de la estatua de Glommer en la noche de luna llena.",
			COUNTER = "Tiempos adorados Glommer",
			HOVER = "Predicar a Glommer",
		},
		["Mirror of Merms"] = {
			NAME = "Espejo de Merms",
			DESCRIPTION = "¡La vida en el pantano está al revés! \nLos hombres del pantano han empezado a emitir gases cuando son atacados.\n Si se inhalan, el mundo empieza a girar. \nMata a %s hombres del pantano para evitar que esta mutación se transmita.",
		},
		["Giving back to Nature"] = {
			NAME = "Devolver a la naturaleza",
			DESCRIPTION = "La noche oscura parece amenazante, sobre todo por Charlie. \nPara una vida más despreocupada, pido a las luciérnagas que iluminen mi camino.",
			COUNTER = "Liberación de luciérnagas",
			HOVER = "Deja caer %s luciérnagas al suelo",
		},
		["A Crappy Day"] = {
			NAME = "Un día de mierda",
			DESCRIPTION = "Hoy he tenido un día de mierda, ¡quiero que alguien se sienta así de mal! \n¡Por favor ayúdame a terminar esta mierda!",
			COUNTER = "Tiempos que se cagan",
			HOVER = "Ser golpeado %s veces por caca lanzada",
		},
		["Revenge of the crapped victim"] = {
			NAME = "La venganza de la víctima cagada",
			DESCRIPTION = "Después de no poder quitarme la mierda de la ropa tras mi última visita a las ruinas, ¡quiero vengarme de estas criaturas! \n¡Que roben la flema de un Ewecus para mostrarles lo que significa el verdadero asco!",
			COUNTER = "Flema robada",
			HOVER = "Que los monos roben 1 flema",
		},
		["Luminous globules"] = {
			NAME = "Glóbulos luminosos",
			DESCRIPTION = "Soy un defensor de la medicina natural desde hace mucho tiempo. Según mis investigaciones, las bombillas han demostrado ser muy prometedoras en términos de curación. \nExperimenta los efectos curativos por ti mismo e informa de los resultados.",
			COUNTER = "Curado con bombillas",
			HOVER = "Cura %s Salud comiendo Bombillas",
		},
		["Beary Hunger"] = {
			NAME = "Hambre de Oso",
			DESCRIPTION = "Por favor, ayúdame, estoy al borde de la inanición porque los pavos se están comiendo todas mis bayas. \nMata a dos de estas bestias y compartiré mis bayas contigo.",
		},
		Wetlands = {
			NAME = "Humedales",
			DESCRIPTION = "Es tan agradable estar mojado, ¿no quieres estarlo así? \n¿Puedes conseguir estar mojado al 50%% durante un total de %s segundos?",
			COUNTER = "Segundos húmedos",
			HOVER = "Permanece con una humedad mínima del 50%% durante %s segundos",
		},
		["Off to sea"] = {
			NAME = "En el mar",
			DESCRIPTION = "¡Ah, marineros de agua dulce! \nSi quieres zarpar con nosotros, primero debes tener todos los materiales para un barco listos en tu inventario.",
			COUNTER = "Materiales",
			HOVER = "Ten un kit de barco, un remo, un mástil, un volante y un ancla en tu inventario",
		},
		["Hidden Treasures"] = {
			NAME = "Tesoros ocultos",
			DESCRIPTION = "Se dice que en las profundidades del mar hay tesoros que nadie ha visto todavía. \nSi pescas %s de estos tesoros, ¡serás recompensado!",
			COUNTER = "Tesoros",
			HOVER = "Utiliza el cabrestante para elevar %s salvables submarinos",
		},
		["Off to donate blood"] = {
			NAME = "A donar sangre",
			DESCRIPTION = "¡Las reservas de sangre son escasas! Nosotros, los cerdos, incluso buscamos sangre humana para reponer nuestras reservas. \n¡Con gusto se puede aplicar en cualquier momento!",
			COUNTER = "Veces dona sangre",
			HOVER = "Ser atacado %s veces por los mosquitos",
		},
		["The Lonely Woven Shadow"] = {
			NAME = "La sombra solitaria tejida",
			DESCRIPTION = "¡El Antiguo Tejedor de Combustible ha dejado a esta pobre Sombra Tejida a su suerte! \nAlgunos monstruos quieren vengarse del Antiguo Tejedor de Combustible y han decidido atacarlo, ¡por favor, defiéndelo!",
			COUNTER = "Ondas de ataque",
			HOVER = "¡Protege la sombra tejida!",
		},
		["The Eye of Cthulhu"] = {
			NAME = "El ojo de Cthulhu",
			DESCRIPTION = "¡Mi ojo me ha abandonado una vez más! ¡Se niega a venir a mí! \nComo actualmente estoy muy ocupado, me gustaría contratar a un aventurero para derrotarlo y que mi ojo vuelva a mí.",
		},
		["The Biggest Veggy"] = {
			NAME = "La %s más grande",
			DESCRIPTION = "¿Quién tiene la %s más grande? \nQuiero organizar un concurso. \nSi consigues cultivar una %s que tenga un peso superior a %s, el récord actual, ¡ganarás un precio especial!",
			COUNTER = "%s",
			HOVER = "¡Recoge una %s con un peso de más de %s!",
		},
		["A Sailor's Life"] = {
			NAME = "La vida de un marinero",
			DESCRIPTION = "Como un verdadero marinero, te quedas en el barco todo el tiempo que puedas!\nSi nos demuestras que eres uno de los nuestros, te daremos la bienvenida con un pequeño regalo!",
			COUNTER = "Segundos en el barco",
			HOVER = "¡Permanezca %s segundos en un barco de una vez sin abandonarlo!",
		},
		["Survival: Famine"] = {
			NAME = "Supervivencia: hambruna %s",
			DESCRIPTION = "Estudia el capítulo 1, „Hambre“, del manual oficial „Técnicas de supervivencia“ de nuestra colección de libros. Muévete de hambre hasta el límite del dolor y comprueba la eficacia de este libro de referencia en tu propio cuerpo. No te preocupes que después se te proporcionará una reparación adecuada...\n\n~ La Agencia Quest ~",
			COUNTER = "Daños por hambre",
			HOVER = "Recibir %s de daño al morir de hambre",
		},
		["Survival: Heart attack"] = {
			NAME = "Supervivencia: Ataque al corazón %s",
			DESCRIPTION = "Estudia el capítulo 2 „Ataque al corazón“ del manual oficial „Técnicas de supervivencia“ de nuestra colección de libros. ¡Llévate al borde de la locura y comprueba los valiosos consejos de nuestra guía paso a paso! Como recompensa, ¡también recibirás helado de nueces para compensar!\n\n~ La Agencia Quest ~",
			COUNTER = "Daños recibidos",
			HOVER = "Recibe %s de daño por un pico de terror",
		},
		["Survival: Frost Shock"] = {
			NAME = "Supervivencia: Choque de Escarcha %s",
			DESCRIPTION = "Estudia el capítulo 3 „Choque de escarcha“ del manual oficial „Técnicas de supervivencia“ de nuestra colección de libros. ¡Soporta los vientos helados y los miembros temblorosos y comprueba si puedes mantener el calor en una fila con la ayuda del libro! Si completas con éxito su tarea, ¡también recibirás algo caliente para comer como agradecimiento! \n\n~ La Agencia Quest ~",
			COUNTER = "Daños por congelación",
			HOVER = "Recibe %s de daño por congelación",
		},
		["Survival: Heat exhaustion"] = {
			NAME = "Supervivencia: agotamiento por calor %s",
			DESCRIPTION = "Estudia el capítulo 4, „Golpe de calor“, del manual oficial „Técnicas de supervivencia“ de nuestra colección de libros. ¡Manténgase en el calor abrasador y sudoroso y compruebe la eficacia de las medidas para reducir el sudor que se encuentran entre las páginas de este capítulo! Además, ¡te aseguramos una comida fresca después para refrescarte! \n\n~ La Agencia Quest ~.",
			COUNTER = "Daños por sobrecalentamiento",
			HOVER = "Recibe %s de daño por sobrecalentamiento",
		},
		["Survival: Life-threatening"] = {
			NAME = "Supervivencia: riesgo de muerte %s",
			DESCRIPTION = "Estudia el capítulo 5 „Peligro de muerte“ del manual oficial „Técnicas de supervivencia“ de nuestra colección de libros. ¡Intenta estar lo más cerca posible de la muerte desangrándote por la buena causa y comprueba si puedes utilizar los trucos sugeridos en el libro para salir de esta situación de peligro de muerte! Para que vuelvas a la pista, ¡el maestro panadero local también te tiene reservada una sorpresa como recompensa!\n\n ~ La Agencia Quest ~",
			COUNTER = "Experiencia cercana a la muerte",
			HOVER = "Tener menos de %s de salud",
		},
		["The True Enemy"] = {
			NAME = "El verdadero enemigo",
			DESCRIPTION = "Un terror siniestro planea en sus alas por la tierra y su nombre es Glommer... Muchos no son conscientes del peligro que trae consigo este malvado viajero y, por tanto, ignoran el peligro pendiente. Esta amenaza sólo puede ser detenida si tomamos medidas preventivas contra ti con toda la fuerza. ¡Salva al mundo de este engendro asesino y destruye al verdadero enemigo de todos nosotros!\n\n~ La Agencia Quest ~",
		},
		["Treebeard's end"] = {
			NAME = "El fin de Barba de Árbol",
			DESCRIPTION = "Los árboles vagan por el bosque y no causan más que problemas en nuestros esfuerzos de adquisición de leña. Interfieren en nuestras operaciones de albholz y ahuyentan a todos los que se acercan al bosque. Da ejemplo cortando una de estas barbas de árbol con un hacha. \n\n~ La Agencia Quest ~",
			COUNTER = "Guardia del árbol",
			HOVER = "Mata a 1 guardia del árbol con un hacha",
		},
		["Feeding Time"] = {
			NAME = "Hora de comer",
			DESCRIPTION = "¡Mantén a tus compañeros de equipo con vida a toda costa! Salva a uno de tus compañeros metiéndole comida en la boca con el mayor hambre. ¡Esto promueve la camaradería y envía una fuerte señal sobre su espíritu de equipo!\n\n~ La Agencia Quest ~",
			COUNTER = "Jugador Fed",
			HOVER = "Alimentar a 1 jugador cuando pierda salud por hambre",
		},
		["Catch the stick"] = {
			NAME = "Atrapa el palo",
			DESCRIPTION = "Nuestros científicos del comportamiento han hecho la suposición de que los perros del lugar también reaccionan al „lanzamiento de palos“ como los perros normales. ¡Ponga a prueba esta apasionante tesis intentando estimular a uno de los perros de este mundo con un palo! \n\n~ La Agencia Quest ~",
			COUNTER = "Palos lanzados",
			HOVER = "Lanza un bumerán %s veces a un sabueso",
		},
		["Front Pigs"] = {
			NAME = "Cerdos delanteros",
			DESCRIPTION = "La guerra está en el aire. Necesitamos cerdos de primera línea capaces de defenderse para repeler a los agresores de todo tipo y proteger nuestros intereses. Pero, por desgracia, nuestras ofertas de trabajo no parecen llegar a ninguno de los luchadores por la libertad locales. Ponte en contacto con ellos personalmente y convence a los locales para que les sigan a la batalla. ¡Poco después te ascenderemos a general de los cerdos!\n\n~ La Agencia Quest ~",
			COUNTER = "Seguidores del cerdo",
			HOVER = "Recluta %s cerdos para que luchen a tu lado.",
		},
		["Detective Work"] = {
			NAME = "Trabajo de detective",
			DESCRIPTION = "Estoy buscando a alguien que tenga experiencia en la lectura de pistas.\nHay unas criaturas que andan por aquí, pero parece que nunca las encuentro. \nSi eres capaz de localizar a 3 de ellas, te recompensaré.",
			COUNTER = "Seguimiento de los montones de basura",
			HOVER = "Rastrea 3 Dirtpiles hasta que encuentres la criatura a la que perteneceno",
		},
		["Twins Of Destruction"] = {
			NAME = "Gemelos de la Destrucción",
			DESCRIPTION = "Parece que ha habido una grieta dimensional que ha traído a este mundo criaturas que no deberían estar aquí.",
			COUNTER = "Los gemelos del terror",
			HOVER = "Derrota a los dos Gemelos del Terror",
		},
		["The Biggest Frog"] = {
			NAME = "La rana más grande",
			DESCRIPTION = "He oído que hay una rana en las cuevas que es tan grande que podría tragarse a una persona entera. \nTengo una fuerte fobia a las ranas, desafortunadamente.",
		},
		["Ho Ho Ho"] = {
			NAME = "Ho Ho Ho",
			DESCRIPTION = "Parece que hay un impostor entre nosotros, Santa... \nEn este mundo, Santa no distribuye los regalos que recibe de la Asociación de Santa y los acapara para sí mismo. \nPor favor, derrótalo para que este mundo también pueda experimentar las alegrías de la Navidad.",
		},
		["The Impregnable Fortress"] = {
			NAME = "La fortaleza inexpugnable",
			DESCRIPTION = "Hay una fortaleza en el mar que parece inexpugnable. \nEstá custodiada (¿o es la propia fortaleza?) por un monstruo tan grande que no te lo creerías. \nSi derrotas a este monstruo, te recompensaremos en consecuencia.",
		},
		["The Master Chef"] = {
			NAME = "El maestro de cocina",
			DESCRIPTION = "Me gustaría mucho probar una Cena Wobster, pero los ingredientes son tan difíciles de conseguir que soy incapaz de hacerlo! \nSi pudieras cocinar este plato y dármelo, te recompensaré!",
			COUNTER = "Cenas de Wobster cocinadas",
			HOVER = "Cocinar %s cena de Wobster",
		},
		["Destroyer of Ancient Works"] = {
			NAME = "Destructor de obras antiguas",
			DESCRIPTION = "Los Siguientes de Glommer no quieren ninguna otra mención de las antiguas civilizaciones en este mundo, esto hace que sea más difícil reclutar seguidores.\n¡Destruye los restos de las antiguas civilizaciones con un martillo y no dejes ningún rastro!",
			COUNTER = "Estaciones antiguas destruidas",
			HOVER = "Destruye %s estaciones de pseudociencia antigua llenas/rotas con un martillo",
		},
		["The Goodest Boy"] = {
			NAME = "The Goodest Boy",
			DESCRIPTION = "¿Quién es el chico más bueno? Sí, eres tú, Houndius Shootius. \nSiempre te ocupas de los perros malos que me atacan. \nPero, por desgracia, Houndius Shootius se siente solo porque no tiene amigos. \nPor favor, construye %s más como él para que tenga algunos amigos con los que jugar.",
			COUNTER = "Houndius Shootius construido",
			HOVER = "Despliega %s Houndius Shootius",
		},
		["The RPG Expert"] = {
			NAME = "The RPG Expert",
			DESCRIPTION = "Necesito la ayuda de un jugador profesional de RPG. \nNo consigo subir de nivel de forma rápida y eficaz. \nSi puedes demostrarme que sabes lo que haces y cómo lo haces, te recompensaré.",
			COUNTER = "Niveles obtenidos",
			HOVER = "Gana %s niveles en el registro de misiones",
		},
		["The Questing Adventurer"] = {
			NAME = "The Questing Adventurer",
			DESCRIPTION = "Las misiones son cada vez más numerosas y no hay suficiente gente para hacerlas! Por eso ofrecemos ahora un incentivo para completar las misiones.\n¡Sólo contarán las misiones que se hayan terminado cuando esta búsqueda estaba activa! \n¡Completa 10 misiones y obtendrás una recompensa especial!",
			COUNTER = "Misiones completadas",
			HOVER = "Completa %s misiones",
		},
		["Night Angler"] = {
			NAME = "Pescador nocturno",
			DESCRIPTION = "Tenemos la sospecha de que los bancos de peces locales han cambiado su comportamiento últimamente. ¡Comprueba si los peces de estas aguas siguen picando por la noche! \n\n ~ La Agencia Quest ~",
			COUNTER = "Peces capturados",
			HOVER = "Captura %s peces en una noche",
		},
		["Comrade Pig"] = {
			NAME = "Camarada Cerdo",
			DESCRIPTION = "Hasta ahora, no se sabe mucho sobre cómo reaccionan los cerdos al consumo excesivo de carne de monstruo. Por lo tanto, alimenta con una gran cantidad de carne de monstruo a 3 especímenes diferentes y documenta cómo reaccionan a ella. Esperamos sus resultados antes de mañana por la mañana.\n\n ~ La Agencia Quest ~",
			COUNTER = "Pigs transformed",
			HOVER = "Turn 3 pigs into a Werepig",
		},
		Kingfisher = {
			NAME = "Kingfisher",
			DESCRIPTION = "La mayoría de las aves conocidas emigran al sur al comienzo del invierno y no regresan hasta la primavera, cuando hace más calor. Una excepción son las aves grandes, que deben desafiar permanentemente las condiciones climáticas del invierno. Para comprobar este hecho, queremos que congeles y descongeles %s aves grandes diferentes. Informa de cómo soportan las aves el frío.\n\n ~ La Agencia Quest ~",
			COUNTER = "Tallbirds congelados",
			HOVER = "Congelar %s Tallbirds",
		},
		["The Mad Hatter"] = {
			NAME = "El Sombrerero Loco",
			DESCRIPTION = "Por desgracia, nuestro mejor fabricante de sombreros ha desaparecido sin dejar rastro. Sin embargo, necesitamos urgentemente nuevos sombreros en este momento. Por eso te pedimos que diseñes una nueva colección de sombreros y nos la envíes. Te enviaremos una lista de los sombreros que necesitamos de ti. Como compensación, recibirás el antiguo sombrero de lluvia del sombrerero.\n\n ~ La Agencia Quest ~",
			COUNTER = "Sombreros hechos",
			HOVER = "Haz los siguientes sombreros: Sombrero de buey, sombrero de plumas, \nsombrero de lluvia y gorro de gato",
			MISSING = "Desaparecida:",
		},
		["Wrong Offering"] = {
			NAME = "Ofrenda equivocada",
			DESCRIPTION = "A veces es correcto sacrificar por una buena causa. Poner a prueba su voluntad de sacrificio con una ofrenda dolorosa. Asegúrese de que su fiel compañero Chester llega a un final inglorioso. Le asignaremos un Chester mejor después.\n\n ~ La Agencia Quest ~",
		},
		["Shadow World Manipulation"] = {
			NAME = "Manipulación del mundo de las sombras",
			DESCRIPTION = "Amplía tu base y ayúdanos a conzeguir los últimos descubrimientoz en la investigación de las zombras. Construya más manipuladorez de sombras para explorar el mundo de las zombras y realizar pruebas de campo innovadoraz. ¡Contamos con usted!\n\n ~ La Agencia Quezt ~",
			COUNTER = "Manipuladores de la sombra construidos",
			HOVER = "Construye 3 Manipuladores Shadown",
		},
		["Friends in the Shadow Realm"] = {
			NAME = "Amigos en el reino de las sombras",
			DESCRIPTION = "Debez ir más lejoz que nunca. Redoblaz tuz esfuerzoz en la investigación de las zombraz. ¡Todavía no haz entendido lo que significaz convertirze en uno con laz zombraz! Asegúrese de que todoz los jugadorez de su entorno participen también en la investigación de las zombras. ¡Abrid los ojos todos a la vez para echar un vistazo a los abismoz más profundoz! ¡No esperamoz nada más que lo mejor de ti!\n\n ~ La Agenzia Quezt ~",
			COUNTER = "Seconds",
			HOVER = "Todoz los jugadorez deben tener un valor de cordura inferior a 10 durante 66 zegundoz",
			HOVER1 = "Permanecer en un valor de cordura inferior a 10 durante 366 zegundoz",
		},
		["Your True Friends"] = {
			NAME = "Tus verdaderos amigos",
			DESCRIPTION = "Haz hecho tu trabajo muy bien, muy bien... Te pagaremoz muy bien. Zí, lo haremos. Mientraz estabaz haciendo zzo buena investigación para uz en la zhadowz pudimos encontrar a un viejo amigo tuyoz para una reunión. Está dezeando volver a verte lo antez pozible... Se muere por... zerá mejor que traigaz a todo tu grupo contigo... Oz recompenzaremoz a todos por el fruto de vueztro trabajo...\n\n ~ La AgenZia QuezZzt ~",
			COUNTER = "AmigoZ",
			HOVER = "Ve a la estatua de glommer para conocer a tus amigozzz...",
		},
		Spiderman = {
			NAME = "Spiderman",
			DESCRIPTION = "Necesito que alguien diezme la población de cerdos, pero sin que sepan que he sido yo. \nSi sabes cómo persuadir a algunas arañas para que maten a los cerdos por mí, eres la persona adecuada para esta misión. \n¡Tu dedicación no será olvidada!",
			COUNTER = "Cerdos",
			HOVER = "Mata a %s cerdos con arañas que te siguen",
		},
		["A Bunnys Job"] = {
			NAME = "Un trabajo de conejo",
			DESCRIPTION = "Los Bunnymans matan a los murciélagos, así es como ha sido siempre el mundo. \nEs su único propósito... \nPero recientemente, los Bunnymans a menudo no saben que tienen que matarlos. \nPor eso necesito a alguien que les enseñe cómo matar a los murciélagos.",
			COUNTER = "Murciélagos",
			HOVER = "Mata a %s murciélagos con Bunnymans que te siguen",
		},
		["Your Own Fault"] = {
			NAME = "Su propia culpa",
			DESCRIPTION = "Lo siento mucho MacTusks, pero es tu culpa...\nHas estado dándonos tus dardos cada vez que te matamos y ahora quiero que sientan el dolor que sentimos al ser golpeados por estos dardos. \n¡Maten a %s de ellos con un dardo explosivo de su elección!",
			COUNTER = "MacTusk",
			HOVER = "Mata a %s MacTusks con un dardo de tu elección",
		},
		["Death By Self"] = {
			NAME = "Muerte por sí mismo",
			DESCRIPTION = "Los cerdos parecen criaturas tontas, pero me gustaría investigar la cuestión: ¿Pueden entender situaciones complejas? \nPara ello, me gustaría que mataran a %s cerdos con un bate de jamón. \nSi entienden por qué esto es algo malo, ¡mi experimento será un éxito!",
			COUNTER = "Cerdos",
			HOVER = "Matar %s cerdos con un bate de jamón",
		},
		["The Inner Monster"] = {
			NAME = "El monstruo interior",
			DESCRIPTION = "En cada cerdo hay un monstruo interior que hace estragos...\nQuiero que lo liberes, ya que los cerdos no deberían vivir con miedo para dejar salir sus demonios interiores.\n¡Libera a %s cerdos de estas normas sociales convirtiéndolos en hombres-cerdo!",
			COUNTER = "Cerdos a Werepig",
			HOVER = "Convierte %s cerdos en Werepigs alimentándolos con algo",
		},
		["The Boxer"] = {
			NAME = "El boxeador",
			DESCRIPTION = "¡Si quieres ser el mejor, tienes que aprender del mejor! \n¡Y yo soy el mejor! Te ofrezco una sesión de entrenamiento personal conmigo mismo, ¡el campeón invicto de boxeo constante! \nEmpezaremos con lo básico, ¡haz %s de daño sólo con tus puños!",
			COUNTER = "Daño",
			HOVER = "Inflige %s de daño con tus puños",
		},
		["The Dish for the Pig"] = {
			NAME = "El plato para el cerdo",
			DESCRIPTION = "Incluso los cerdos como yo sienten la necesidad de darse un capricho.\nPor eso recompensaré a la persona que alimente a otro cerdo con una Cena Wobster.\nDe este modo, también entrarán en contacto con el mundo culinario.",
			COUNTER = "Cena de Wobster Fed",
			HOVER = "Alimentar a un cerdo con una cena Wobster",
		},
		["A Useful Companion"] = {
			NAME = "Un compañero útil",
			DESCRIPTION = "Los búfalos pueden parecer criaturas que no se preocupan por otros que no sean sus miembros de la manada, pero puedo asegurarles que no es así. \nQuiero mostrar al mundo que son compañeros encantadores que dan más de lo que reciben.\nMonta uno durante %s segundos para ver lo que quiero decir.",
			COUNTER = "Segundos montados",
			HOVER = "Monta un Beefalo durante %s segundos",
		},
		["Marble Trees?!"] = {
			NAME = "¡¿Árboles de mármol?!",
			DESCRIPTION = "Aparentemente es posible plantar granos de mármol para hacer crecer el mármol. Es algo que no tiene mucho sentido para mí...\nSi es cierto, debe haber algo que se me escapa... ¿Cómo obtienen la energía para crecer? \nPor favor, planta %s judías de mármol, ¡quiero verlas crecer para avanzar en mi investigación!",
			COUNTER = "Plantar árboles de mármol",
			HOVER = "Planta %s árboles de mármol",
		},
		["The Stonemason"] = {
			NAME = "El Cantero",
			DESCRIPTION = "El mármol es un material útil, aunque se dice que tiene vínculos con las sombras de este mundo. \nPor eso quiero a alguien que sepa fabricar equipo con mármol para que me enseñe a hacerlo. Enséñame a fabricar %s armaduras de mármol",
			COUNTER = "Armaduras de Mármol",
			HOVER = "Crea %s armaduras de mármol",
		},
		["The Shadow Plague"] = {
			NAME = "La Plaga de las Sombras",
			DESCRIPTION = "Estos últimos tiempos las criaturas de las sombras han sido una verdadera amenaza para nuestra población. \nNecesitamos ayuda para tener su número bajo control. \nTodo el mundo es bienvenido a ayudar a matar todas las criaturas de la sombra que quiera, ¡se dará una recompensa por las primeras %s!",
			COUNTER = "Criaturas de la sombra",
			HOVER = "Derrota a %s criaturas de la sombra",
		},
		["The Pieces of Downfall"] = {
			NAME = "Los pedazos de la caída",
			DESCRIPTION = "Parece que nuestra reciente purga ha despertado fuerzas que sería mejor dejar dormidas... \n¡Las Piezas de Sombra están casi despiertas! Si llegan a este punto, ¡el mundo estará condenado! \nSi puedes derrotarlas antes de que despierten del todo, ¡podrás salvarnos a todos! \nPara ello, tienes que construir sus correspondientes estatuas de mármol y destruirlas en luna llena",
			COUNTER = "Piezas de sombra",
			HOVER = "Construye una Figura de Mármol de Torre, Caballero y Alfil, \ndestrúyelas en Luna Llena y mata las Piezas de Sombra",
		},
		["The Ancient Craft"] = {
			NAME = "El Antiguo Oficio",
			DESCRIPTION = "Realmente algo de thulecite pero no soy lo suficientemente fuerte para sobrevivir en las ruinas... \nPor favor, si alguien todavía conoce el antiguo oficio de cómo construir thulecite a partir de fragmentos de thulecite, ¡hágalo!",
			COUNTER = "Thulecite crafteado",
			HOVER = "Artesanía %s Thulecite",
		},
		["The Shadow Slayer"] = {
			NAME = "El Cazador de Sombras",
			DESCRIPTION = "¡Estas sombras de pesadilla se han apoderado de las ruinas! Hay muchas durante el ciclo de pesadillas. \nNecesito que alguien mate algunas para poder viajar con seguridad hasta allí!",
			COUNTER = "Sombras Matadas",
			HOVER = "Mata a %s criaturas de la sombra durante el ciclo de pesadilla en las ruinas",
		},
		["Suicidal Thoughts"] = {
			NAME = "Pensamientos Suicidas",
			DESCRIPTION = "¡Una vez tuve un amigo que me dijo que fue capaz de sobrevivir a la explosión de una pila de 25 pólvoras! \nNi idea de cómo lo hizo y desde entonces murió por otra desafortunada explosión... \nSi eres capaz de sobrevivir a una explosión así, ¡muéstrame cómo lo hiciste!",
			COUNTER = "Sobrevive a la explosión",
			HOVER = "Sobrevive a la explosión de una pila de al menos 25 pólvoras",
		},
		["The Untalented Chef"] = {
			NAME = "El chef sin talento",
			DESCRIPTION = "¡Mi vida se ha acabado! ¡Me han echado de la escuela de cocina! \n¡Ése era mi mayor sueño! Sólo porque yo sólo era capaz de cocinar goop húmedo ... \nNecesito algo que me anime, que me muestre que no soy el único que cocina gulas húmedas",
			COUNTER = "Goop húmedo cocinado",
			HOVER = "Cocinar %s Goop húmedo",
		},
		["The Flower Lover"] = {
			NAME = "El amante de las flores",
			DESCRIPTION = "Me encantan las flores... ¡Probablemente por eso me llaman el Amante de las Flores! \nDeseo llenar este mundo de flores. \nAyúdame a realizar mi sueño plantando %s flores",
			COUNTER = "Flores plantadas",
			HOVER = "Planta %s flores",
		},
		["The Fish Fisher"] = {
			NAME = "El Pescador de %s",
			DESCRIPTION = "¡Necesito urgentemente un %s para un proyecto especial mío! \n¡Pero parece que no puedo atraparlos! \n ¡Si alguien pudiera traerme 5 de ellos, estaría muy agradecido!",
			COUNTER = "%s pescados",
			HOVER = "Pescado 2 %s",
		},
		["The Tormented Dust Moth"] = {
			NAME = "La polilla del polvo atormentada",
			DESCRIPTION = "¡Una polilla del polvo que conozco personalmente ha sido acosada durante bastante tiempo por fuertes criaturas! \n Quieren robar su thulecite que han estado trabajando en el cultivo durante mucho tiempo. \n¡Si ayudas a defenderlos, te recompensarán con un trozo de esta thulecite y lanzando un hechizo protector sobre ti!",
			COUNTER = "Polilla del Polvo protegida",
			HOVER = "Protege a la Polilla del Polvo de las criaturas que aparecen durante 5 oleadas",
		},
		["The Sleeping Beauty"] = {
			NAME = "La Bella Durmiente",
			DESCRIPTION = "¡Hora del sueño reparador! Con todo el trabajo que hay que hacer, es fácil agotarse. Cuídate y dale un respiro a tu cuerpo y a ti mismo",
			COUNTER = "Dormido por segundos",
			HOVER = "Duerme %s segundos en una tienda de campaña o similar",
		},
		["The Ocean Chose Me!"] = {
			NAME = "¡El océano me ha elegido!",
			DESCRIPTION = "Donde el océano se pierde flota un sonido, ¡me llama! ¿Está entonces lejos? ¿Estoy listo?\nEl océano te ha elegido para cosechar %s algas marinas. Así que únete y di \n ¡Me encantaría!",
			CONTADOR = "Cosechar las algas marinas",
			HOVER = "¡Cosecha los percebes de %s Algas Marinas con tus propias manos!",
			COUNTER = "Algas marinas recolectadas",
		},
		["The Seven Dwarfs"] = {
			NAME = "Los Siete Enanitos",
			DESCRIPTION = "¡Blancanieves necesita tu ayuda! ¡Tus amigos enanos han cavado demasiado profundo en su trabajo en la mina y han caído en la constante! Al hacerlo, se han convertido en figuras rígidas. Ayúdala a encontrarlos de nuevo y a entregarlos al Rey Cerdo para que los devuelva a su mundo!",
			CONTADOR = "Enanos",
			HOVER = "¡Entrega los siete enanos al Rey Cerdo!",
			COUNTER = "Enanos",
		},
		["The Cold Never Bothered Me Anyway!"] = {
			NAME = "¡El frío es ahora parte de mí!",
			DESCRIPTION = "¡Me estoy soltando! ¡Suelto ahora! Ya no hay hambre que me atormente, ni criaturas que me vuelvan loca, ¡y el frío ahora también forma parte de mí! Demuestra que tú, como Elsa, estás preparada para la libertad y que no te importa el frío, el hambre y la locura!",
			CONTADOR = "Segundos de despreocupación",
			HOVER = "Permanece hambriento, con frío y con menos de 10 de Cordura durante %s segundos",
			COUNTER = "Segundos sin preocupaciones",
		},
		["Kiss The Frog!"] = {
			NAME = "¡Besa a la rana!",
			DESCRIPTION = "A veces tienes que besar a muchas ranas hasta encontrar a tu príncipe. ¡Enfréntate a suficientes y te convertirás en un verdadero príncipe rana! Pero ten cuidado: ¡una rana rara vez viene sola!",
			COUNTER = "Ranas",
			HOVER = "¡Mata %s ranas para encontrar a tu príncipe!",
		},
		["The Dangerous Widow"] = {
			NAME = "La viuda peligrosa",
			DESCRIPTION = "Uno de los bosques de estas tierras ha estado bajo el control de una araña gigante durante mucho tiempo.",
		},
		["The Mad Adventurer"] = {
			NAME = "El aventurero loco",
			DESCRIPTION = "He oído que existe una criatura de las sombras tan aterradora y monstruosa, que nadie ha sobrevivido al encuentro con ella para contarlo.\n¡Si eres capaz de derrotar a una, te recompensaré!",
		},
		["The Scientist"] = {
			NAME = "El Científico",
			DESCRIPTION = "Necesito a alguien a quien le guste la ciencia tanto como a mí. \nConstruye 3 motores de alquimia para mostrar al mundo lo increíble que puede ser la ciencia.",
			COUNTER = "Motores de alquimia construidos",
			HOVER = "Construye 3 motores de alquimia",
		},
		["The Arsonist"] = {
			NAME = "El pirómano",
			DESCRIPTION = "La mayoría de mis amigos no quieren tener nada que ver conmigo, sólo porque a veces quiero prender fuego a algunas cosas. \nNo entienden lo hermoso que es el fuego... \n¡Demuéstrame que podemos ser amigos prendiendo fuego a 10 cosas!",
			COUNTER = "Incendios iniciados",
			HOVER = "Prende fuego a 10 cosas con un mechero",
		},
		["The Gravedigger"] = {
			NAME = "El sepulturero",
			DESCRIPTION = "En el inquietante silencio del cementerio, te adentrarás en lo desconocido mientras desentierras %s tumbas. Cuando la tierra ceda a tu pala, puede que descubras reliquias olvidadas, recuerdos perdidos o incluso antiguas maldiciones. Cada tumba encierra su propia historia, y tu curiosidad te guiará para desentrañar sus enigmáticos pasados.",
			COUNTER = "Graves",
			HOVER = "Desenterrar %s tumbas",
		},
		["I've got 99 problems but starving ain't one!"] = {
			NAME = "¡Tengo 99 problemas, pero morir de hambre no es uno de ellos!",
			DESCRIPTION = "Aunque la probabilidad en este mundo de morir de hambre es bastante alta, he oído que algunos de sus habitantes son bastante ricos en lo que a comida se refiere. ¡Demuéstrame que existen tales personas comiendo %s calorías de comida sin pasar hambre ni una sola vez!",
			COUNTER = "Calorías",
			HOVER = "Comer %s calorías de comida",
			FORFEIT = "Tengo 99 problemas, ¡pero morir de hambre era uno! No he podido completar la misión.",
		},
		["The Untouchable"] = {
			NAME = "El intocable",
			DESCRIPTION = "¿Puedes ser el Intocable? El Intocable es una entidad tan fuerte que no puede ser tocada por nada. ¡Demuéstrame si eres digno de este título no siendo afectado por ningún daño durante %s segundos!",
			COUNTER = "Segundos",
			HOVER = "Permanecer sin daños durante %s segundos",
		},
		["The Hunted Glommer"] = {
			NAME = "El Glommer cazado",
			DESCRIPTION = "¡Un pobre Glommer está siendo cazado por unos depredadores despiadados! Ayúdale a escapar, ¡al menos esta vez!",
			COUNTER = "Ondas de ataque",
			HOVER = "¡Protege al Glommer! ¡Glommer aparece después de 2-3 minutos!",
		},
		["The Stray Hutch"] = {
			NAME = "La conejera extraviada",
			DESCRIPTION = "¡Mi conejera se ha escapado! Si lo encuentras, por favor, ten cuidado con los peligros a los que puede enfrentarse. Parece que muchas criaturas quieren hacerle daño en cuanto lo ven.",
			COUNTER = "Ondas de ataque",
			HOVER = "¡Protege la conejera! ¡Hutch aparece después de 2-3 minutos!",
		},
		["The Healer"] = {
			NAME = "El Sanador",
			DESCRIPTION = "El miembro más importante de un grupo es el sanador. ¡Demuéstrame que eres capaz de proporcionar la curación necesaria para que merezca la pena ser protegido curando %s de salud!",
			COUNTER = "Salud curada",
			HOVER = "Cura %s de tu salud",
		},
		["The Attacker"] = {
			NAME = "El atacante",
			COUNTER = "Daño causado",
			HOVER = "Inflige %s de daño en un plazo de 30 segundos",
			DESCRIPTION = "El miembro más importante de una party es el atacante. ¡Demuéstrame que eres capaz de proporcionar el poder de ataque necesario para que merezca la pena ser defendido infligiendo %s en 30 segundos!",
		},
		["The Defender"] = {
			NAME = "El Defensor",
			DESCRIPTION = "El miembro más importante de un grupo es el defensor. ¡Demuéstrame que eres capaz de proporcionar el poder defensivo necesario para que valga la pena curarte!",
			COUNTER = "Daños detenidos",
			HOVER = "Impide que %s de daño te golpeen con armadura",
		},
		["Axe-swinging Competition"] = {
			NAME = "Concurso de lanzamiento de hachas",
			DESCRIPTION = "Estamos organizando una competición de hachas. Si crees que puedes hacerlo, ¡acepta esta misión! Tendrás que talar %s árboles en un tiempo de 3 minutos. La competición comenzará cuando hayas cortado el primer árbol.",
			COUNTER = "Árboles talados",
			HOVER = "Cortar %s árboles en 3 minutos",
		},
		["Pickaxe-swinging Competition"] = {
			NAME = "Concurso de piquetas",
			DESCRIPTION = "Estamos organizando una competición de lanzamiento de picos. Si crees que puedes hacerlo, ¡acepta esta misión! Tendrás que extraer %s rocas en un tiempo de 3 minutos. La competición comenzará cuando extraigas la primera roca.",
			COUNTER = "Rocas extraídas",
			HOVER = "Mine %s rocks in 3 minutes",
		},
		["Shovel-digging Competition"] = {
			NAME = "Concurso de excavación con pala",
			DESCRIPTION = "Celebramos un concurso de excavación con pala. Si crees que puedes hacerlo, ¡acepta esta misión! Tendrás que desenterrar %s de cosas en un tiempo de 3 minutos. La competición empezará cuando desentierres el primer objeto.",
			COUNTER = "Cosas desenterradas",
			HOVER = "Desenterrar %s cosas en 3 minutos",
		},
		["The Fatal Rose"] = {
			NAME = "La rosa fatal",
			DESCRIPTION = "Cuando era joven, una vez toqué una rosa y casi me muero. ¡Pero nadie me ha creído nunca que las rosas son criaturas malignas que incluso pueden matarte! Ayúdame a demostrarles que las rosas pueden matarte, si así lo desean...",
			COUNTER = "Muerte",
			HOVER = "Morir junto a una rosa",
		},
		["The Bird Predator"] = {
			NAME = "El depredador de aves",
			DESCRIPTION = "¡Los pájaros son sólo zánganos que Charlie ha enviado para observarnos! ¡Quiero que desaparezcan y para ello necesito un depredador de aves! ¡Muéstrame tu valía matando %s de pájaros rojos en los próximos 8 minutos!",
			COUNTER = "Redbirds",
			HOVER = "Mata %s pájaros rojos en los próximos 8 minutos",
		},
		["A Werepigs Worst Nightmare"] = {
			NAME = "La peor pesadilla de un hombre",
			DESCRIPTION = "Parece que hay un hombre-cerdo en las cuevas, tan grande que nadie se atreve a acercarse a él. Pero no deberíamos tener miedo de los simples hombres-cerdo. Por eso quiero que alguien le enseñe a este \"Werepig de pesadilla\" que los humanos son su peor pesadilla.",
		},
		["The Nightmare Trio"] = {
			NAME = "El Trío Pesadilla",
			DESCRIPTION = "Queremos extraer piedra pavorosa de las cuevas, pero, por desgracia, a los Ink Blights no les gusta. Ayúdanos a derrotarlos.",
			COUNTER = "Plagas de tinta",
			HOVER = "Mata a los 3 Ink Blights",
		},
		["The Acid Bath"] = {
			NAME = "El baño ácido",
			DESCRIPTION = "Quiero investigar cuánto ácido puede soportar una persona. Por eso estoy buscando voluntarios para esta investigación. Comenzaremos con %s segundos en la lluvia ácida de las cuevas, pero lo haremos sin protección, ¡de lo contrario la investigación será falsificada!",
			COUNTER = "Segundos",
			HOVER = "Resistir %s segundos en la lluvia ácida sin protección",
		},
		["A Great Ryft"] = {
			NAME = "Un gran Ryft",
			DESCRIPTION = "Los ryftals recién aparecidos parecen bastante interesantes, ¡quiero saber qué tipo de botín dan! Necesito que alguien mine %s de ellos para poder ver su contenido.",
			COUNTER = "Ryftals extraídos",
			HOVER = "Mine %s ryftals",
		},
		["A Grazers Nightmare"] = {
			NAME = "Una pesadilla para los ganaderos",
			DESCRIPTION = "Los pastores parecen proteger a los ryftals, ¡pero necesito investigarlos sin que me molesten! ¡Que alguien me ayude infligiéndoles %s de daño!",
			COUNTER = "Daño causado",
			HOVER = "Inflige %s de daño a los herbívoros",
		},
		["Closest To Oneself"] = {
			NAME = "Más cerca de sí mismo",
			DESCRIPTION = "Todo el mundo tiene un talento especial. Quiero que los cultives. Crea %s objetos que sólo tú puedas hacer y te daré una pequeña recompensa.",
			COUNTER = "Manualidades específicas de cada personaje",
			HOVER = "Craft %s objetos específicos del personaje",
		},
		["Kill The Lord"] = {
			NAME = "Matar al Señor",
			DESCRIPTION = "Aunque el Señor Mosca de la Fruta ha vigilado nuestra aldea durante algún tiempo, ha empezado a atacar a nuestros granjeros y ganado recientemente. Por lo tanto, sólo tenemos una opción, ¡muerte al Señor! Desafortunadamente no somos lo suficientemente fuertes, ¡por favor ayúdanos!",
		},
		["Kill The Innocent"] = {
			NAME = "Matar al inocente",
			DESCRIPTION = "Los Mossling son tan inocentes cuando su madre está con ellos, pero se convierten en monstruos cuando ella se va. Por desgracia, su carne ya no sabe tan bien cuando se enfadan... ¡Necesito a alguien que mate a %s inocentes mosslings para disfrutar del placer de una carne deliciosa!",
			COUNTER = "Inocentes musgos",
			HOVER = "Mata %s musgos que no estén enfurecidos",
		},
		["Defeating Rocky"] = {
			NAME = "Derrotar a Rocky",
			DESCRIPTION = "Mi antiguo mejor amigo Rocky, una langosta de roca, me ha traicionado horriblemente. Quiero devolvérsela matando a uno de sus hermanos. De esta manera tal vez pueda sentir un poco del dolor que me causó.",
		},
		["I'm The Pirate Now!"] = {
			NAME = "¡Ahora soy el pirata!",
			DESCRIPTION = "Jajaja Últimamente, los piratas recorren las costas con más frecuencia. ¡Demuéstrales que los papeles pueden cambiar rápidamente a nuestro favor!",
		},
		["Cannon Fodder"] = {
			NAME = "Carne de cañón",
			DESCRIPTION = "¿Eres carne de cañón o quieres tomar cartas en el asunto? ¡Demuéstrame que no eres carne de cañón desplegando %s cañones!",
			COUNTER = "Cañones desplegados",
			HOVER = "Desplegar %s cañones",
		},
		["Let's Get The Party Started!"] = {
			NAME = "¡Que empiece la fiesta!",
			DESCRIPTION = "Ha pasado algún tiempo desde que celebré mi última fiesta de verdad, en realidad desde que llegué a Constant. ¡Pero esto está cambiando ahora! Necesito gente que quiera festejar conmigo, pero tienen que traer sus propias bebidas, al menos %s. Puede ser un Zumo de Plátano, un Aguijón Vegetal o un Daiquiri de Plátano Congelado.",
			COUNTER = "Cócteles consumidos",
			HOVER = "Coma %s de zumo de plátano, aguijón de verdura o daiquiri de plátano congelado.",
		},
		["Return To Monke"] = {
			NAME = "Volver a Monke",
			DESCRIPTION = "El mundo moderno ya no tiene sitio para nosotros, los humanos. Por eso propongo que rechacemos la humanidad y volvamos a ser monos. ¿Quieres unirte a nosotros?",
			COUNTER = "De vuelta a Monke",
			HOVER = "Transfórmate en Wonkey, ¡vuelve a ser mono!",
		},
		["The Punching Bag"] = {
			NAME = "El saco de boxeo",
			DESCRIPTION = "Me considero el más fuerte de este mundo. ¡Soy tan fuerte que fui capaz de alcanzar un valor de %s cuando usaba los sacos de boxeo! ¡Te reto a que me muestres un valor más alto!",
			COUNTER = "Daño máximo al saco de boxeo",
			HOVER = "Haz más de %s de daño a un saco de boxeo de un solo golpe",
		},
		["The Shadowcrafter"] = {
			NAME = "El Artesano de las Sombras",
			DESCRIPTION = "Los oficios de las sombras son difíciles de aprender y aún más difíciles de dominar... \nSi eres capaz de demostrarme que has fabricado %s objetos de artesanía de las sombras, ¡te recompensaré con poderes oscuros!",
			COUNTER = "Objetos de Shadowcraft fabricados",
			HOVER = "Crea %s objetos de artesanía de las sombras con el zócalo de artesanía de las sombras",
		},
		["Strong Stomach"] = {
			NAME = "Estómago fuerte",
			DESCRIPTION = "¿Tienes lo que hay que tener para sobrevivir en la naturaleza? Una necesidad es tener un estómago fuerte, ya que mucha comida empezará a pudrirse cuando llegues a ella. Considéralo como un entrenamiento para tu estómago comer %s podridos.",
			COUNTER = "Pudrición comido",
			HOVER = "Come %s Rot. No lo pienses, sólo cómetelo...",
		},
		["Dreadful Constructor"] = {
			NAME = "Constructor temible",
			DESCRIPTION = "Las cuevas parecen un poco inestables últimamente, ya que se han producido muchos terremotos. Nuestros pilares de apoyo hechos de piedra no son capaces de absorber estas sacudidas, por lo que necesito algún material más fuerte, como dreadstone. ¡Ayúdanos construyendo %s pilares llenos de dreadstone para que nuestra base en las cuevas esté segura!",
			COUNTER = "Pilares de piedra de terror construidos",
			HOVER = "Construir %s pilares de dreadstone llenos",
		},
		["Poor Doggies"] = {
			NAME = "Pobres perritos",
			DESCRIPTION = "Pobres perritos, dijo mi madre. Sólo digo que se lo merecían. Estos sabuesos buscan humanos y los atacan, ¡puedes llamarlos pobres! ¡Si vences a %s de ellos, te daré un perrito realmente bueno!",
			COUNTER = "Sabuesos muertos",
			HOVER = "Mata %s de sabuesos, sabuesos de fuego o sabuesos de hielo",
		},
		["The Queen Slayer"] = {
			NAME = "La Reina Cazadora",
			DESCRIPTION = "¡Las reinas araña se han vuelto demasiado poderosas! Necesito a alguien lo suficientemente fuerte como para matar a %s de ellas, ¡para que nuestra aldea de cerdos pueda seguir viviendo en paz!",
		},
		["Whac-A-Mole"] = {
			NAME = "Whac-A-Mole",
			DESCRIPTION = "He oído hablar de este juego llamado Whac-A-Mole de fuera de la Constant. He intentado jugarlo pero me parece imposible, nunca soy capaz de acertar a un topo. ¡Demuéstrame que es posible matando %s topos!",
		},
		["Running Like Clockwork"] = {
			NAME = "Funcionar como un reloj",
			DESCRIPTION = "Estoy perplejo sobre cómo estos mecanismos de relojería siguen funcionando sin problemas a pesar de que no hay nadie que los mantenga. Necesito que destruyas %s de ellos para poder entender mejor cómo funcionan.",
			COUNTER = "Mecanismos de relojería destruidos",
			HOVER = "Destruir %s mecanismos de relojería",
		},
		["A Friend of Bunnymans"] = {
			NAME = "Un amigo de Bunnymans",
			DESCRIPTION = "Los Bunnymans son criaturas realmente dulces que pueden parecer un poco groseras al principio, pero tienen un corazón de oro. Pruébalo dando %s zanahorias a Bunnymans",
			COUNTER = "Zanahorias alimentadas",
			HOVER = "Alimenta %s zanahorias a Bunnymans",
		},
		Firestarter = {
			NAME = "Firestarter",
			DESCRIPTION = "He creado un prototipo de un nuevo tipo de cofre, capaz incluso de resistir los incendios más duros. Pero no he llegado a probarlo, así que necesito a alguien que prenda fuego a %s cosas con una antorcha.",
			COUNTER = "Cosas iluminadas",
			HOVER = "Prende fuego a %s cosas con una antorcha",
		},
		["Squid Game"] = {
			NAME = "Juego del calamar",
			DESCRIPTION = "¡Quiero jugar a un juego contigo! ¡Mata %s calamares y te daré algo que te ayudará a mantenerlos frescos!",
		},
		["It's Wednesday my Dudes!"] = {
			NAME = "¡Es miércoles, amigos!",
			DESCRIPTION = "¿Necesito decir más? ¡Celébralo liberando %s ranas de la constante!",
		},
		["The Archive Guardian"] = {
			NAME = "Archivo Guardian",
			DESCRIPTION = "El Archivo Antiguo está lleno de centinelas antiguos y no me dejan investigar en paz. ¡Ayúdame a mantenerlos a raya con tus ataques infligiendo %s de daño!",
			COUNTER = "Daños",
			HOVER = "Inflige %s de daño a Centinelas Antiguos",
		},
		["Helmet Compulsory"] = {
			NAME = "Casco obligatorio",
			DESCRIPTION = "Queremos inculcar una nueva directriz: Lleva siempre el casco cuando circules bajo tierra. Pero la mayoría de la gente no nos cree, así que tenemos que mostrarles los resultados de no llevar casco. Para ello, los escombros de un terremoto te golpearán %s veces.",
			COUNTER = "Golpeado por escombros",
			HOVER = "Ser golpeado %s veces por los escombros de un terremoto",
		},
		["Good For Your Nerves"] = {
			NAME = "Bueno para los nervios",
			DESCRIPTION = "La mayoría de la gente hoy en día está más que estresada. Tómate un momento para relajarte bebiendo %s tés calmantes y verás cuánto te ayudan...",
			COUNTER = "Tés calmantes bebidos",
			HOVER = "Beber %s tés calmantes",
		},
		Nitroglycerin = {
			NAME = "Nitroglicerina",
			DESCRIPTION = "He oído que hay un mineral tan inestable y explosivo como la Nitroglicerina aquí en la Constante. Tiene algo que ver con el Glas Lunar, pero necesito muchos de ellos para poder analizar bien la estructura y replicar la versión inestable del mismo. ¡Ayúdame encontrando %s Moon Glas!",
			COUNTER = "Luna de cristal",
			HOVER = "Encuentra %s Glas lunares extrayendo rocas o similares",
		},
		["It's A Trap!"] = {
			NAME = "¡Es una trampa!",
			DESCRIPTION = "Quiero estudiar a los Guerreros Araña para saber cómo son mucho más fuertes e inteligentes que sus hermanos y hermanas. ¡Necesito que atrapes %s de ellos!",
			COUNTER = "Guerreros araña capturados",
			HOVER = "Atrapa %s guerreros araña con una trampa",
		},
		["The Monster Breeder"] = {
			NAME = "El criador de monstruos",
			DESCRIPTION = "Unos conocidos me han dicho que ahora los pájaros ponen huevos monstruosos si se les alimenta con carne monstruosa. Tengo muchas ganas de ver qué tipo de criatura saldrá de ellos, ¡necesitaré que crees %s de ellos!",
			COUNTER = "Huevos monstruosos",
			HOVER = "Producir %s de huevos monstruosos con aves en una jaula",
		},
		["The Ancient Curse"] = {
			NAME = "La antigua maldición",
			DESCRIPTION = "Según una leyenda, en lo más profundo de las ruinas de la antigua civilización, ¡vive uno de los seres de las sombras más poderosos! Necesito que lo encuentres y lo mates, ¡demuéstrame que no es sólo una leyenda!",
		},
		["Oh Sweet Summer Child"] = {
			NAME = "Oh Sweet Summer Child",
			DESCRIPTION = "¿Sigues con tu Cataplasma de Miel? ¿O ya formas parte de la pandilla guay con tu Envoltura de Flores Dulces? Vamos, ¡sé parte de los chicos guays y haz %s Sweetflower Wrap!",
			COUNTER = "Sweetflower Wrap hecho a mano",
			HOVER = "Craft %s Sweetflower Wrap",
		},
		["It's Raining!"] = {
			NAME = "¡Está lloviendo!",
			DESCRIPTION = "¡Está lloviendo! Al menos eso es lo que hubiera querido deciros, pero desgraciadamente ha pasado mucho tiempo desde la última lluvia. Necesito que alguien invoque la lluvia para nosotros, ya que es la única posibilidad que nos queda para que nuestros cultivos no se marchiten... ¡Necesito que la invoques al menos %s veces!",
			COUNTER = "Lluvia convocada",
			HOVER = "Invoca la lluvia con una caracola ahogadora %s veces",
		},
		["The Uncompromising Experience"] = {
			NAME = "La experiencia sin concesiones",
			DESCRIPTION = "¿Eres tan duro como crees? ¡Demuéstrame tu valía sobreviviendo %s días seguidos en el Constant sin morir!",
			COUNTER = "Días de supervivencia",
			HOVER = "Sobrevivir %s días a la vez",
		},
		["Watch This!"] = {
			NAME = "¡Mira esto!",
			DESCRIPTION = "He robado algunas gemas en el Bosque de los Cerezos y ahora los Vigilantes me atacan nada más verme. Pero tengo muchas ganas de pasear, ¡así que por favor mata a uno de ellos!",
		},
		["Mutated Queen"] = {
			NAME = "Reina mutante",
			DESCRIPTION = "¡La Reina Abeja ha perdido la cabeza! ¡Parece que el Bosque de los Cerezos ha provocado una mutación que la ha vuelto venenosa y mortal! ¡Necesito que alguien me ayude a deshacerme de ella!",
		},
		["A Reputable Person"] = {
			NAME = "Una persona reputada",
			DESCRIPTION = "El Bosque de los Cerezos y sus habitantes siempre te vigilan... ¡Da un paso en falso y tu reputación disminuirá! ¡Demuéstrame que puedes aumentar tu reputación hasta el número necesario!",
			COUNTER = "Reputación",
			HOVER = "Alcance %s Reputación forestal",
		},
		["It's Bugging Me!"] = {
			NAME = "Me está molestando",
			DESCRIPTION = "Me molesta no poder atrapar ningún bicho en el bosque de cerezos. Cada vez que creo que he cazado uno, ya está huyendo o volando... Si puedes ayudarme a atrapar algún bicho, ¡te lo agradecería mucho!",
			COUNTER = "Insectos capturados",
			HOVER = "Atrapar %s bichos con una red",
		},
		["The Pacifier"] = {
			NAME = "El chupete",
			DESCRIPTION = "El mundo tal y como lo conocemos está siempre en guerra. ¡Ya no lo soporto más! He oído que, de alguna manera, se puede construir un dispositivo que pacifique a las criaturas. ¡Puede ser una forma de traer la paz a este mundo!",
			COUNTER = "Chupetes construidos",
			HOVER = "Construir %s chupetes",
		},
		["Mischievous Thief"] = {
			NAME = "Ladrón travieso",
			DESCRIPTION = "He oído hablar de un ladrón que ha estado robando en Tallbirds. Quiero conocer a esta persona, pero necesito saber si es de fiar. ¡Demuéstrame que lo eres robando %s huevos de Tallbird!",
			COUNTER = "Robo de huevos de Tallbird",
			HOVER = "Robar %s huevos de Tallbird",
		},
		["People Pleaser"] = {
			NAME = "Complacer a la gente",
			DESCRIPTION = "Quiero hacer feliz a la gente. Pero para poder hacerlo, ¡necesito que más personas tengan pensamientos positivos! ¡Sé una de esas personas y muéstrame lo feliz que eres!",
			COUNTER = "Aura de cordura",
			HOVER = "Tener un Aura de Cordura de %s/min",
		},
		["The Hunt For Mutants"] = {
			NAME = "A la caza de mutantes",
			DESCRIPTION = "He oído hablar de mutantes gigantes que han estado aterrorizando a los pigmanos alrededor de las grietas lunares. Quiero darles caza, pero no soy lo bastante fuerte. ¡Ayúdame matando %s de ellos!",
			COUNTER = "Gigantes mutados muertos",
			HOVER = "Mata a %s gigantes mutantes (Deerclops de cristal, Bearger blindado o Varg poseído).",
		},
		["Praise The Pigking"] = {
			NAME = "Elogios al Pigking",
			DESCRIPTION = "¡El Rey Cerdo es la persona más generosa de Constant! Nos da mucho oro, ¡pero tenemos que alabarle por ello! ¡Demuéstrame que eres digno de su oro dándole tantos objetos que te dará %s de oro!",
			COUNTER = "Oro",
			HOVER = "Recibir %s oro del Pigking",
		},
		["Training Makes Perfect"] = {
			NAME = "La formación hace al maestro",
			DESCRIPTION = "Me estoy haciendo viejo y ya no necesito mi Howlitzer. Quiero dárselo a alguien que lo merezca. Demuéstrame tus habilidades a distancia infligiendo %s de daño con cerbatanas.",
			COUNTER = "Daños",
			HOVER = "Inflige %s de daño con cerbatanas",
		},
		["What Is Hunger?"] = {
			NAME = "¿Qué es el hambre?",
			DESCRIPTION = "La constante es un lugar duro, ¡pero he oído hablar de gente que ni siquiera sabe lo que es el hambre! ¡Demuéstrame que eres uno de ellos manteniéndote por encima del 80%% de hambre durante %s segundos!",
			COUNTER = "Segundos por encima del 80% de hambre",
			HOVER = "Permanecer %s segundos por encima del 80%% de hambre a la vez",
		},
		["Repairing The Past"] = {
			NAME = "Reparar el pasado",
			DESCRIPTION = "El pasado es algo que no podemos cambiar, ¡pero podemos repararlo! ¡Necesito a alguien que repare %s objetos con un %s!",
			COUNTER = "Artículos reparados",
			HOVER = "Reparar %s elementos con un %s",
		},
		["A Soul For A Soul"] = {
			NAME = "Un alma para un alma",
			DESCRIPTION = "Se dice que el alma de una persona persiste a pesar de los cambios físicos. ¡Quiero probar esta teoría! ¡Demuéstrame que eres digno de ello transformándote en otro personaje!",
			COUNTER = "Transformaciones",
			HOVER = "Cambia a otro personaje con un ídolo de roca lunar",
		},
		["Dancing With The Devil"] = {
			NAME = "Bailando con el diablo",
			DESCRIPTION = "El Diablo, también conocido como el Antiguo Tejedor de Combustible, es una criatura muy fuerte que lleva mucho tiempo aterrorizando las ruinas. Todos viven temiéndole, ¡pero no deberían tener miedo! ¡Necesito que alguien les muestre que el Diablo no es tan aterrador como creen bailando %s veces cerca de él!",
			COUNTER = "Bailes",
			HOVER = "Baila %s veces cerca del Antiguo Tejedor de Combustible",
		},
		["Hell's Guardian"] = {
			NAME = "Guardián del Infierno",
			DESCRIPTION = "La Libélula guarda la entrada al infierno, ¡pero yo quiero entrar! Necesito que alguien la derrote para poder entrar en la Piscina de Magma.",
		},
	},
	QUEST_FUNCTIONS = {
		SANITY_90 = "Mantente por encima del 90% de cordura durante x segundos a la vez.",
		SANITY_10 = "¡Mantente por debajo del 10% de Cordura durante x segundos a la vez!",
		LUNACY_10 = "¡Mantente por debajo del 10% de Lunático durante x segundos a la vez!",
		LUNACY_90 = "Mantente por encima del 90% de locura durante x segundos a la vez.",
		MONSTERLASAGNA = "Comer x Monterlasagna",
		SURFNTURF = "Comer x Surf'n'Turf",
		LOBSTERDINNER = "Comer x Cena Wobster",
		LEAFLOAF = "Comer x Pastel de carne con hojas",
		JELLYBEAN = "Comer x Gominolas",
		KOALEFIG_TRUNK = "Comer x Tronco relleno de higos",
		BARNACLESUSHI = "Comer x Nigiri de percebe",
		FOSSILS = "Encontrar x Fósiles por minería",
		GOLDNUGGETS = "Encuentra x Pepitas de Oro minando",
		REDGEM = "Encuentra x Gemas Rojas minando",
		BLUEGEM = "Encontrar x Gemas Azules minando",
		PURPLEGEM = "Encuentra x Gemas moradas minando",
		GREENGEM = "Encontrar x Gemas verdes minando",
		YELLOWGEM = "Encontrar x Gemas Amarillas minando",
		ORANGEGEM = "Encontrar x Gemas Naranjas minando",
		LIVINGLOG = "Encontrar x Troncos vivos picando",
		LIFEAMULET = "Encontrar x Amuletos de la vida cavando",
		GEARS = "Encontrar x Engranajes excavando",
		CHARLIE = "Ser golpeado x veces por Charlie",
		TRADES = "Negocia x veces con el Rey Cerdo",
		TRINKET_12 = "Intercambia x veces un Tentáculo Desecado con el Rey Cerdo",
		TRINKET_8 = "Intercambia x veces un Tapón de Goma Endurecido con el Rey Cerdo",
		TRINKET_24 = "Intercambia x veces un Tarro del Gato de la Suerte con el Rey Cerdo",
		TRINKET_26 = "Intercambia x veces una Copa de Patata con el Rey Cerdo",
		FISHING = "Captura x peces",
		ICEBREAM = "Captura x Helado",
		DEEPBASS = "Captura x Deep Bass",
		SPITTLEFISH = "Captura x Salivazo",
		SUNFISH = "Captura x Pez Sol abrasador",
		TUNA = "Captura x Bloomfin Tuna",
		FALLOUNDER = "Captura x Fallounder",
		CORNCOD = "Captura x Maíz Bacalao",
		TELEPORT = "Teletransportar x veces algo lejos",
		T_BEEFALO = "Teletransportar x Beefalo lejos",
		T_DEERCLOPS = "Teletransportar x Deerclops lejos",
		T_BEARGER = "Teletransportar x Bearger lejos",
		T_DRAGONFLY = "Teletransportar x Libélula",
		T_MOOSE = "Teletransportar x alce/alce lejos",
		MOONBASE = "Defiende x veces la Base Lunar",
		BUILD_BUFFER = "Recibir %s como construcción en buffer",
		KRAMPUS_SACK = "%s%% Probabilidad de Krampus Sack",
	},
	SCRAPBOOK = {
		NIGHTMARE_EYEBONE = "Invoca a Chester Pesadilla cuando se recoge. Chester Pesadilla seguirá al portador. Mientras Pesadilla Chester esté vivo, el ojo estará abierto.",
		FROGKING_P_CROWN = "Se puede recargar con ranas. Cuando lo lleves, las sirenas y las ranas serán tus amigas. Las ranas te ayudarán si te atacan.",
		FROGKING_SCEPTER = "Puede repostar con ranas. Puede lanzar un hechizo que engendrará un grano de rana solo alrededor del lanzador durante 60 segundos.",
		GLOMMERFUELMACHINE_ITEM = "Se puede repostar con nightmarefuel. Cuando se coloca, genera Glommerfuel oscuro.",
		GLOMMERFUELMACHINE = "Se puede repostar con nightmarefuel. Cuando se coloca, genera Glommerfuel oscuro.",
		BLACKGLOMMERFUEL = "Puede colocarse como trampa para los enemigos. Si nada se mueve a través de ella, se disolverá al cabo de 15 segundos. El enemigo hará un 40% menos de daño, recibirá un 20% más de daño y será un 40% más lento durante 10 segundos.",
		GLOMMER_LIGHTFLOWER = "Genera un total de 20 Glommer Fuel a lo largo del tiempo.",
		QUESTBOARD = "Se puede utilizar para obtener una nueva misión cada día. Si está activada, también puedes crear tus propias misiones aquí.",
		REQUEST_QUEST = "Cuando las leas, se añadirá una nueva misión a tu registro de misiones. También pueden aparecer en diferentes dificultades.",
		SHADOW_CREST = "Se puede repostar con combustible de pesadilla. Recibirás un 33% menos de daño de las entidades de sombra. Cuando la lleves puesta, podrás usar un ataque especial contra los enemigos.",
		SHADOW_MITRE = "Se puede repostar con combustible de pesadilla. Recibirás un 33% menos de daño de las entidades de sombra. Cuando la lleves puesta, dejarás murciélagos de sombra tras de ti si te golpean.",
		SHADOW_LANCE = "Se puede recargar con combustible de pesadilla. Hace un 50% más de daño a las entidades lunares y utiliza menos usos contra las entidades lunares.",
	},
}