return {
	NAMES = {
		QUESTBOARD = "任务板",
		REQUEST_QUEST = "要求",
		REQUEST_QUEST_VERY_EASY = "非常简单的请求",
		REQUEST_QUEST_EASY = "简单的请求",
		REQUEST_QUEST_NORMAL = "正常请求",
		REQUEST_QUEST_DIFFICULT = "硬请求",
		REQUEST_QUEST_VERY_DIFFICULT = "非常艰难的要求",
		REQUEST_QUEST_SPECIFIC = "要求",
		GLOMMERFUELMACHINE = "黑暗的Glommer燃料机",
		GLOMMER_LIGHTFLOWER = "Glommer的光之花",
		CHESTER_BOSS = "恶梦切斯特",
		NIGHTMARECHESTER = "噩梦般的切斯特",
		NIGHTMARECHESTER_EYEBONE = "梦魇切斯特的眼骨",
		GLOMMER_SMALL = "飓风 Glommer",
		GLOMMER_BOSS = "暴风雪 Glommer",
		BLACKGLOMMERFUEL = "黑暗的Glommerfuel",
		["ADDITIONAL QUEST SLOTS"] = "额外的任务老虎机",
		SHADOW_CREST = "影子山庄",
		SHADOW_MITRE = "影子密特",
		SHADOW_LANCE = "影子长矛",
		FROGKING = "蛙鸣",
		FROGKING_P_CROWN = "蛙人之冠",
		FROGKING_SCEPTER = "蛙人权杖",
		FROGKING_BEYBLADE = "钻石陀螺",
	},
	DESCRIBE = {
		QUESTBOARD = "我想我知道其中一些...",
		REQUEST_QUEST = "似乎有人在某处丢失了请求。对我好！",
		REQUEST_QUEST_VERY_EASY = "似乎有人在某处丢失了请求。对我好！",
		REQUEST_QUEST_EASY = "似乎有人在某处丢失了请求。对我好！",
		REQUEST_QUEST_NORMAL = "似乎有人在某处丢失了请求。对我好！",
		REQUEST_QUEST_DIFFICULT = "似乎有人在某处丢失了请求。对我好！",
		REQUEST_QUEST_VERY_DIFFICULT = "似乎有人在某处丢失了请求。对我好！",
		REQUEST_QUEST_SPECIFIC = "似乎有人在某处丢失了请求。对我好！",
		GLOMMERFUELMACHINE = "一个神把他的祝福带到了这个机器上！",
		GLOMMER_LIGHTFLOWER = "神的礼物！",
		CHESTER_BOSS = "我不应该那样做！我不应该那样做 。我不应该那样做！",
		NIGHTMARECHESTER = "他看起来有点恼火，但我认为他不是这个意思。",
		NIGHTMARECHESTER_EYEBONE = "连眼珠子都看起来很恼火！",
		GLOMMER_SMALL = "哦，他是如此的可爱和渺小...哦，上帝，为什么它要攻击我！",
		GLOMMER_BOSS = "他觉醒了，他是来杀我们的！",
		BLACKGLOMMERFUEL = "一种黑暗而粘稠的物质，可以用来困住其他怪物！",
		SHADOW_CREST = "让你的敌人在你的头上，有点恐怖，但这太好啦！",
		SHADOW_MITRE = "似乎它还有一些影子主教的影子...",
		SHADOW_LANCE = "看来是个嗜血的武器，尤其是对付月球上的敌人！",
		FROGKING = "这个人看起来很可怕！",
		FROGKING_P_CROWN = "一个能让所有青蛙都视你为国王的皇冠！",
		FROGKING_SCEPTER = "一根权杖，用铁拳统治它的臣民。",
		FROGKING_BEYBLADE = "最好不要被这个人打中！",
	},
	RECIPE_DESC = {
		QUESTBOARD = "开始追问！",
		REQUEST_QUEST = "我不认为我可以制作这个！",
		REQUEST_QUEST_VERY_EASY = "非常简单的请求",
		REQUEST_QUEST_EASY = "简单的请求",
		REQUEST_QUEST_NORMAL = "正常请求",
		REQUEST_QUEST_DIFFICULT = "硬请求",
		REQUEST_QUEST_VERY_DIFFICULT = "非常艰难的要求",
		REQUEST_QUEST_SPECIFIC = "要求",
		GLOMMERFUELMACHINE = "你不能制作虔诚的东西！",
		GLOMMER_LIGHTFLOWER = "你不能制作神圣的东西！",
	},
	ATTACKWAVES = {
		MISSION_FAILED = "任务失败...",
		MISSION_SUCCESS = "任务完成！",
		MISSION_OBJECTIVE = "我需要保护 %s！",
	},
	ACTIONS = {
		FIGHT_GLOMMER = "做个朋友？!",
		SHADOW_ROOK_ATTACK = "影子车攻击",
	},
	REQUEST_QUEST = {
		FULL_LOG = "我已经有了完整的任务日志！",
		QUEST_ADDED = "任务已添加！",
	},
	TALKING = {
		REWARDS = "我的战斗得到了奖励！",
	},
	REWARDS = {
		health = "健康奖金 为 x min",
		sanity = "理智奖励 为 x min",
		hunger = "饥饿奖励 为 x min",
		sanityaura = "萨尼提奥拉奖金 为 x min",
		hungerrate = "饥饿率为 x 分钟",
		healthrate = "每 10 秒生命值 x 分钟",
		damage = "伤害奖励 为 x min",
		damagereduction = "伤害减免奖励 为 x min",
		range = "范围奖励 为 x min",
		winterinsulation = "防寒保暖奖金 为 x min",
		summerinsulation = "夏季隔热奖金 为 x min",
		worker = "工作奖金 为 x min",
		sleeping = "睡眠奖励 为 x min",
		nightvision = "夜视 为 x min",
		speed = "速度奖励 为 x min",
		escapedeath = "逃脱死亡的次数为 x 分钟",
		planardamage = "平面伤害奖励 x 分钟",
		planardefense = "平面防御奖励 x 分钟",
		dodge = "闪避奖励冷却 x 分钟",
	},
	QUEST_BOARD = {
		QUEST_BOARD = "任务板",
		LOOK_FOR_QUESTS = "寻找新的任务",
		LOOK_FOR_QUESTS_ACCEPTED = "已接受新任务！",
		LOOK_FOR_QUESTS_MAX = "我有最大数量的任务！",
		OBTAIN_LEVEL_REWARDS = "获得等级奖励",
		CREATE_NEW_QUESTS = "创建新任务",
		IN_CAVES = "在山洞里是不可能的!",
		CLOSE = "关闭",
		NO_NAME = "无名",
		REWARDS = "奖励",
		ACCEPT_QUEST = "接受任务",
		ALREADY_ACCEPT_QUEST = "已接受新任务！",
		REWARD_LEVEL = "奖励等级",
		ACCEPTED_REWARDS = "已接受的等级奖励",
		LEVEL = "等级",
		REWARD1 = "奖励1",
		REWARD2 = "奖励2",
		REWARD3 = "奖励3",
		DIFFICULTY = "困难",
		VICTIM = "受害者",
		AMOUNT = "数量",
		AMOUNT_OF_KILLS = "击杀数量",
		POINTS = "积分",
		TITLE = "标题",
		WRITE_DESCRIPTION = "写说明",
		ADD_QUEST = "将任务添加到任务池",
		SAVE_DESCRIPTION = "保存说明",
		YES = "是的",
		NO = "不",
		ASK_ADD_QUEST = "您确定要将此任务添加到任务池中吗？",
		QUEST = "寻求",
		ADDED_SUCCESFULLY = "添加成功",
		QUEST_EXISTS = "同名任务已经存在。请选择另一个",
		NUMBERS = "数字",
		FOODS = "食品",
		ITEMS = "项目",
		REMOVE_QUEST = "从任务库中删除任务",
		ASK_REMOVE_QUEST = "应该删除任务\"%s\"吗？",
		MANAGE_QUESTS = "管理自定义任务",
		REQUIREMENTS = "要求",
		EDIT_QUEST = "编辑任务",
		ASK_OVERWRITE_QUEST = "你想把任务%s改为这个版本吗？该任务将从所有玩家的任务日志中删除！",
	},
	QUEST_LOG = {
		EMPTY_SLOT = "空任务槽",
		BUTTON = "打开任务日志",
		NO_NAME = "无名",
		DESCRIPTION = "描述",
		REWARDS = "奖励",
		NOT_DEFINED = "没有定义的",
		GET_REWARDS = "获得奖励！",
		RECEIVE_REWARDS = "获得任务奖励",
		FORFEIT_QUEST = "没收任务",
		QUEST_LOG = "任务日志",
		CLOSE = "关闭",
		PAGE_1 = "第一页任务",
		PAGE_2 = "第二页任务",
		PAGE_3 = "第三页任务",
		PAGE_4 = "第四页任务",
		PAGE_5 = "第五页的任务",
		PAGE_6 = "第六页的任务",
		SCOREBOARD = "记分牌",
		CURRENT_LEVEL = "当前水平",
		POINTS = "积分",
		LEVEL = "等级",
		YES = "是的",
		NO = "不",
		BOSSFIGHT = "Boss战!",
		COMPLETED_QUESTS = "已完成的任务",
		TOTAL_POINTS = "总积分",
		ASK_FORFEIT = "你确定要放弃这个任务吗？",
		SUCCESS = "成功完成！",
		HEALTHBONUS = "健康增加：",
		SANITYBONUS = "理智增加:",
		HUNGERBONUS = "饥饿增加:",
		SPEEDBONUS = "速度提升:",
		WINTERINSULATIONBONUS = "保温增加:",
		SUMMERINSULATIONBONUS = "隔热增加:",
		WORKMULTIPLIERBONUS = "工作乘数:",
		KILL = "杀人",
		PROGRESS = "进展",
		SHOW_BONUS = "显示奖金",
		CURR_RANK = "目前排名\n\n到下一个等级的积分: ",
		QUEST_LINE = "这个任务是一个任务线的一部分！",
	},
	TEMP_BONI = {
		HEALTH = " 健康",
		SANITY = " 智慧",
		HUNGER = " 饥饿",
		SANITYAURA = "/min 萨尼提奥拉",
		HUNGERRATE = "% 饥饿率",
		HEALTHRATE = " 每10秒健康值",
		DAMAGE = " 损害",
		DAMAGEREDUCTION = "% 减少伤害",
		RANGE = " 范围",
		WINTERINSULATION = " 冬季保温",
		SUMMERINSULATION = " 夏季保温",
		WORKER = "% 工作成效",
		SLEEPING = " 健康/精神每秒钟的睡眠增加",
		NIGHTVISION = "夜视仪",
		SPEED = " % 速度",
		ESCAPEDEATH = " 逃脱死亡的时代",
		PLANARDAMAGE = "平面损伤",
		PLANARDEFENSE = "平面防御",
		DODGE = "每 %s 秒闪避一次",
	},
	LOADING_TIPS = {
		request = "请求可以从被杀的生物中掉落。你也可以在配置选项中启用它们的制作功能！",
		questboard = "建立一个任务板，每天可以获得一个新的任务，如果启用，还可以创建自己的任务！",
		attackwaves = "需要保护一个生物的任务将在接受任务后的随机时间后开始。",
		bossfight = "老板的战斗可以从任务日志中开始。每次你的等级提高，你都有机会能够开始一场BOSS战! 如果你死了，你不会失去你的物品，但如果你赢了，会有奖励给你！",
		temporarybonus = "一些任务会给你一个临时的奖励作为回报。你会在屏幕的顶部看到哪些是活动的。博尼的最大数量是5，如果你得到更多，旧的将被删除。",
		quest_line = "有一些任务是任务线的一部分。在起始任务之后的任务将被自动添加，否则就无法得到。这些任务会有一个电灯泡。",
		levelupcomponent = "如果你启用了等级系统，你每获得一个等级就会变得更强。你通过完成任务和击败生物获得积分。奖励可以在左页的任务记录中看到。",
	},
	QUESTS = {
		["The Wicked Mist Fury"] = {
			NAME = "恶雾之怒",
			DESCRIPTION = "那些讨厌的海行者正在破坏水淹生物群落的避难所。\n请帮助我们摆脱它们，让我们在这个美丽的地方安息！",
		},
		["The Powerful Shadow from Below"] = {
			NAME = "来自下方的强大阴影",
			DESCRIPTION = "一出航，这些可怕的阴影就向我们袭来！\n我们不知道如何才能逃脱它们，更不用说如何打败它们了。\n如果有勇敢的冒险家能帮忙就好了！",
		},
		["The Reckoning of the Gestalt"] = {
			NAME = "格式塔的清算",
			DESCRIPTION = "格式塔渴望你的开悟！\n在月球岛上以超过 85%% 的开悟立即停留 %s 几秒钟就能收集到他们的祭品。",
			COUNTER = "秒",
			HOVER = "一次性保持在85%%以上的Lunatic状态%s秒!",
		},
		["The Corrupt Prophecy Revenge"] = {
			NAME = "腐败的预言复仇",
			DESCRIPTION = "一个曾经预言过的预言提到，对昆虫怪物的崇拜将为这片荒凉的土地带来和平与财富。\n但看看它把我们带到了哪里！只有我们身边的怪物，吃不饱，夜晚是最可怕的部分！\n作为对这个预言的报复，我们希望你消灭这个名叫格洛默的昆虫怪物！\n签名，猪王。",
		},
		["The Monstrous Delicacy"] = {
			NAME = "可怕的美味",
			DESCRIPTION = "一位知名厨师向我提供了一个看起来很美味的怪物千层面，但我想确保如果我尝试吃它不会杀死我！\n如果有人可以吃掉其中的五个来表明我的怀疑是没有根据的，我将相应地奖励他们！",
			COUNTER = "怪物千层面",
			HOVER = "吃%s个怪物面条",
		},
		["The Explorers End"] = {
			NAME = "探险家结束",
			DESCRIPTION = "某位科学家告诉我们，一种极其危险的生物在组装月球虹吸器后出现。\n它被称为天体冠军。\n我担心我的生命！\n请摧毁这个怪物，让世界和平！\n作为回报，我会接受奖励时复制您库存中的每件物品！\n（这不包括您背包中的物品！）",
		},
		["Within the Labyrinth"] = {
			NAME = "迷宫内",
			DESCRIPTION = "牛头怪，许多传说中的神话生物，出现在这个世界上！\n正如预言所说，它一直在迷宫中。\n请打败它，让我的孩子们可以再次在那里玩耍，他们真的只是让我紧张在家！",
		},
		["The Stone from Below"] = {
			NAME = "下面的石头",
			DESCRIPTION = "我想分析一些可以在这个世界上找到的化石。\n不幸的是，我无法在洞穴中挖掘它们，因为我不够强壮，无法在那里生存。\n如果有人可以帮助我，我会非常乐意感激的！",
			COUNTER = "化石",
			HOVER = "寻找%s个化石",
		},
		["Beyond the Charming Hamlet"] = {
			NAME = "超越迷人的哈姆雷特",
			DESCRIPTION = "这些猪人正在占领这个世界！\n它们以惊人的速度繁殖，到处都是粪便。\n请控制一下人口。",
		},
		["Corpses of the Swampy Badlands"] = {
			NAME = "沼泽荒地的尸体",
			DESCRIPTION = "很多冒险者为了完成这个任务已经死了，我希望你不要成为他们中的一员！\n我们需要从沼泽中消失的触须，这样我们才能平安地旅行。",
		},
		["The Bane of Lake Nen"] = {
			NAME = "嫩湖之祸",
			DESCRIPTION = "我们的 Nen 湖离你们的世界不远，有时，我们会遇到可怕的 Malbatross。\n它偷走了我们生存所需的所有鱼！\n求求你，打败这个怪物吧我们不必挨饿！",
		},
		["The Scorched Nightmare Amulet"] = {
			NAME = "焦灼梦魇护身符",
			DESCRIPTION = "我想看看你能活到什么程度！\n装备一个噩梦护身符，同时过热%s秒。\n但是你千万不要做这些事情一秒钟都不做，因为我赢了不接受！\n看看你能不能做到！",
			COUNTER = "燃烧的秒",
			HOVER = "一次性保持疯狂和过热的状态%s秒",
		},
		["The Fearful Trial"] = {
			NAME = "可怕的审判",
			DESCRIPTION = "我希望你在一年内摆脱所有大型季节性 Boss。\n意思是：\n秋天 = 熊\n冬天 = 鹿角怪\n春天 = 驼鹿/鹅\n夏天 = 蚁狮\n\n如果你设法在一年内击败它们，你会得到丰厚的回报！",
			COUNTER = "老板",
			HOVER = "在一年内杀死所有4个季节性老板",
		},
		["Across the Desert"] = {
			NAME = "穿越沙漠",
			DESCRIPTION = "我听说沙漠中有一种奇怪的生物。\n显然它很快就会生气，只有祭品才能安抚他。\n不幸的是，我们几乎没有这样的祭品了！\n如果有人能打败它，我们将永远感激的！",
		},
		["The Corrupt Darkness"] = {
			NAME = "腐败的黑暗",
			DESCRIPTION = "我目前正在做一些测试来分析查理的实力。\n我需要一个志愿者来吸收她的一些打击。\n如果你有受虐狂的特质，请接受！",
			COUNTER = "点击次数",
			HOVER = "接受查理的%s次攻击",
		},
		["The Legend of the Trade Road"] = {
			NAME = "贸易之路的传说",
			DESCRIPTION = "我们想加强与猪人的贸易关系。\n为此，我们需要你以我们的名义与猪王进行一些交易。\n你将得到相应的回报！",
			COUNTER = "交易",
			HOVER = "与猪王做%s次交易",
		},
		["The Vampire Dungeon"] = {
			NAME = "吸血鬼地牢",
			DESCRIPTION = "我们正试图探索地下，但不幸的是，我们遇到了卡住的地步！\n这些吸血蝙蝠正在吸干我们！\n请打败他们，以便我们前进！",
		},
		["Within the Stream"] = {
			NAME = "流内",
			DESCRIPTION = "我需要生活在这个世界海洋中的不同鱼类的样本。\n捕获 %s 条鱼并报告结果！",
			COUNTER = "钓到的鱼",
			HOVER = "捕获%s条鱼",
		},
		["Mage of the Manor Baldur"] = {
			NAME = "博德庄园的法师",
			DESCRIPTION = "我，博德庄园的大法师，邀请你参加考试！\n你需要传送一只鹿角怪！\n提示：你可以使用远程定位法杖。\n看看你是否有魔力来完成这个！",
			HOVER = "遥控鹿角的人",
			COUNTER = "鹿鼎记",
		},
		["The Rage of Ioun"] = {
			NAME = "艾恩之怒",
			DESCRIPTION = "我是约恩。自从我父亲进入树林收集一些丝绸以来，他就再也没有出现过。\n我敢肯定蜘蛛是罪魁祸首！\n愤怒开始吞噬我，但我还不够强大，无法抑制复仇的渴望！ \n请帮帮我！",
		},
		["The Sack For the Unlucky"] = {
			NAME = "倒霉的人的麻袋",
			DESCRIPTION = "我听说你喜欢坎普萨克。\n但我也听说你是个倒霉的家伙，我的哀悼。\n作为你不能接受的提议，如果你打败了他们，我会给你一个坎普萨克！",
		},
		["Below the Abandoned Land"] = {
			NAME = "废弃的土地下面",
			DESCRIPTION = "听说地下有数不清的宝物。\n我们做个交易，我给你位置，你去拿。\n然后我们就可以分享战利品了！\n宝物可以在生长在地下的石笋。",
			COUNTER = "石笋",
			HOVER = "在山洞的石笋中寻找宝藏",
		},
		["A Cute Companion"] = {
			NAME = "一个可爱的伙伴",
			DESCRIPTION = "我爱切斯特，就像我真的真的真的很爱他！\n我希望他有一个可以和他一起玩的朋友。\n我听说地下有一个和他相似的生物。\n请为我和切斯特去找他！",
			HOVER = "持有哈奇的鱼缸",
		},
		["The Allies Within the Land"] = {
			NAME = "土地上的盟友",
			DESCRIPTION = "每个人都需要朋友！\n这就是我想帮助人们找到朋友的原因。\n还有什么比奖励更好的动力...\n如果你有 %s 个朋友关注你，无论是猪、蜘蛛还是其他什么，我都不会”不在乎，我会奖励你的！",
			COUNTER = "跟随者",
			HOVER = "一次拥有%s个追随者",
		},
		["Orcus's Living Dead"] = {
			NAME = "奥库斯的活死人",
			DESCRIPTION = "出现在月球岛上的这些猎犬不正常，它们散发着死亡的光芒！\n我要在更糟糕的事情发生之前将它们根除！",
		},
		["The Damned Legacy"] = {
			NAME = "被诅咒的遗产",
			DESCRIPTION = "你好，我叫威尔巴，你可能认识我来自另一个大陆。\n因为我必须继承我父亲的遗产，所以我在每个满月都会变成一个狼人。\n但我不想再这样了！\n我听说诅咒可以如果你从人猪和猎犬手中保卫月亮石基地 %s 次，就会被打破！\n请帮帮我！",
			COUNTER = "捍卫的时代",
			HOVER = "保卫月球基地%s次",
		},
		["The Abandoned Chester"] = {
			NAME = "被遗弃的切斯特",
			DESCRIPTION = "我的织烟古人完全忘记了我，让我在这个残酷的世界中自生自灭！\n我已经感觉到我很快就会受到攻击，请帮助保护我！",
			COUNTER = "攻击波",
			HOVER = "保护切斯特!",
		},
		["The Sharks Demise"] = {
			NAME = "鲨鱼的灭亡",
			DESCRIPTION = "原谅我，冒险者。需要你的帮助。\n大自然是不稳定的，也是有充分理由的。某种恶魔的力量已经在这片土地上蔓延开来，起初很小，但它们每天都在变得强大。我们再也无法阻止他们只是时间问题。请英雄，找出他们的来源，摧毁它并摆脱那些可怜的石颚龙。\n英雄，在与石颚龙打交道时迅速采取行动。你想干多少就干多少，这世上的贱民越少越好。",
		},
		["The Houndstooth Curse"] = {
			NAME = "猎犬的诅咒",
			DESCRIPTION = "我寻求你的帮助，冒险家！\n可怜的座狼已经蹂躏了我们的小猪村！\n请打败他们，让我们再次和平相处！",
		},
		["The Possessed Crows"] = {
			NAME = "附属的乌鸦",
			DESCRIPTION = "我们的田地正在被乌鸦蹂躏。他们似乎被黑暗势力附身。\n不幸的是，我认为他们没有希望。请摆脱它们，否则我的家人会饿死！",
		},
		["Colors of the Rainbow"] = {
			NAME = "彩虹的颜色",
			DESCRIPTION = "冥界的暗影生物窃取了光之守护者的耀眼色彩。\n前往冥界，收集每种彩虹颜色的宝石。 \n当所有六颗不同的宝石都在你的口袋里时，我会拿走它们并认为任务完成了。 \n帮我把彩虹的所有颜色统一起来。",
			COUNTER = "发现不同的宝石",
			HOVER = "持有红色、蓝色、紫色、绿色、黄色和橙色的宝石",
		},
		["Bright Worshipnight"] = {
			NAME = "明亮的崇拜之夜",
			DESCRIPTION = "神圣的Glommer崇拜之夜即将来临，没有相关的道具是无法进行的。奋力越过猪群，得到格洛默之花和10只萤火虫，并在月圆之夜在格洛默雕像附近找到我为你提供的神圣木箱。",
			COUNTER = "倍受崇拜的格洛默",
			HOVER = "向格洛默宣讲",
		},
		["Mirror of Merms"] = {
			NAME = "梅尔姆斯之镜",
			DESCRIPTION = "沼泽中的生活是颠倒的！ \n沼泽人在受到攻击时开始释放气体。如果这些被吸入，世界开始转动。 \n杀死 %s 个沼泽人以防止这种变异被传播。",
		},
		["Giving back to Nature"] = {
			NAME = "回馈自然",
			DESCRIPTION = "黑夜看起来很危险，尤其是因为查理。 \n为了更无忧无虑的生活，我请萤火虫照亮我的路。",
			COUNTER = "萤火虫被释放",
			HOVER = "将%s只萤火虫扔在地上",
		},
		["A Crappy Day"] = {
			NAME = "糟糕的一天",
			DESCRIPTION = "我今天过得很糟糕，我希望有人感觉如此糟糕！ \n请帮我完成这个狗屎！",
			COUNTER = "时代得到狗屎",
			HOVER = "被投掷的大便击中%s次",
		},
		["Revenge of the crapped victim"] = {
			NAME = "被拉屎的受害者的复仇",
			DESCRIPTION = "上次去废墟后，衣服上的屎都洗不掉，我要报复这些生物！ \n让他们偷走一只羊羊的痰，让他们知道什么是真正的厌恶！",
			COUNTER = "盗取的痰液",
			HOVER = "让猴子偷东西 1 痰",
		},
		["Luminous globules"] = {
			NAME = "发光的球状物",
			DESCRIPTION = "长期以来，我一直是自然医学的倡导者。根据我的研究，灯泡在治疗方面显示出巨大的前景。\n亲自体验一下治疗效果，并报告结果。",
			COUNTER = "用电灯泡治愈",
			HOVER = "通过吃灯泡治愈%s个健康",
		},
		["Beary Hunger"] = {
			NAME = "饥饿的熊孩子",
			DESCRIPTION = "请帮助我，我快要饿死了，因为火鸡把我的浆果都吃光了。\n杀死这些野兽中的两个，我将与你分享我的浆果。",
		},
		Wetlands = {
			NAME = "湿地",
			DESCRIPTION = "湿润的感觉真好，难道你不想这样湿润吗？\n你能在%s分钟内做到比50%%更湿吗？",
			COUNTER = "湿润的秒数",
			HOVER = "在%s分钟内保持至少50%%的湿润度",
		},
		["Off to sea"] = {
			NAME = "出海",
			DESCRIPTION = "喂，你们这些陆地上的人! \n如果你想和我们一起出海，你必须先在你的库存中准备好所有的船的材料！你必须在你的库存中准备好。",
			COUNTER = "材料",
			HOVER = "在你的库存中持有一套船具、一支桨、一根桅杆、一个方向盘和一个锚。",
		},
		["Hidden Treasures"] = {
			NAME = "隐藏的宝藏",
			DESCRIPTION = "在海的深处，据说有无人见过的宝藏。\n如果你能钓出%s个这样的宝藏，你就会得到奖励!",
			COUNTER = "宝藏",
			HOVER = "使用Pinchin'绞盘提升%s个水下打捞物。",
		},
		["Off to donate blood"] = {
			NAME = "去献血了",
			DESCRIPTION = "血液储备很匮乏！我们猪甚至会取人血来补充储备。我们猪甚至会去取人血来补充我们的储备。\n愿意随时申请!",
			COUNTER = "献血次数",
			HOVER = "被蚊子袭击%s次",
		},
		["The Lonely Woven Shadow"] = {
			NAME = "孤独的织影",
			DESCRIPTION = "古老的燃料编织者让这个可怜的编织影子自生自灭! \n一些怪物想从古代燃料织造者那里得到一些报复，并决定攻击它，请保护他!",
			COUNTER = "攻击波",
			HOVER = "保护编织的影子!",
		},
		["The Eye of Cthulhu"] = {
			NAME = "克苏鲁之眼",
			DESCRIPTION = "我的眼睛又一次离开了我！它拒绝来到我身边！由于我现在很忙，我想雇一个冒险家来打败他，让我的眼睛回到我身边。",
		},
		["The Biggest Veggy"] = {
			NAME = "最大的%s",
			DESCRIPTION = "谁有最大的%s？我想举办一个比赛。如果你能种出重量超过目前记录的%s的%s，你将赢得一个特殊的价格",
			COUNTER = "%s",
			HOVER = "收获一个重量超过%s的%s!",
		},
		["A Sailor's Life"] = {
			NAME = "一个水手的生活",
			DESCRIPTION = "作为一个真正的水手，你在船上呆的时间越长越好！如果你向我们表明你是我们中的一员，我们会用小礼物欢迎你。",
			COUNTER = "在船上的秒数",
			HOVER = "每次在船上停留%s的时间而不离开!",
		},
		["Survival: Famine"] = {
			NAME = "生存：饥荒 %s",
			DESCRIPTION = "学习我们书库中的官方 \"生存技巧 \"手册的第一章 \"饥荒\"。把自己饿到痛苦的极限，检查这本参考书对你自己身体的效果！不要担心，事后会给你提供适当的补偿。别担心，事后我们会给你提供适当的补偿... \n\n~ The Quest Agency ~",
			COUNTER = "饥饿的损害",
			HOVER = "因饥饿而受到%s次伤害",
		},
		["Survival: Heart attack"] = {
			NAME = "存活率：心脏病发作 %s",
			DESCRIPTION = "从我们的藏书中学习官方 \"生存技巧 \"手册的第二章 \"心脏病\"。把自己逼到疯狂的边缘，看看我们的分步指南中的宝贵建议吧! 作为奖励，你还将获得3勺坚果冰淇淋作为补偿!\n\n~ The Quest Agency ~",
			COUNTER = "收到的损害",
			HOVER = "受到恐怖喙的%s次伤害",
		},
		["Survival: Frost Shock"] = {
			NAME = "生存：霜冻冲击 %s",
			DESCRIPTION = "S学习我们收藏的官方 \"生存技巧 \"手册中的第三章 \"霜冻冲击\"。忍受冰冷的风和颤抖的肢体，在书中的帮助下，检查你是否能保持温暖! 如果你成功地完成了他们的任务，你还会收到一些温暖的东西作为感谢! \n\n~ The Quest Agency ~",
			COUNTER = "冻害",
			HOVER = "受到%s次冰冻伤害",
		},
		["Survival: Heat exhaustion"] = {
			NAME = "生存：热衰竭 %s",
			DESCRIPTION = "学习我们书库中的官方 \"生存技巧 \"手册的第四章 \"中暑\"。在烈日炎炎、汗流浃背的温暖环境中坚持下去，并检查本章书页之间发现的减汗措施的有效性! 我们还保证在事后为你提供一顿清凉的饭菜，为你降温! \n\n~ The Quest Agency ~.",
			COUNTER = "过热的损害",
			HOVER = "因过热而受到%s的伤害",
		},
		["Survival: Life-threatening"] = {
			NAME = "存活率：有生命危险 %s",
			DESCRIPTION = "学习我们书库中的官方手册《生存技巧》的第5章 \"生命的危险\"。试着通过流血的方式尽可能地接近死亡，看看你是否能使用书中建议的技巧来摆脱这种危及生命的情况! 为了让你重回正轨，当地的面包大师还为你准备了一个惊喜作为奖励!\n\n ~ The Quest Agency ~",
			COUNTER = "濒临死亡的体验",
			HOVER = "有少于%s个健康状况",
		},
		["The True Enemy"] = {
			NAME = "真正的敌人",
			DESCRIPTION = "一个险恶的恐怖组织乘着它的翅膀在这片土地上滑行，它的名字叫Glommer...。许多人没有意识到这个邪恶的行者带来的危险，因此忽视了即将到来的危险。只有全力对你采取预防措施，才能阻止这种威胁。把世界从这个杀人的卵子中拯救出来，消灭我们所有人的真正的敌人!\n\n~ The Quest Agency ~",
		},
		["Treebeard's end"] = {
			NAME = "树熊的结局",
			DESCRIPTION = "这些树在森林里游荡，给我们的木柴收购工作带来了麻烦。它们干扰了我们的白桦林作业，并赶走了所有接近森林的人。请以身作则，用斧头砍掉这些树胡子中的一个。 \n\n~ The Quest Agency ~",
			COUNTER = "树木护卫队",
			HOVER = "用斧头杀死1个树人",
		},
		["Feeding Time"] = {
			NAME = "喂食时间",
			DESCRIPTION = "不惜一切代价保住你的队友的性命! 在最饥饿的时候把食物塞进你的同事嘴里，以拯救他。这可以促进友情，并对他们的团队精神发出强烈的信号!\n\n~ The Quest Agency ~",
			COUNTER = "玩家反馈",
			HOVER = "当1名玩家因饥饿而失去健康时，为他们提供食物",
		},
		["Catch the stick"] = {
			NAME = "接住棍子",
			DESCRIPTION = "我们的行为科学家已经做出假设，当地的狗也像普通的狗一样对 \"扔棍子 \"做出反应。通过尝试用棍子刺激这个世界上的一只狗，来检验这个令人兴奋的论点吧! \n\n~ The Quest Agency ~",
			COUNTER = "抛出的棍子",
			HOVER = "向猎犬投掷回旋镖%s次",
		},
		["Front Pigs"] = {
			NAME = "前面的猪",
			DESCRIPTION = "战争正在酝酿之中。我们需要有防御能力的前线猪来击退各种侵略者，保护我们的利益。但不幸的是，我们的工作机会似乎并没有到达任何一个当地的自由战士那里。亲自联系他们，并说服当地人跟随他们进入战斗! 我们会在不久之后提升你为猪将军!\n\n~ The Quest Agency ~",
			COUNTER = "猪的追随者",
			HOVER = "招募%s只猪，让它们在你身边战斗。",
		},
		["Detective Work"] = {
			NAME = "侦探工作",
			DESCRIPTION = "我正在寻找一个有读轨经验的人。有一些生物在这里游荡，但我似乎永远无法找到它们。\n如果你能找到他们中的3个，我将奖励你！。",
			COUNTER = "追踪到的污物堆",
			HOVER = "追踪3个粪堆，直到找到它们所属的生物。",
		},
		["Twins Of Destruction"] = {
			NAME = "毁灭的双胞胎",
			DESCRIPTION = "似乎有一个维度的裂缝，把不应该出现在这里的生物带到了这个世界！请打败他们，因为他们扰乱了整个生态系统！。",
			COUNTER = "恐怖的双胞胎",
			HOVER = "击败两个恐怖的双胞胎",
		},
		["The Biggest Frog"] = {
			NAME = "最大的青蛙",
			DESCRIPTION = "我听说山洞里有一只青蛙，它大得可以把人整个吞下去！我对青蛙有很强的恐惧症，不幸的是，这就是为什么它让我在探索山洞时有点紧张，请找到它并杀死它。",
		},
		["Ho Ho Ho"] = {
			NAME = "嗬嗬嗬",
			DESCRIPTION = "在我们的圣诞老人中似乎有一个冒名顶替者... .\n在这个世界上，圣诞老人并不分发他从圣诞老人协会得到的礼物，而是为自己囤积礼物。\n请打败他，让这个世界也能体验到圣诞节的快乐",
		},
		["The Impregnable Fortress"] = {
			NAME = "坚不可摧的堡垒",
			DESCRIPTION = "海中有一座似乎坚不可摧的堡垒。它由一个大得让你难以置信的怪物看守（或者说是堡垒本身）！\n有传言说那里藏有大量的宝藏。如果你打败了这个怪物，我们会给你相应的奖励",
		},
		["The Master Chef"] = {
			NAME = "大厨",
			DESCRIPTION = "我很想尝试一下沃布斯特晚餐，但是材料太难得到了，我无法做到！如果你能做这道菜并把它送给我，我会奖励你！",
			COUNTER = "煮熟的乌贼晚餐",
			HOVER = "烹饪%s个沃布斯特晚餐",
		},
		["Destroyer of Ancient Works"] = {
			NAME = "古代作品的破坏者",
			DESCRIPTION = "格洛默的追随者不希望在这个世界上有任何其他关于古代文明的提法，这使得它更难招募到追随者。\n用锤子摧毁古代文明的残余，不留任何痕迹！。",
			COUNTER = "古老的站台被摧毁",
			HOVER = "用锤子摧毁%s个完整/破损的古代伪科学站",
		},
		["The Goodest Boy"] = {
			NAME = "最优秀的男孩",
			DESCRIPTION = "谁是最乖的孩子？对，就是你，Houndius Shootius!\n你总是照顾那些攻击我的坏狗！\n但不幸的是，Houndius Shootius很孤独，因为他没有朋友。\n请再建造%s个这样的狗，让它有一些朋友可以一起玩!",
			COUNTER = "Houndius Shootius建造",
			HOVER = "部署%s个Houndius Shootius",
		},
		["The RPG Expert"] = {
			NAME = "角色扮演专家",
			DESCRIPTION = "我需要一个专业的RPG玩家的帮助! \n我似乎就是不能快速有效地提升等级。如果你能向我展示你知道你在做什么以及你是如何做的，我会奖励你！\n你只需要在任务日志中获得%s级。",
			COUNTER = "获得的级别",
			HOVER = "在任务日志中获得%s级",
		},
		["The Questing Adventurer"] = {
			NAME = "探索的冒险家",
			DESCRIPTION = "任务越来越多，但却没有足够的人去完成它们！\n这就是为什么我们现在提供了一个完成任务的激励机制。只有在这个任务激活时完成的任务才算数！\n完成%s个任务，你会得到一个特殊的奖励。",
			COUNTER = "任务完成",
			HOVER = "完成%s个任务",
		},
		["Night Angler"] = {
			NAME = "夜间钓鱼者",
			DESCRIPTION = "我们有一个怀疑，当地的鱼群最近改变了他们的行为。看看这些水域的鱼在晚上是否还在咬人！？ \n\n ~ The Quest Agency",
			COUNTER = "捕获的鱼类",
			HOVER = "在一个晚上捕获%s条鱼",
		},
		["Comrade Pig"] = {
			NAME = "小猪同志",
			DESCRIPTION = "到目前为止，人们对猪对过度消费怪物肉的反应了解不多。因此，请将大量的怪物肉喂给3个不同的标本，并记录它们的反应。我们期待你在明天早上之前的结果!\n\n ~ The Quest Agency ~",
			COUNTER = "猪的转变",
			HOVER = "把3头猪变成一个Werepig",
		},
		Kingfisher = {
			NAME = "翠鸟",
			DESCRIPTION = "我们所知道的大多数鸟类在冬季开始时向南迁移，直到春天变得温暖时才返回。但大型鸟类是个例外，它们必须永久抵御冬季的天气条件。为了验证这一事实，我们希望你能对不同的大鸟进行冷冻和解冻。请报告这些鸟儿是如何应对寒冷的!\n\n ~ The Quest Agency ~",
			COUNTER = "冷冻的高脚鸟",
			HOVER = "冻结%s只高脚鸟",
		},
		["The Mad Hatter"] = {
			NAME = "疯帽子",
			DESCRIPTION = "不幸的是，我们最好的制帽师已经消失得无影无踪了。然而，我们现在急需新的帽子。为此，我们要求你设计一个新的帽子系列并寄给我们。我们将向你发送一份我们需要你提供的帽子的清单。作为补偿，你将收到制帽师的旧雨帽。\n\n ~ The Quest Agency ~",
			COUNTER = "帽子制作",
			HOVER = "制作下列帽子。牛皮帽、羽毛帽、雨帽和猫帽",
		},
		["Wrong Offering"] = {
			NAME = "错误的祭品",
			DESCRIPTION = " 有时，为一个好的原因而牺牲是正确的。用一个痛苦的祭品来测试他们的牺牲意愿。确保你忠诚的伙伴切斯特有一个不光彩的结局。事后我们会给你分配一个更好的切斯特\n\n ~ The Quest Agency ~",
		},
		["Shadow World Manipulation"] = {
			NAME = "影子世界的操纵",
			DESCRIPTION = "扩大你的基地，帮助我们实现影子研究的最新发现。建立更多的影子操纵器来探索影子世界并进行突破性的实地测试! 我们指望着你!\n\n ~ The QueZzt Agenzy ~",
			COUNTER = "建造的影子操纵器",
			HOVER = "建造3个影子操纵器",
		},
		["Friends in the Shadow Realm"] = {
			NAME = "影界的朋友",
			DESCRIPTION = "你要比以前走得更远。你在影子研究方面加倍努力。你还没有理解与影子融为一体意味着什么。确保他们环境中的所有玩家也参与到影子研究中来! 同时睁开你的眼睛，看一看深邃的影子。我们期待着你的表现。\n\n ~ The QueZzt Agenzy ~",
			COUNTER = "秒钟",
			HOVER = "所有球员的理智值都要在10以下，时间为66秒。",
			HOVER1 = "在366秒内保持在10以下的理智值",
		},
		Spiderman = {
			NAME = "蜘蛛侠",
			DESCRIPTION = "我需要有人来消灭猪群，但不能让它们知道是我。\n如果你知道如何说服一些蜘蛛为我杀猪，你就是这个任务的最佳人选！\n你的奉献精神不会被遗忘。 你的奉献精神将不会被遗忘!",
			COUNTER = "猪",
			HOVER = "杀死%s头有蜘蛛跟随的猪",
		},
		["A Bunnys Job"] = {
			NAME = "兔子的工作",
			DESCRIPTION = "兔子人杀死蝙蝠，这就是世界一直以来的情况。\n这是他们唯一的目的... \n但最近，兔子人常常不知道他们必须杀死它们。\n这就是为什么我需要有人能告诉他们如何杀死蝙蝠的方法!",
			COUNTER = "蝙蝠",
			HOVER = "杀死%s只跟随你的兔子人的蝙蝠",
		},
		["Your Own Fault"] = {
			NAME = "你自己的错",
			DESCRIPTION = "我真的很抱歉MacTusks，但这是你自己的错...\n每次我们杀你的时候你都会把你的吹箭给我们，现在我想让他们感受一下我们被这些飞镖击中时的痛苦。\n用你选择的吹箭杀死他们中的%s个!",
			COUNTER = "MacTusk",
			HOVER = "用你选择的飞镖杀死%s个MacTusks。",
		},
		["Death By Self"] = {
			NAME = "死于自我",
			DESCRIPTION = "猪似乎是一种愚蠢的生物，但我想研究一下这个问题。它们能理解复杂的情况吗？\n要做到这一点，我希望你用火腿棒杀死%s头猪。\n如果他们明白为什么这样做是件坏事，我的实验就成功了！",
			COUNTER = "猪",
			HOVER = "用火腿棒杀死%s头猪",
		},
		["The Inner Monster"] = {
			NAME = "内在的怪物",
			DESCRIPTION = "在每只猪身上都有一个内心的怪物在肆虐...\n我希望你能解放它，因为猪不应该生活在恐惧中，让它们内心的恶魔出来。\n把%s只猪从这些社会规范中解放出来，把它们变成狼人！",
			COUNTER = "猪到韦里皮格",
			HOVER = "给%s头猪喂食，让它们变成韦里皮格。",
		},
		["The Boxer"] = {
			NAME = "拳击手",
			DESCRIPTION = "如果你想成为最好的，你必须向最好的学习！\n而我就是最好的。而我就是最棒的！\n我为你提供个人训练课程，与我自己，不败的恒定的拳击冠军！我们将从基础开始，只用你的拳头打出150的伤害。\n我们将从基本功开始，只用你的拳头就能造成%s的伤害！这就是我们的目的。",
			COUNTER = "损害",
			HOVER = "用你的拳头造成%s的伤害",
		},
		["The Dish for the Pig"] = {
			NAME = "为猪做的菜",
			DESCRIPTION = "即使是像我这样的猪也觉得有必要犒劳自己。\n这就是为什么我会奖励给另一只猪喂食沃布斯特晚餐的人。\n这样一来，他们也会接触到烹饪世界。",
			COUNTER = "渥太华晚餐费",
			HOVER = "给猪喂食沃布斯特晚餐",
		},
		["A Useful Companion"] = {
			NAME = "一个有用的伙伴",
			DESCRIPTION = "牛肉看起来像是不关心其他人的生物，但我可以向你保证，情况并非如此！我想向世界展示这些可爱的伙伴，它们的回报将超过它们的付出.骑一个%s秒，看看我是什么意思。",
			COUNTER = "骑行秒数",
			HOVER = "骑牛%s秒",
		},
		["Marble Trees?!"] = {
			NAME = "大理石树?！",
			DESCRIPTION = "显然，有可能种植大理石豆来使大理石生长。这只是一些对我来说没有什么意义的事情...（如果这是真的，一定有什么是我所忽略的... 它们是如何获得能量来生长的？\n请种植%s颗大理石豆，我想看到它们成长，以推动我的研究！",
			COUNTER = "种植大理石树",
			HOVER = "种植%s颗大理石树",
		},
		["The Stonemason"] = {
			NAME = "石匠",
			DESCRIPTION = "大理石是有用的材料，尽管据说它与这个世界的阴影有联系。\n这就是为什么我想要一个知道如何用大理石制作装备的人，这样他就可以教我如何做了！通过制作%s件大理石盔甲来告诉我如何做",
			COUNTER = "大理石盔甲",
			HOVER = "制作%s件大理石盔甲",
		},
		["The Shadow Plague"] = {
			NAME = "影子瘟疫",
			DESCRIPTION = "最近这些时间，影子生物对我们的人口构成了真正的威胁。我们需要帮助来控制它们的数量。\n欢迎每个人帮助杀死尽可能多的影子生物，前%s名将获得奖励！",
			COUNTER = "影子生物",
			HOVER = "击败%s个影子生物",
		},
		["The Pieces of Downfall"] = {
			NAME = "衰落的碎片",
			DESCRIPTION = "看来我们最近的清洗行动唤醒了那些最好让它们沉睡的力量...影子碎片几乎被唤醒了！\n如果他们达到这个阶段，这个世界将被毁灭！如果你能在他们完全觉醒之前打败他们，你就能拯救我们所有人！\n要做到这一点，你需要建造它们相应的大理石雕像，并在满月时摧毁这些雕像。",
			COUNTER = "影子棋子",
			HOVER = "建造一个车、马和主教的大理石雕像，在满月时摧毁它们，并杀死影子棋子",
		},
		["The Ancient Craft"] = {
			NAME = "古代工艺",
			DESCRIPTION = "我真的有一些雷石，但我还没有强大到可以在废墟中生存...\n拜托，如果有人还知道如何用雷石碎片制造雷石的古老工艺，那就快来吧!",
			COUNTER = "滑石工艺",
			HOVER = "工艺 %s 遒力石",
		},
		["The Shadow Slayer"] = {
			NAME = "影子杀手",
			DESCRIPTION = "这些噩梦般的影子已经占领了废墟! 在恶梦周期中，有这么多。\n我需要有人杀一些，这样我就可以安全地到下面去了！",
			COUNTER = "杀死的影子",
			HOVER = "在废墟的恶梦循环中杀死%s个影子生物",
		},
		["Suicidal Thoughts"] = {
			NAME = "自杀的念头",
			DESCRIPTION = "我曾经有一个朋友告诉我，他能够在25个火药堆的爆炸中存活下来! \n不知道他是如何做到这一点的，而且他后来又因另一次不幸的爆炸而死亡... \n如果你能在这样的爆炸中幸存下来，请告诉我你是如何做到的。",
			COUNTER = "在爆炸中幸存下来",
			HOVER = "在至少25个火药堆的爆炸中幸存下来",
		},
		["The Untalented Chef"] = {
			NAME = "无能的厨师",
			DESCRIPTION = "我的生活结束了! 我被烹饪学校开除了! \n那是我最大的梦想! 就因为我只能做湿漉漉的果酱... \n我需要一些东西让我振作起来，让我知道我不是唯一一个煮湿糊糊的人！",
			COUNTER = "煮好的湿果酱",
			HOVER = "烹调%s湿果酱",
		},
		["The Flower Lover"] = {
			NAME = "爱花之人",
			DESCRIPTION = "我喜欢花.. 这可能是我被称为 爱花之人 的原因。\n我希望让这个世界充满鲜花! \n种植%s朵花，帮助我实现我的梦想!",
			COUNTER = "种植的花朵",
			HOVER = "种植%s朵花",
		},
		["The Fish Fisher"] = {
			NAME = "%s费希尔",
			DESCRIPTION = "我急需一个%s来完成我的一个特殊项目! 但我似乎抓不到它们! 如果有人能给我带来5个，我将非常感激!",
			COUNTER = "捕捞的%s",
			HOVER = "鱼类 2 %s",
		},
		["The Tormented Dust Moth"] = {
			NAME = "饱受折磨的尘土飞蛾",
			DESCRIPTION = "我个人认识的一只尘土飞蛾已经被强壮的生物骚扰了相当长的一段时间！他们想偷走他们长期以来致力于种植的雷石。 他们想偷走他们已经努力生长了很久的雷公石。 如果你帮助保护他们，他们会用一块这块雷石来奖励你，并对你施以保护性的咒语!",
			COUNTER = "尘螨保护",
			HOVER = "保护尘土飞蛾不受产卵生物的影响，持续5波。",
		},
		["The Sleeping Beauty"] = {
			NAME = "睡美人",
			DESCRIPTION = "该睡美容觉了！。有这么多工作要做，很容易就会过度疲劳。照顾好自己，给自己和身体一个喘息的机会！",
			COUNTER = "睡了几秒钟。",
			HOVER = "在帐篷或类似地方睡了%s秒。",
		},
		["The Ocean Chose Me!"] = {
			NAME = "海洋选择了我！",
			DESCRIPTION = "海洋迷失自我的地方漂浮着一种声音，它在召唤我！。那么它远吗？Am I ready?n 海洋已经选择了你来收割%s的海草。所以，请加入进来并说：我很乐意！",
			COUNTER = "收获的海草",
			HOVER = "徒手收割%s海草的藤壶！",
		},
		["The Seven Dwarfs"] = {
			NAME = "七个小矮人",
			DESCRIPTION = "白雪公主需要你的帮助! 你的小矮人朋友在挖矿时挖得太深了，掉进了恒河沙数里！在这样的情况下，他们变成了一个个小矮人。这样一来，他们就变成了僵硬的人物。帮助她再次找到他们，把他们交给猪王，把他们送回他们的世界！",
			COUNTER = "矮人",
			HOVER = "把七个小矮人交给猪王！",
		},
		["The Cold Never Bothered Me Anyway!"] = {
			NAME = "寒冷现在是我的一部分！",
			DESCRIPTION = "我正在放手！现在就放手！。现在放开了！。不再有饥饿折磨我，不再有生物让我发疯，而寒冷现在也是我的一部分！。证明你和艾尔莎一样，已经为自由做好了准备，证明你不介意寒冷、饥饿和疯狂！",
			COUNTER = "无忧无虑的秒",
			HOVER = "保持饥饿、寒冷和低于10的理智%s秒。",
		},
		["Kiss The Frog!"] = {
			NAME = "亲吻青蛙！",
			DESCRIPTION = "有时你必须亲吻很多青蛙，直到你找到你的王子。面对足够多的青蛙，你就会成为一个真正的青蛙王子！但要注意：青蛙很少有机会亲吻。但要注意：青蛙很少单独来！",
			COUNTER = "青蛙",
			HOVER = "杀死%s青蛙，找到你的王子！",
		},
		["The Dangerous Widow"] = {
			NAME = "危险的寡妇",
			DESCRIPTION = "我们想开垦这片土地，为此我们需要消灭这只蜘蛛！\n杀死它，我们会奖励你的。",
		},
		["The Mad Adventurer"] = {
			NAME = "疯狂的冒险家",
			DESCRIPTION = "我听说有一种影子生物是如此可怕和畸形，从来没有人在与它的接触中幸存下来并讲述这个故事。\n如果你能打败它，我会奖励你的。",
		},
		["Your True Friends"] = {
			NAME = "你真正的朋友",
			DESCRIPTION = "你的工作做得非常好，非常好......。我们会给你很高的报酬。是的，我们会的。当你为我们在Zhadowz做了很好的研究时，我们能够找到你的一个老朋友来重聚。他期待着再次见到你，因为你是一个可以信赖的人......。他只是很想...你最好把你的整个团队都带上... ...我们会奖励你们所有人的劳动成果... （QueZzt机构）",
			COUNTER = "朋友z",
			HOVER = "到格罗默雕像去见你的朋友zzz...",
		},
		["The Scientist"] = {
			NAME = "科学家》杂志",
			DESCRIPTION = "我需要一个和我一样热爱科学的人!\n建造3个炼金术引擎，向世界展示科学是多么令人敬畏!",
			COUNTER = "建造的炼金术引擎",
			HOVER = "建立3个炼金引擎",
		},
		["The Arsonist"] = {
			NAME = "纵火犯",
			COUNTER = "火灾开始",
			HOVER = "用打火机点燃10件东西",
			DESCRIPTION = "我的大多数朋友都不想和我有任何关系，只是因为有时我想点燃一些东西。\n他们不明白火有多美......。\n通过点燃10件东西来告诉我我们可以成为朋友!",
		},
		["The Gravedigger"] = {
			NAME = "掘墓人",
			DESCRIPTION = "在墓地阴森寂静的环境中，您将挖掘出 % 的坟墓，探索未知的世界。当你的铲子铲起泥土时，你可能会发现被遗忘的遗物、遗失的纪念品，甚至是古老的诅咒。每个坟墓都有自己的故事，您的好奇心将引导您揭开它们神秘的过去。",
			COUNTER = "格雷夫斯",
			HOVER = "挖掘 %s 座坟墓",
		},
		["I've got 99 problems but starving ain't one!"] = {
			NAME = "我有 99 个问题，但挨饿不是其中之一！",
			DESCRIPTION = "尽管在这个世界上挨饿的概率相当高，但我听说有些居民在食物方面相当富有。让我看看是否有这样的人，他们吃掉的食物热量占总热量的%，却一次也没有挨饿！",
			COUNTER = "卡路里",
			HOVER = "吃掉 %s 卡路里的食物",
		},
		["The Untouchable"] = {
			NAME = "贱民",
			DESCRIPTION = "你能成为 \"不可触碰者 \"吗？触不可及 \"是一个强大到无法被任何东西触及的实体！只要在 %s 秒内不受任何伤害，就能证明自己是否配得上这个称号！",
			COUNTER = "秒数",
			HOVER = "在 %s 秒内保持未损坏状态",
		},
		["The Hunted Glommer"] = {
			NAME = "被猎杀的格洛莫",
			DESCRIPTION = "一个可怜的 Glommer 正被一些冷酷无情的掠食者猎杀！帮助他逃脱，至少这一次！",
			COUNTER = "攻击波",
			HOVER = "保护 Glommer！Glommer 会在 2-3 分钟后出现！",
		},
		["The Stray Hutch"] = {
			NAME = "流浪的哈奇",
			DESCRIPTION = "我的哈奇离家出走了！如果你们找到它，请小心它可能面临的危险。很多动物似乎一看到它就想伤害它！",
			COUNTER = "攻击波",
			HOVER = "保护 Hutch！Hutch 会在 2-3 分钟后出现！",
		},
		["The Healer"] = {
			NAME = "医者",
			DESCRIPTION = "治疗师是团队中最重要的成员。让我看看你是否有能力提供必要的治疗，是否值得通过治疗 %s 健康值来保护自己！",
			COUNTER = "健康痊愈",
			HOVER = "治疗 %s 的健康状况",
		},
		["The Attacker"] = {
			NAME = "攻击者",
			COUNTER = "造成的伤害",
			HOVER = "在 30 秒内造成 %s 的伤害",
			DESCRIPTION = "一个团队中最重要的成员是攻击者。让我看看你是否能提供必要的攻击力，值得在 30 秒内打出 %s 的伤害！",
		},
		["The Defender"] = {
			NAME = "捍卫者",
			DESCRIPTION = "一个团队中最重要的成员就是防御者。让我看看，你能提供必要的防御力，值得被治疗！",
			COUNTER = "损坏停止",
			HOVER = "阻止 %s 护甲伤害",
		},
		["Axe-swinging Competition"] = {
			NAME = "抡斧比赛",
			DESCRIPTION = "我们正在举行一场抡斧比赛。如果你认为自己有这个能力，请接受这个任务！您需要在 3 分钟内砍倒 %s 棵树！砍下第一棵树后，比赛就开始了！",
			COUNTER = "砍伐树木",
			HOVER = "在 3 分钟内砍伐 %s 棵树",
		},
		["Pickaxe-swinging Competition"] = {
			NAME = "抡镐比赛",
			DESCRIPTION = "我们正在举行抡镐比赛。如果你认为自己有这个能力，就接受这个任务吧！您需要在 3 分钟内开采 %s 的岩石！比赛从您挖出第一块石头开始！",
			COUNTER = "开采的岩石",
			HOVER = "3 分钟内开采 %s 岩石",
		},
		["Shovel-digging Competition"] = {
			NAME = "铲土比赛",
			DESCRIPTION = "我们正在举行一场铲土比赛。如果你认为自己有这个能力，就接受这个任务吧！您需要在 3 分钟内挖出 %s 的东西！一旦您挖出第一件东西，比赛就开始了！",
			COUNTER = "挖出的东西",
			HOVER = "在 3 分钟内挖掘 %s 的内容",
		},
		["The Fatal Rose"] = {
			NAME = "致命玫瑰",
			DESCRIPTION = "小时候，我曾碰过一朵玫瑰，差点因此丧命！但从来没有人相信我的话，玫瑰是邪恶的生物，甚至会杀死你！帮我向他们证明，只要他们愿意，玫瑰也会杀死你的",
			COUNTER = "死亡",
			HOVER = "死于玫瑰",
		},
		["The Bird Predator"] = {
			NAME = "鸟类捕食者",
			DESCRIPTION = "鸟只是查理派来观察我们的无人机！我想让它们消失，为此我需要一个鸟类捕食者！在接下来的 8 分钟内杀死 %s 的红鸟，证明你的价值！",
			COUNTER = "红鸟",
			HOVER = "在接下来的 8 分钟内杀死 %s 红鸟",
		},
		["A Werepigs Worst Nightmare"] = {
			NAME = "最可怕的噩梦",
			DESCRIPTION = "山洞里好像有一只黄鼠狼，个头很大，没人敢靠近它。但是，我们不应该仅仅害怕狼猪！所以我希望有人能让这只所谓的 \"噩梦狼猪 \"知道，人类才是它们最大的噩梦！",
		},
		["The Nightmare Trio"] = {
			NAME = "噩梦三人组",
			DESCRIPTION = "我们想在洞穴里开采一些可怕的石头，但不幸的是，墨水怪似乎并不喜欢这样做！请帮助我们打败他们！",
			COUNTER = "墨水灼伤",
			HOVER = "杀死全部 3 个墨水暴徒",
		},
		["The Acid Bath"] = {
			NAME = "酸浴",
			DESCRIPTION = "我想研究一个人能承受多少酸。因此，我正在为这项研究寻找志愿者。我们将从洞穴中的酸雨中的 %s 秒开始，但要在没有保护措施的情况下进行，否则研究将被伪造！",
			COUNTER = "秒数",
			HOVER = "在没有保护措施的情况下，在酸雨中可承受 %s 秒的时间",
		},
		["A Great Ryft"] = {
			NAME = "伟大的雷夫特",
			DESCRIPTION = "新出现的 Ryftals 似乎很有趣，我想知道它们会带来什么样的战利品！我需要有人开采出 %s 的矿石，这样我就能看到里面的东西了。",
			COUNTER = "开采的 Ryftals",
			HOVER = "地雷 %s ryftals",
		},
		["A Grazers Nightmare"] = {
			NAME = "放牧人的噩梦",
			DESCRIPTION = "食草动物似乎会保护 ryftals，但我真的需要在它们不打扰我的情况下调查它们！谁来帮帮我，对它们造成 %s 的伤害！",
			COUNTER = "造成的伤害",
			HOVER = "对食草动物造成 %s 的伤害",
		},
		["Closest To Oneself"] = {
			NAME = "最接近自己",
			DESCRIPTION = "每个人都有特殊才能！我希望你能培养这些才能！制作 %s 只有你才能制作的物品，我会给你一点奖励！",
			COUNTER = "角色专用手工艺品",
			HOVER = "制作 %s 角色专用物品",
		},
		["Kill The Lord"] = {
			NAME = "杀死上帝",
			DESCRIPTION = "虽然果蝇王已经守护我们村子有一段时间了，但它最近开始攻击我们的农民和牲畜。因此，我们只有一个选择，那就是向上帝求死！不幸的是，我们不够强大，请帮助我们！",
		},
		["Kill The Innocent"] = {
			NAME = "杀死无辜者",
			DESCRIPTION = "苔藓人在妈妈身边的时候是多么天真无邪，可一旦妈妈不在了，他们就变成了怪物。不幸的是，当它们生气时，它们的肉就不再那么美味了......我需要有人杀死 % 的无辜苔藓人来享受美味肉类的乐趣！",
			COUNTER = "无辜的苔藓人",
			HOVER = "杀死 %s 未被激怒的苔藓人",
		},
		["Defeating Rocky"] = {
			NAME = "打败洛奇",
			DESCRIPTION = "我以前最好的朋友岩石龙虾洛奇可怕地背叛了我。我想杀了他的一个兄弟来报答他。这样他也许能感受到一点他给我带来的痛苦。",
		},
		["I'm The Pirate Now!"] = {
			NAME = "现在我是海盗",
			DESCRIPTION = "呀哈哈最近，海盗们在这里游荡的频率越来越高了。让他们看看，角色的转换对我们有利！",
		},
	},
	QUEST_FUNCTIONS = {
		SANITY_90 = "一次性保持在90%以上的理智状态 x 秒!",
		SANITY_10 = "一次性保持在10%以下的理智状态 x 秒!",
		LUNACY_10 = "一次性保持在10%的Lunacy以下 x 秒!",
		LUNACY_90 = "一次性保持在90%以上的疯癫状态 x 秒!",
		MONSTERLASAGNA = "食用 x 怪物拉萨格纳",
		SURFNTURF = "食用 x 冲浪的草地",
		LOBSTERDINNER = "食用 x 沃布斯特晚餐",
		LEAFLOAF = "食用 x 叶子肉饼",
		JELLYBEAN = "食用 x 糖豆",
		KOALEFIG_TRUNK = "食用 x 无花果树的树干",
		BARNACLESUSHI = "食用巴纳克炸鱼",
		FOSSILS = "通过采矿找到 x 个化石",
		GOLDNUGGETS = "通过采矿找到 x 金块",
		REDGEM = "通过采矿找到 x 颗红色宝石",
		BLUEGEM = "通过采矿找到 x 颗蓝色宝石",
		PURPLEGEM = "通过采矿找到 x 颗紫色宝石",
		GREENGEM = "通过采矿找到 x 颗绿色宝石",
		YELLOWGEM = "通过采矿找到 x 颗黄色宝石",
		ORANGEGEM = "通过采矿找到 x 颗橙色宝石",
		LIVINGLOG = "通过砍伐找到 x 个活体原木",
		LIFEAMULET = "通过挖掘找到 x 个生命护身符",
		GEARS = "通过挖掘找到 x 齿轮",
		CHARLIE = "被查理打了 x 次",
		TRADES = "与猪王交易 x 次",
		TRINKET_12 = "与猪王交换 x 次甜品触角",
		TRINKET_8 = "与猪王交易 x 次硬化橡胶塞",
		TRINKET_24 = "与猪王交换 x 次幸运猫罐子",
		TRINKET_26 = "与猪王交换 x 次土豆杯",
		FISHING = "捕获 x 鱼",
		ICEBREAM = "捕获 x 冰激凌",
		DEEPBASS = "捕获 x 深海鲈鱼",
		SPITTLEFISH = "捕获 x 唾液鱼",
		SUNFISH = "捕获 x 炙热的太阳鱼",
		TUNA = "捕获 x 布隆芬金枪鱼",
		FALLOUNDER = "捕获 x Fallounder",
		CORNCOD = "捕获 x 玉米鳕鱼",
		TELEPORT = "传送 x 次的东西离开",
		T_BEEFALO = "将 x 只牛魔王传送走",
		T_DEERCLOPS = "将 x 个Deerclops传送走",
		T_BEARGER = "传送 x 个熊人离开",
		T_DRAGONFLY = "传送 x 蜻蜓离开",
		T_MOOSE = "将麋鹿/鹅传送走",
		MOONBASE = "保卫 x 倍的月球基地",
	},
}